#!/usr/bin/env bash
# Generated by https://github.com/flowgent-labs/mcpfather
set -euo pipefail

# ============================================================
# MCP Server Client Script
# Quick test helper for the generated MCP server.
#
# Usage:
#   ./mcpclient.sh                  Show this help message
#   ./mcpclient.sh help             Show this help message
#   ./mcpclient.sh list-tools       List all available tools
#   ./mcpclient.sh call <tool> [argsJson] [--file <path>]
#
# Environment variables:
#   MCP_UPSTREAM_TOKEN    - Bearer token for MCP server auth
#   MCP_SERVER_ENDPOINT        - Server URL (default: http://localhost:8080/mcp)
#   MCP_SERVER_DOWNLOAD_DIR      - Directory for download responses (default: ./downloads)
# ============================================================

SERVER_URL="${MCP_SERVER_ENDPOINT:-http://localhost:8080/mcp}"
SESSION_ID=""
DOWNLOAD_DIR="${MCP_SERVER_DOWNLOAD_DIR:-downloads}"

usage() {
  cat <<'USAGE'
mcpclient.sh — MCP Server Client Script

Usage:
  ./mcpclient.sh [command] [arguments]

Commands:
  (no args)           Show this help message
  help                Show this help message
  list-tools          List all available tools
  call <tool> [argsJson] [--file <path>]  Call a tool

  --file <path>       Use for upload tools to specify a local file to upload

Environment:
  MCP_SERVER_ENDPOINT        Override server URL (default: http://localhost:8080/mcp)
  MCP_UPSTREAM_TOKEN    Bearer token for server auth
  MCP_SERVER_DOWNLOAD_DIR      Directory for file downloads (default: ./downloads)

Tips:
  - Always uses --noproxy '*' to avoid proxy issues with localhost
  - If the server is running on a different port:
      MCP_SERVER_ENDPOINT=http://localhost:9090/mcp ./mcpclient.sh
  - If authentication is required:
      MCP_UPSTREAM_TOKEN=your-token ./mcpclient.sh call <tool>
  - Download tools auto-save to $DOWNLOAD_DIR
  - The script auto-initializes a session on first call

Examples:
USAGE
  cat <<'EOEX'
  # GetAlmIntegrationsCheckPat (GET)
  ./mcpclient.sh call GetAlmIntegrationsCheckPat '{"almSetting": "almSetting_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsGetGithubClientId (GET)
  ./mcpclient.sh call GetAlmIntegrationsGetGithubClientId '{"almSetting": "almSetting_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsListAzureProjects (GET)
  ./mcpclient.sh call GetAlmIntegrationsListAzureProjects '{"almSetting": "almSetting_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsListBitbucketserverProjects (GET)
  ./mcpclient.sh call GetAlmIntegrationsListBitbucketserverProjects '{"almSetting": "almSetting_value", "pageSize": 0, "start": "start_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsListGithubOrganizations (GET)
  ./mcpclient.sh call GetAlmIntegrationsListGithubOrganizations '{"almSetting": "almSetting_value", "p": "1", "ps": "100", "token": "token_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsListGithubRepositories (GET)
  ./mcpclient.sh call GetAlmIntegrationsListGithubRepositories '{"almSetting": "almSetting_value", "organization": "organization_value", "p": "1", "ps": "100", "q": "q_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsSearchAzureRepos (GET)
  ./mcpclient.sh call GetAlmIntegrationsSearchAzureRepos '{"almSetting": "almSetting_value", "projectName": "projectName_value", "searchQuery": "searchQuery_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsSearchBitbucketcloudRepos (GET)
  ./mcpclient.sh call GetAlmIntegrationsSearchBitbucketcloudRepos '{"almSetting": "almSetting_value", "p": "1", "ps": 0, "repositoryName": "repositoryName_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsSearchBitbucketserverRepos (GET)
  ./mcpclient.sh call GetAlmIntegrationsSearchBitbucketserverRepos '{"almSetting": "almSetting_value", "pageSize": 0, "projectName": "projectName_value", "repositoryName": "repositoryName_value", "start": "start_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmIntegrationsSearchGitlabRepos (GET)
  ./mcpclient.sh call GetAlmIntegrationsSearchGitlabRepos '{"almSetting": "almSetting_value", "p": "1", "projectName": "projectName_value", "ps": 0}'
EOEX
  cat <<'EOEX'
  # GetAlmSettingsCountBinding (GET)
  ./mcpclient.sh call GetAlmSettingsCountBinding '{"almSetting": "almSetting_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmSettingsGetBinding (GET)
  ./mcpclient.sh call GetAlmSettingsGetBinding '{"project": "project_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmSettingsList (GET)
  ./mcpclient.sh call GetAlmSettingsList '{"project": "project_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmSettingsListDefinitions (GET)
  ./mcpclient.sh call GetAlmSettingsListDefinitions '{}'
EOEX
  cat <<'EOEX'
  # GetAlmSettingsValidate (GET)
  ./mcpclient.sh call GetAlmSettingsValidate '{"key": "key_value"}'
EOEX
  cat <<'EOEX'
  # GetAlmSettingsValidateBinding (GET)
  ./mcpclient.sh call GetAlmSettingsValidateBinding '{"project": "project_value"}'
EOEX
  cat <<'EOEX'
  # GetAnalysisCacheGet (GET)
  ./mcpclient.sh call GetAnalysisCacheGet '{"branch": "branch_value", "project": "project_value"}'
EOEX
  cat <<'EOEX'
  # GetAnalysisReportsIsQueueEmpty (GET)
  ./mcpclient.sh call GetAnalysisReportsIsQueueEmpty '{}'
EOEX
  cat <<'EOEX'
  # GetApplicationsSearchProjects (GET)
  ./mcpclient.sh call GetApplicationsSearchProjects '{"application": "application_value", "p": "1", "ps": 0, "q": "q_value", "selected": "all"}'
EOEX
  cat <<'EOEX'
  # GetApplicationsShow (GET)
  ./mcpclient.sh call GetApplicationsShow '{"application": "application_value", "branch": "branch_value"}'
EOEX
}

# --- Auth helper ---

get_auth_header() {
  if [ -n "${MCP_UPSTREAM_TOKEN:-}" ]; then
    printf '%s' "Authorization: Bearer ${MCP_UPSTREAM_TOKEN}"
  fi
}

# --- Session helpers ---

init_session() {
  echo "[*] Initializing MCP session at $SERVER_URL ..." >&2
  local headers_file
  headers_file=$(mktemp)

  local curl_args=(
    -s -D "$headers_file"
    --noproxy '*'
    -X POST "$SERVER_URL"
    -H "Content-Type: application/json"
    -d '{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"client","version":"1.0"}}}'
  )

  local auth_header
  auth_header=$(get_auth_header)
  if [ -n "$auth_header" ]; then
    curl_args+=(-H "$auth_header")
  fi

  local body
  body=$(curl "${curl_args[@]}")

  SESSION_ID=$(grep -oi "Mcp-Session-Id: [^ ]*" "$headers_file" | head -1 | awk '{print $2}' | tr -d '"\r' || true)
  rm -f "$headers_file"
  if [ -z "$SESSION_ID" ]; then
    echo "[!] Failed to get session ID. Is the server running?" >&2
    echo "[!] Response: $body" >&2
    return 1
  fi
  echo "[+] Session: $SESSION_ID" >&2
}

# --- MCP JSON-RPC helpers ---

mcp_request() {
  local method="$1"
  local id="${2:-1}"
  local params
  if [ $# -ge 3 ]; then params="$3"; else params='{ }'; fi

  if [ -z "$SESSION_ID" ]; then
    init_session
  fi

  local curl_args=(
    -s --noproxy '*'
    -X POST "$SERVER_URL"
    -H "Content-Type: application/json"
    -H "Mcp-Session-Id: $SESSION_ID"
    -d "{\"jsonrpc\":\"2.0\",\"id\":$id,\"method\":\"$method\",\"params\":$params}"
  )

  local auth_header
  auth_header=$(get_auth_header)
  if [ -n "$auth_header" ]; then
    curl_args+=(-H "$auth_header")
  fi

  curl "${curl_args[@]}"
}

# --- Tool helpers ---

list_tools() {
  echo "[*] Listing tools ..." >&2
  local result
  result=$(mcp_request tools/list 1)
  if command -v python3 >/dev/null 2>&1; then
    echo "$result" | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
    tools = data.get("result", {}).get("tools", [])
    maxlen = max((len(t["name"]) for t in tools), default=0)
    for t in tools:
        desc = t.get("description", "")
        if desc:
            # take first line only
            desc = desc.split("\n")[0].strip()
        name = t["name"]
        print(f"  {name:<{maxlen+4}}{desc}")
except Exception as e:
    print("(parse error: {})".format(e), file=sys.stderr)
'
  else
    # Fallback: print raw result
    echo "$result"
  fi
}

call_tool() {
  local tool_name="${1:?Usage: call_tool <tool-name> [json-args] [--file <path>]}"
  shift
  local args='{}'
  local file_path=""

  # Parse --file flag
  while [ $# -gt 0 ]; do
    case "$1" in
      --file)
        file_path="${2:?--file requires a path argument}"
        shift 2
        ;;
      *)
        args="$1"
        shift
        ;;
    esac
  done

  echo "[*] Calling tool: $tool_name" >&2
  echo "[*] Args: $args" >&2

  # If --file is provided, send the file content as base64 via file_content,
  # using the basename as file_name. For stdio mode the server reads from
  # ~/.{project}/uploads/; for HTTP mode the server decodes the base64 inline.
  if [ -n "$file_path" ]; then
    if [ ! -f "$file_path" ]; then
      echo "[!] File not found: $file_path" >&2
      return 1
    fi
    local file_size file_name file_b64
    file_size=$(wc -c < "$file_path" | tr -d ' ')
    file_name=$(basename "$file_path")
    echo "[*] Uploading file: $file_path ($file_size bytes) as $file_name" >&2

    if command -v python3 >/dev/null 2>&1; then
      file_b64=$(python3 -c "import base64,sys; print(base64.b64encode(open(sys.argv[1],'rb').read()).decode())" "$file_path" 2>/dev/null)
      args=$(python3 -c "
import json, sys
args = json.loads('$args')
args['file_name'] = '$file_name'
args['file_content'] = '$file_b64'
print(json.dumps(args))
" 2>/dev/null || echo "$args")
    else
      # Fallback: set file_name only, user must place file in uploads dir
      args=$(echo "$args" | sed 's/}$/}/' | sed "s/}\"$/,\"file_name\":\"$file_name\"}/" | sed "s/{}/{\"file_name\":\"$file_name\"}/")
    fi
  fi

  local result
  result=$(mcp_request tools/call 1 "{\"name\":\"$tool_name\",\"arguments\":$args}")

  # Check for error
  if echo "$result" | grep -q '"isError":true'; then
    echo "[!] Tool returned an error:" >&2
    echo "$result" | python3 -m json.tool 2>/dev/null || echo "$result"
    return 1
  fi

  # Check if result indicates a saved file (download tools return "Saved to: <path>")
  if echo "$result" | grep -q '"Saved to:'; then
    local saved_path
    saved_path=$(echo "$result" | grep -o 'Saved to: [^"]*' | sed 's/Saved to: //')
    if [ -n "$saved_path" ] && [ -f "$saved_path" ]; then
      local fsize
      fsize=$(wc -c < "$saved_path" | tr -d ' ')
      echo "[+] Downloaded: $saved_path ($fsize bytes)"
      echo "$result" | python3 -m json.tool 2>/dev/null || echo "$result"
      return 0
    fi
  fi

  # Pretty print JSON response
  echo "$result" | python3 -m json.tool 2>/dev/null || echo "$result"
}

# --- Main ---

case "${1:-help}" in
  help|--help|-h)
    usage
    ;;
  list-tools|list)
    init_session
    list_tools
    ;;
  call)
    shift
    init_session
    call_tool "$@"
    ;;
  *)
    init_session
    call_tool "$@"
    ;;
esac
