// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetApplicationsShow tool
const GetApplicationsShowInputSchema = "{\n  \"properties\": {\n    \"application\": {\n      \"description\": \"Application key\",\n      \"type\": \"string\"\n    },\n    \"branch\": {\n      \"description\": \"Branch name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"application\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetApplicationsShow tool (Status: 200, Content-Type: application/json)
const GetApplicationsShowResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetApplicationsShowMCPTool creates the MCP Tool instance for GetApplicationsShow
func NewGetApplicationsShowMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetApplicationsShow",
		"Returns an application and its associated projects. - Returns an application and its associated projects. Requires the 'Browse' permission on the application and on its child projects.",
		[]byte(GetApplicationsShowInputSchema),
	)
}

// GetApplicationsShowHandler is the handler function for the GetApplicationsShow tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetApplicationsShowHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/applications/show", args, []string{}, contentType, "GetApplicationsShow")
}
