// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAlmIntegrationsSearchBitbucketcloudRepos tool
const GetAlmIntegrationsSearchBitbucketcloudReposInputSchema = "{\n  \"properties\": {\n    \"almSetting\": {\n      \"description\": \"DevOps Platform setting key\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"p\": {\n      \"default\": \"1\",\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"description\": \"Page size. Must be greater than 0 and less or equal than 100\",\n      \"maximum\": 100,\n      \"type\": \"integer\"\n    },\n    \"repositoryName\": {\n      \"description\": \"Repository name filter\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"almSetting\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetAlmIntegrationsSearchBitbucketcloudRepos tool (Status: 200, Content-Type: application/json)
const GetAlmIntegrationsSearchBitbucketcloudReposResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetAlmIntegrationsSearchBitbucketcloudReposMCPTool creates the MCP Tool instance for GetAlmIntegrationsSearchBitbucketcloudRepos
func NewGetAlmIntegrationsSearchBitbucketcloudReposMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAlmIntegrationsSearchBitbucketcloudRepos",
		"Search the Bitbucket Cloud repositories. - Search the Bitbucket Cloud repositories Requires the 'Create Projects' permission",
		[]byte(GetAlmIntegrationsSearchBitbucketcloudReposInputSchema),
	)
}

// GetAlmIntegrationsSearchBitbucketcloudReposHandler is the handler function for the GetAlmIntegrationsSearchBitbucketcloudRepos tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAlmIntegrationsSearchBitbucketcloudReposHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/alm_integrations/search_bitbucketcloud_repos", args, []string{}, contentType, "GetAlmIntegrationsSearchBitbucketcloudRepos")
}
