// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAlmSettingsValidateBinding tool
const GetAlmSettingsValidateBindingInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Unique key of project\",\n      \"maxLength\": 400,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetAlmSettingsValidateBinding tool (Status: 200, Content-Type: application/json)
const GetAlmSettingsValidateBindingResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetAlmSettingsValidateBindingMCPTool creates the MCP Tool instance for GetAlmSettingsValidateBinding
func NewGetAlmSettingsValidateBindingMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAlmSettingsValidateBinding",
		"Validate a project binding setting by checking connectivity and permissions. - Validate a project binding setting by checking connectivity and permissions Requires project 'Browse' permission",
		[]byte(GetAlmSettingsValidateBindingInputSchema),
	)
}

// GetAlmSettingsValidateBindingHandler is the handler function for the GetAlmSettingsValidateBinding tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAlmSettingsValidateBindingHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/alm_settings/validate_binding", args, []string{}, contentType, "GetAlmSettingsValidateBinding")
}
