// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAlmSettingsList tool
const GetAlmSettingsListInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetAlmSettingsList tool (Status: 200, Content-Type: application/json)
const GetAlmSettingsListResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetAlmSettingsListMCPTool creates the MCP Tool instance for GetAlmSettingsList
func NewGetAlmSettingsListMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAlmSettingsList",
		"List DevOps Platform setting available for a given project, sorted by DevOps Platform key. - List DevOps Platform setting available for a given project, sorted by DevOps Platform key Requires the 'Administer project' permission if the 'project' parameter is provided, requires the 'Create Projects' permission otherwise.",
		[]byte(GetAlmSettingsListInputSchema),
	)
}

// GetAlmSettingsListHandler is the handler function for the GetAlmSettingsList tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAlmSettingsListHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/alm_settings/list", args, []string{}, contentType, "GetAlmSettingsList")
}
