// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetBatchProject tool
const GetBatchProjectInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"profile\": {\n      \"description\": \"Profile name\",\n      \"type\": \"string\"\n    },\n    \"pullRequest\": {\n      \"description\": \"Pull request id\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetBatchProject tool (Status: 200, Content-Type: application/json)
const GetBatchProjectResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetBatchProjectMCPTool creates the MCP Tool instance for GetBatchProject
func NewGetBatchProjectMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetBatchProject",
		"Return project repository. - Return project repository",
		[]byte(GetBatchProjectInputSchema),
	)
}

// GetBatchProjectHandler is the handler function for the GetBatchProject tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetBatchProjectHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/batch/project", args, []string{}, contentType, "GetBatchProject")
}
