// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetCeTask tool
const GetCeTaskInputSchema = "{\n  \"properties\": {\n    \"additionalFields\": {\n      \"description\": \"Comma-separated list of the optional fields to be returned in response.\",\n      \"enum\": [\n        \"stacktrace\",\n        \"scannerContext\",\n        \"warnings\"\n      ],\n      \"type\": \"string\"\n    },\n    \"id\": {\n      \"description\": \"Id of task\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetCeTask tool (Status: 200, Content-Type: application/json)
const GetCeTaskResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetCeTaskMCPTool creates the MCP Tool instance for GetCeTask
func NewGetCeTaskMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetCeTask",
		"Give Compute Engine task details such as type, status, duration and associated component. - Give Compute Engine task details such as type, status, duration and associated component. Requires one of the following permissions: - 'Administer' at global or project level - 'Execute Analysis' at global or project levelSince 6.1, field \"logs\" is deprecated and its value is always false.",
		[]byte(GetCeTaskInputSchema),
	)
}

// GetCeTaskHandler is the handler function for the GetCeTask tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetCeTaskHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/ce/task", args, []string{}, contentType, "GetCeTask")
}
