// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetCeComponent tool
const GetCeComponentInputSchema = "{\n  \"properties\": {\n    \"component\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"component\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetCeComponent tool (Status: 200, Content-Type: application/json)
const GetCeComponentResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetCeComponentMCPTool creates the MCP Tool instance for GetCeComponent
func NewGetCeComponentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetCeComponent",
		"Get the pending tasks, in-progress tasks and the last executed task of a given component (usually a project). - Get the pending tasks, in-progress tasks and the last executed task of a given component (usually a project). Requires the following permission: 'Browse' on the specified component.",
		[]byte(GetCeComponentInputSchema),
	)
}

// GetCeComponentHandler is the handler function for the GetCeComponent tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetCeComponentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/ce/component", args, []string{}, contentType, "GetCeComponent")
}
