// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetComponentsShow tool
const GetComponentsShowInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key. Not available in the community edition.\",\n      \"type\": \"string\"\n    },\n    \"component\": {\n      \"description\": \"Component key\",\n      \"type\": \"string\"\n    },\n    \"pullRequest\": {\n      \"description\": \"Pull request id. Not available in the community edition.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"component\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetComponentsShow tool (Status: 200, Content-Type: application/json)
const GetComponentsShowResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetComponentsShowMCPTool creates the MCP Tool instance for GetComponentsShow
func NewGetComponentsShowMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetComponentsShow",
		"Returns a component (file, directory, project, portfolio…) and its ancestors. - Returns a component (file, directory, project, portfolio…) and its ancestors. The ancestors are ordered from the parent to the root project. Requires the following permission: 'Browse' on the project of the specified component.",
		[]byte(GetComponentsShowInputSchema),
	)
}

// GetComponentsShowHandler is the handler function for the GetComponentsShow tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetComponentsShowHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/components/show", args, []string{}, contentType, "GetComponentsShow")
}
