// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetEditionsShowLicense tool
const GetEditionsShowLicenseInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetEditionsShowLicense tool (Status: 200, Content-Type: application/json)
const GetEditionsShowLicenseResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetEditionsShowLicenseMCPTool creates the MCP Tool instance for GetEditionsShowLicense
func NewGetEditionsShowLicenseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetEditionsShowLicense",
		"Show information about currently installed license. - Show information about currently installed license. Requires 'Administer System' permission.",
		[]byte(GetEditionsShowLicenseInputSchema),
	)
}

// GetEditionsShowLicenseHandler is the handler function for the GetEditionsShowLicense tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetEditionsShowLicenseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/editions/show_license", args, []string{}, contentType, "GetEditionsShowLicense")
}
