// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetEditionsIsValidLicense tool
const GetEditionsIsValidLicenseInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetEditionsIsValidLicense tool (Status: 200, Content-Type: application/json)
const GetEditionsIsValidLicenseResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetEditionsIsValidLicenseMCPTool creates the MCP Tool instance for GetEditionsIsValidLicense
func NewGetEditionsIsValidLicenseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetEditionsIsValidLicense",
		"Return the validity of the license. - Return the validity of the license.\nError message can be thrown under the following circumstances:\n\n - \"404 License not found\" will be thrown if no license has been set. \n - \"404 Unknown URL : /api/editions/is_valid_license\" will be thrown if the instance is under community edition\n - \"500 An error has occurred. Please contact your administrator\" can be thrown when the license is corrupted. Additional details can be found in the logs.",
		[]byte(GetEditionsIsValidLicenseInputSchema),
	)
}

// GetEditionsIsValidLicenseHandler is the handler function for the GetEditionsIsValidLicense tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetEditionsIsValidLicenseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/editions/is_valid_license", args, []string{}, contentType, "GetEditionsIsValidLicense")
}
