// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetGovernanceReportsStatus tool
const GetGovernanceReportsStatusInputSchema = "{\n  \"properties\": {\n    \"branchKey\": {\n      \"description\": \"The branch key\",\n      \"type\": \"string\"\n    },\n    \"componentId\": {\n      \"description\": \"The portfolio, sub-portfolio, project or application id\",\n      \"type\": \"string\"\n    },\n    \"componentKey\": {\n      \"description\": \"The portfolio, sub-portfolio, project or application key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetGovernanceReportsStatus tool (Status: 200, Content-Type: application/json)
const GetGovernanceReportsStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetGovernanceReportsStatusMCPTool creates the MCP Tool instance for GetGovernanceReportsStatus
func NewGetGovernanceReportsStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetGovernanceReportsStatus",
		"Return PDF report metadata (action rights, report availability etc.). - Return PDF report metadata (action rights, report availability etc.). Requires the 'Browse' permission on the portfolio, sub-portfolio, project or application.",
		[]byte(GetGovernanceReportsStatusInputSchema),
	)
}

// GetGovernanceReportsStatusHandler is the handler function for the GetGovernanceReportsStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetGovernanceReportsStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/governance_reports/status", args, []string{}, contentType, "GetGovernanceReportsStatus")
}
