// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetIssuesChangelog tool
const GetIssuesChangelogInputSchema = "{\n  \"properties\": {\n    \"issue\": {\n      \"description\": \"Issue key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"issue\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetIssuesChangelog tool (Status: 200, Content-Type: application/json)
const GetIssuesChangelogResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetIssuesChangelogMCPTool creates the MCP Tool instance for GetIssuesChangelog
func NewGetIssuesChangelogMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetIssuesChangelog",
		"Display changelog of an issue. - Display changelog of an issue. Requires the 'Browse' permission on the project of the specified issue.",
		[]byte(GetIssuesChangelogInputSchema),
	)
}

// GetIssuesChangelogHandler is the handler function for the GetIssuesChangelog tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetIssuesChangelogHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/issues/changelog", args, []string{}, contentType, "GetIssuesChangelog")
}
