// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetIssuesTags tool
const GetIssuesTagsInputSchema = "{\n  \"properties\": {\n    \"all\": {\n      \"description\": \"Indicator to search for all tags or only for tags in the main branch of a project\",\n      \"enum\": [\n        \"true\",\n        \"false\"\n      ],\n      \"type\": \"string\"\n    },\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"description\": \"Page size. Must be greater than 0 and less or equal than 500\",\n      \"maximum\": 500,\n      \"type\": \"integer\"\n    },\n    \"q\": {\n      \"description\": \"Limit search to tags that contain the supplied string.\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetIssuesTags tool (Status: 200, Content-Type: application/json)
const GetIssuesTagsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetIssuesTagsMCPTool creates the MCP Tool instance for GetIssuesTags
func NewGetIssuesTagsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetIssuesTags",
		"List tags matching a given query. - List tags matching a given query",
		[]byte(GetIssuesTagsInputSchema),
	)
}

// GetIssuesTagsHandler is the handler function for the GetIssuesTags tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetIssuesTagsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/issues/tags", args, []string{}, contentType, "GetIssuesTags")
}
