// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetIssuesList tool
const GetIssuesListInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key. Not available in the community edition.\",\n      \"type\": \"string\"\n    },\n    \"component\": {\n      \"description\": \"Component key\",\n      \"type\": \"string\"\n    },\n    \"inNewCodePeriod\": {\n      \"description\": \"Filter issues created in the new code period of the project\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"p\": {\n      \"default\": \"1\",\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"description\": \"Page size. Must be greater than 0 and less or equal than 500\",\n      \"maximum\": 500,\n      \"type\": \"integer\"\n    },\n    \"pullRequest\": {\n      \"description\": \"Filter issues that belong to the specified pull request. Not available in the community edition.\",\n      \"type\": \"string\"\n    },\n    \"resolved\": {\n      \"description\": \"Filter issues that are resolved or not, if not provided all issues will be returned\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"types\": {\n      \"description\": \"Comma-separated list of issue types\",\n      \"enum\": [\n        \"BUG\",\n        \"VULNERABILITY\",\n        \"CODE_SMELL\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetIssuesList tool (Status: 200, Content-Type: application/json)
const GetIssuesListResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetIssuesListMCPTool creates the MCP Tool instance for GetIssuesList
func NewGetIssuesListMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetIssuesList",
		"List issues. - List issues. This endpoint is used in degraded mode, when issue indexing is running. Either 'project' or 'component' parameter is required. Total number of issues will be always equal to a page size, as this counting all issues is not supported. Requires the 'Browse' permission on the specified project.",
		[]byte(GetIssuesListInputSchema),
	)
}

// GetIssuesListHandler is the handler function for the GetIssuesList tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetIssuesListHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/issues/list", args, []string{}, contentType, "GetIssuesList")
}
