// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetIssuesPullTaint tool
const GetIssuesPullTaintInputSchema = "{\n  \"properties\": {\n    \"branchName\": {\n      \"description\": \"Branch name for which taint vulnerabilities are fetched.\",\n      \"type\": \"string\"\n    },\n    \"changedSince\": {\n      \"description\": \"Timestamp. If present only taint vulnerabilities modified after given timestamp are returned (both open and closed). If not present all non-closed taint vulnerabilities are returned.\",\n      \"type\": \"string\"\n    },\n    \"languages\": {\n      \"description\": \"Comma separated list of languages. If not present all taint vulnerabilities regardless of their language are returned.\",\n      \"type\": \"string\"\n    },\n    \"projectKey\": {\n      \"description\": \"Project key for which taint vulnerabilities are fetched.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"branchName\",\n    \"projectKey\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetIssuesPullTaint tool (Status: 200, Content-Type: application/json)
const GetIssuesPullTaintResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetIssuesPullTaintMCPTool creates the MCP Tool instance for GetIssuesPullTaint
func NewGetIssuesPullTaintMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetIssuesPullTaint",
		"This endpoint fetches and returns all (unless filtered by optional params) the taint vulnerabilities for a given branch. - This endpoint fetches and returns all (unless filtered by optional params) the taint vulnerabilities for a given branch. The taint vulnerabilities returned are not paginated, so the response size can be big. Requires project 'Browse' permission.",
		[]byte(GetIssuesPullTaintInputSchema),
	)
}

// GetIssuesPullTaintHandler is the handler function for the GetIssuesPullTaint tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetIssuesPullTaintHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/issues/pull_taint", args, []string{}, contentType, "GetIssuesPullTaint")
}
