// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetMonitoringMetrics tool
const GetMonitoringMetricsInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetMonitoringMetrics tool (Status: 200, Content-Type: application/json)
const GetMonitoringMetricsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetMonitoringMetricsMCPTool creates the MCP Tool instance for GetMonitoringMetrics
func NewGetMonitoringMetricsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetMonitoringMetrics",
		"Return monitoring metrics in Prometheus format. - Return monitoring metrics in Prometheus format. \nSupport content type 'text/plain' (default) and 'application/openmetrics-text'.\nThis endpoint can be accessed using a Bearer token, which needs to be defined in sonar.properties with the 'sonar.web.systemPasscode' key.",
		[]byte(GetMonitoringMetricsInputSchema),
	)
}

// GetMonitoringMetricsHandler is the handler function for the GetMonitoringMetrics tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetMonitoringMetricsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/monitoring/metrics", args, []string{}, contentType, "GetMonitoringMetrics")
}
