// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetMeasuresSearch tool
const GetMeasuresSearchInputSchema = "{\n  \"properties\": {\n    \"metricKeys\": {\n      \"description\": \"Comma-separated list of metric keys\",\n      \"type\": \"string\"\n    },\n    \"projectKeys\": {\n      \"description\": \"Comma-separated list of project, view or sub-view keys\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"metricKeys\",\n    \"projectKeys\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetMeasuresSearch tool (Status: 200, Content-Type: application/json)
const GetMeasuresSearchResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetMeasuresSearchMCPTool creates the MCP Tool instance for GetMeasuresSearch
func NewGetMeasuresSearchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetMeasuresSearch",
		"Search for project measures ordered by project names. - Search for project measures ordered by project names. At most 100 projects can be provided. Returns the projects with the 'Browse' permission.",
		[]byte(GetMeasuresSearchInputSchema),
	)
}

// GetMeasuresSearchHandler is the handler function for the GetMeasuresSearch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetMeasuresSearchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/measures/search", args, []string{}, contentType, "GetMeasuresSearch")
}
