// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetMeasuresComponent tool
const GetMeasuresComponentInputSchema = "{\n  \"properties\": {\n    \"additionalFields\": {\n      \"description\": \"Comma-separated list of additional fields that can be returned in the response.\",\n      \"enum\": [\n        \"metrics\",\n        \"period\"\n      ],\n      \"type\": \"string\"\n    },\n    \"branch\": {\n      \"description\": \"Branch key. Not available in the community edition.\",\n      \"type\": \"string\"\n    },\n    \"component\": {\n      \"description\": \"Component key\",\n      \"type\": \"string\"\n    },\n    \"metricKeys\": {\n      \"description\": \"Comma-separated list of metric keys\",\n      \"type\": \"string\"\n    },\n    \"pullRequest\": {\n      \"description\": \"Pull request id. Not available in the community edition.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"component\",\n    \"metricKeys\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetMeasuresComponent tool (Status: 200, Content-Type: application/json)
const GetMeasuresComponentResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetMeasuresComponentMCPTool creates the MCP Tool instance for GetMeasuresComponent
func NewGetMeasuresComponentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetMeasuresComponent",
		"Return component with specified measures. - Return component with specified measures. Requires one of the following permissions: - 'Browse' on the project of the specified component - 'Execute Analysis' on the project of the specified component",
		[]byte(GetMeasuresComponentInputSchema),
	)
}

// GetMeasuresComponentHandler is the handler function for the GetMeasuresComponent tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetMeasuresComponentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/measures/component", args, []string{}, contentType, "GetMeasuresComponent")
}
