// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetMetricsTypes tool
const GetMetricsTypesInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetMetricsTypes tool (Status: 200, Content-Type: application/json)
const GetMetricsTypesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetMetricsTypesMCPTool creates the MCP Tool instance for GetMetricsTypes
func NewGetMetricsTypesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetMetricsTypes",
		"List all available metric types. - List all available metric types.",
		[]byte(GetMetricsTypesInputSchema),
	)
}

// GetMetricsTypesHandler is the handler function for the GetMetricsTypes tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetMetricsTypesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/metrics/types", args, []string{}, contentType, "GetMetricsTypes")
}
