// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetNavigationComponent tool
const GetNavigationComponentInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"component\": {\n      \"description\": \"A component key.\",\n      \"type\": \"string\"\n    },\n    \"pullRequest\": {\n      \"description\": \"Pull request id\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetNavigationComponent tool (Status: 200, Content-Type: application/json)
const GetNavigationComponentResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetNavigationComponentMCPTool creates the MCP Tool instance for GetNavigationComponent
func NewGetNavigationComponentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetNavigationComponent",
		"Get information concerning component navigation for the current user. - Get information concerning component navigation for the current user. Requires the 'Browse' permission on the component's project. For applications, it also requires 'Browse' permission on its child projects.",
		[]byte(GetNavigationComponentInputSchema),
	)
}

// GetNavigationComponentHandler is the handler function for the GetNavigationComponent tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetNavigationComponentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/navigation/component", args, []string{}, contentType, "GetNavigationComponent")
}
