// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetNewCodePeriodsList tool
const GetNewCodePeriodsListInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetNewCodePeriodsList tool (Status: 200, Content-Type: application/json)
const GetNewCodePeriodsListResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetNewCodePeriodsListMCPTool creates the MCP Tool instance for GetNewCodePeriodsList
func NewGetNewCodePeriodsListMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetNewCodePeriodsList",
		"Lists the new code definition for all branches in a project. - Lists the new code definition for all branches in a project. Requires the permission to browse the project",
		[]byte(GetNewCodePeriodsListInputSchema),
	)
}

// GetNewCodePeriodsListHandler is the handler function for the GetNewCodePeriodsList tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetNewCodePeriodsListHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/new_code_periods/list", args, []string{}, contentType, "GetNewCodePeriodsList")
}
