// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetPermissionsSearchTemplates tool
const GetPermissionsSearchTemplatesInputSchema = "{\n  \"properties\": {\n    \"p\": {\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"description\": \"Page size. Must be greater than or equal to 0 and less or equal than 500. If this and p param are not provided, pagination is disabled and all results are returned. If pageSize=0, no results are returned but the response will contain the total count of matching templates.\",\n      \"type\": \"string\"\n    },\n    \"q\": {\n      \"description\": \"Limit search to permission template names that contain the supplied string.\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetPermissionsSearchTemplates tool (Status: 200, Content-Type: application/json)
const GetPermissionsSearchTemplatesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetPermissionsSearchTemplatesMCPTool creates the MCP Tool instance for GetPermissionsSearchTemplates
func NewGetPermissionsSearchTemplatesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetPermissionsSearchTemplates",
		"List permission templates. - List permission templates. Requires the following permission: 'Administer System'.",
		[]byte(GetPermissionsSearchTemplatesInputSchema),
	)
}

// GetPermissionsSearchTemplatesHandler is the handler function for the GetPermissionsSearchTemplates tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetPermissionsSearchTemplatesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/permissions/search_templates", args, []string{}, contentType, "GetPermissionsSearchTemplates")
}
