// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectDumpStatus tool
const GetProjectDumpStatusInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Project id\",\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectDumpStatus tool (Status: 200, Content-Type: application/json)
const GetProjectDumpStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectDumpStatusMCPTool creates the MCP Tool instance for GetProjectDumpStatus
func NewGetProjectDumpStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectDumpStatus",
		"Provide the import and export status of a project. - Provide the import and export status of a project. Permission 'Administer' is required. The project id or project key must be provided.",
		[]byte(GetProjectDumpStatusInputSchema),
	)
}

// GetProjectDumpStatusHandler is the handler function for the GetProjectDumpStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectDumpStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/project_dump/status", args, []string{}, contentType, "GetProjectDumpStatus")
}
