// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectBranchesList tool
const GetProjectBranchesListInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectBranchesList tool (Status: 200, Content-Type: application/json)
const GetProjectBranchesListResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectBranchesListMCPTool creates the MCP Tool instance for GetProjectBranchesList
func NewGetProjectBranchesListMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectBranchesList",
		"List the branches of a project or application. - List the branches of a project or application. Requires 'Browse' or 'Execute analysis' rights on the specified project or application.",
		[]byte(GetProjectBranchesListInputSchema),
	)
}

// GetProjectBranchesListHandler is the handler function for the GetProjectBranchesList tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectBranchesListHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/project_branches/list", args, []string{}, contentType, "GetProjectBranchesList")
}
