// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectsGetDetectedAiCode tool
const GetProjectsGetDetectedAiCodeInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectsGetDetectedAiCode tool (Status: 200, Content-Type: application/json)
const GetProjectsGetDetectedAiCodeResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectsGetDetectedAiCodeMCPTool creates the MCP Tool instance for GetProjectsGetDetectedAiCode
func NewGetProjectsGetDetectedAiCodeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectsGetDetectedAiCode",
		"Get detected AI code. - Get detected AI code",
		[]byte(GetProjectsGetDetectedAiCodeInputSchema),
	)
}

// GetProjectsGetDetectedAiCodeHandler is the handler function for the GetProjectsGetDetectedAiCode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectsGetDetectedAiCodeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/projects/get_detected_ai_code", args, []string{}, contentType, "GetProjectsGetDetectedAiCode")
}
