// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectsSearchMyScannableProjects tool
const GetProjectsSearchMyScannableProjectsInputSchema = "{\n  \"properties\": {\n    \"q\": {\n      \"description\": \"Limit search to project names that contain the supplied string.\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectsSearchMyScannableProjects tool (Status: 200, Content-Type: application/json)
const GetProjectsSearchMyScannableProjectsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectsSearchMyScannableProjectsMCPTool creates the MCP Tool instance for GetProjectsSearchMyScannableProjects
func NewGetProjectsSearchMyScannableProjectsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectsSearchMyScannableProjects",
		"List projects that a user can scan. - List projects that a user can scan.",
		[]byte(GetProjectsSearchMyScannableProjectsInputSchema),
	)
}

// GetProjectsSearchMyScannableProjectsHandler is the handler function for the GetProjectsSearchMyScannableProjects tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectsSearchMyScannableProjectsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/projects/search_my_scannable_projects", args, []string{}, contentType, "GetProjectsSearchMyScannableProjects")
}
