// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetPushSonarlintEvents tool
const GetPushSonarlintEventsInputSchema = "{\n  \"properties\": {\n    \"languages\": {\n      \"description\": \"Comma-separated list of languages for which events will be delivered\",\n      \"type\": \"string\"\n    },\n    \"projectKeys\": {\n      \"description\": \"Comma-separated list of projects keys for which events will be delivered\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"languages\",\n    \"projectKeys\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetPushSonarlintEvents tool (Status: 200, Content-Type: application/json)
const GetPushSonarlintEventsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Structure (Type: object):\n"

// NewGetPushSonarlintEventsMCPTool creates the MCP Tool instance for GetPushSonarlintEvents
func NewGetPushSonarlintEventsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetPushSonarlintEvents",
		"Endpoint for listening to server side events. - Endpoint for listening to server side events. Currently it notifies listener about change to activation of a rule",
		[]byte(GetPushSonarlintEventsInputSchema),
	)
}

// GetPushSonarlintEventsHandler is the handler function for the GetPushSonarlintEvents tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetPushSonarlintEventsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/push/sonarlint_events", args, []string{}, contentType, "GetPushSonarlintEvents")
}
