// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectBadgesToken tool
const GetProjectBadgesTokenInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project or application key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectBadgesToken tool (Status: 200, Content-Type: application/json)
const GetProjectBadgesTokenResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectBadgesTokenMCPTool creates the MCP Tool instance for GetProjectBadgesToken
func NewGetProjectBadgesTokenMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectBadgesToken",
		"Retrieve a token to use for project or application badge access for private projects or applications. - Retrieve a token to use for project or application badge access for private projects or applications. This token can be used to authenticate with api/project_badges/quality_gate and api/project_badges/measure endpoints. Requires 'Browse' permission on the specified project or application. If the 'sonar.forceAuthentication' setting is enabled, then a token is required for public projects as well.",
		[]byte(GetProjectBadgesTokenInputSchema),
	)
}

// GetProjectBadgesTokenHandler is the handler function for the GetProjectBadgesToken tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectBadgesTokenHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/project_badges/token", args, []string{}, contentType, "GetProjectBadgesToken")
}
