// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectLinksSearch tool
const GetProjectLinksSearchInputSchema = "{\n  \"properties\": {\n    \"projectId\": {\n      \"description\": \"Project Id\",\n      \"type\": \"string\"\n    },\n    \"projectKey\": {\n      \"description\": \"Project Key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectLinksSearch tool (Status: 200, Content-Type: application/json)
const GetProjectLinksSearchResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectLinksSearchMCPTool creates the MCP Tool instance for GetProjectLinksSearch
func NewGetProjectLinksSearchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectLinksSearch",
		"List links of a project. - List links of a project. The 'projectId' or 'projectKey' must be provided. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the specified project - 'Browse' on the specified project",
		[]byte(GetProjectLinksSearchInputSchema),
	)
}

// GetProjectLinksSearchHandler is the handler function for the GetProjectLinksSearch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectLinksSearchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/project_links/search", args, []string{}, contentType, "GetProjectLinksSearch")
}
