// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetPluginsDownload tool
const GetPluginsDownloadInputSchema = "{\n  \"properties\": {\n    \"plugin\": {\n      \"description\": \"The key identifying the plugin to download\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"plugin\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetPluginsDownload tool (Status: 200, Content-Type: application/json)
const GetPluginsDownloadResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Structure (Type: object):\n"

// NewGetPluginsDownloadMCPTool creates the MCP Tool instance for GetPluginsDownload
func NewGetPluginsDownloadMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetPluginsDownload",
		"Download plugin JAR, for usage by scanner engine. - Download plugin JAR, for usage by scanner engine",
		[]byte(GetPluginsDownloadInputSchema),
	)
}

// GetPluginsDownloadHandler is the handler function for the GetPluginsDownload tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetPluginsDownloadHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/plugins/download", args, []string{}, contentType, "GetPluginsDownload")
}
