// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetProjectBadgesMeasure tool
const GetProjectBadgesMeasureInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"metric\": {\n      \"description\": \"Metric key\",\n      \"enum\": [\n        \"coverage\",\n        \"duplicated_lines_density\",\n        \"ncloc\",\n        \"alert_status\",\n        \"security_hotspots\",\n        \"bugs\",\n        \"code_smells\",\n        \"vulnerabilities\",\n        \"sqale_rating\",\n        \"reliability_rating\",\n        \"security_rating\",\n        \"sqale_index\",\n        \"software_quality_reliability_issues\",\n        \"software_quality_maintainability_issues\",\n        \"software_quality_security_issues\",\n        \"software_quality_maintainability_rating\",\n        \"software_quality_reliability_rating\",\n        \"software_quality_security_rating\",\n        \"software_quality_maintainability_remediation_effort\"\n      ],\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project or application key\",\n      \"type\": \"string\"\n    },\n    \"token\": {\n      \"description\": \"Project badge token. Required for private projects or if the 'sonar.forceAuthentication' setting is enabled.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"metric\",\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetProjectBadgesMeasure tool (Status: 200, Content-Type: application/json)
const GetProjectBadgesMeasureResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetProjectBadgesMeasureMCPTool creates the MCP Tool instance for GetProjectBadgesMeasure
func NewGetProjectBadgesMeasureMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetProjectBadgesMeasure",
		"Generate badge for project's measure as an SVG. - Generate badge for project's measure as an SVG. Requires 'Browse' permission on the specified project.",
		[]byte(GetProjectBadgesMeasureInputSchema),
	)
}

// GetProjectBadgesMeasureHandler is the handler function for the GetProjectBadgesMeasure tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetProjectBadgesMeasureHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/project_badges/measure", args, []string{}, contentType, "GetProjectBadgesMeasure")
}
