// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetQualitygatesShow tool
const GetQualitygatesShowInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"Name of the quality gate. Either id or name must be set\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetQualitygatesShow tool (Status: 200, Content-Type: application/json)
const GetQualitygatesShowResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetQualitygatesShowMCPTool creates the MCP Tool instance for GetQualitygatesShow
func NewGetQualitygatesShowMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetQualitygatesShow",
		"Display the details of a quality gate. - Display the details of a quality gate",
		[]byte(GetQualitygatesShowInputSchema),
	)
}

// GetQualitygatesShowHandler is the handler function for the GetQualitygatesShow tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetQualitygatesShowHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/qualitygates/show", args, []string{}, contentType, "GetQualitygatesShow")
}
