// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetQualityprofilesSearch tool
const GetQualityprofilesSearchInputSchema = "{\n  \"properties\": {\n    \"defaults\": {\n      \"description\": \"If set to true, return only the quality profiles marked as default for each language\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"language\": {\n      \"description\": \"Language key. If provided, only profiles for the given language are returned.\",\n      \"enum\": [\n        \"abap\",\n        \"ansible\",\n        \"apex\",\n        \"azurepipelines\",\n        \"azureresourcemanager\",\n        \"c\",\n        \"cloudformation\",\n        \"cobol\",\n        \"cpp\",\n        \"cs\",\n        \"css\",\n        \"dart\",\n        \"docker\",\n        \"flex\",\n        \"githubactions\",\n        \"go\",\n        \"gosu\",\n        \"groovy\",\n        \"ipynb\",\n        \"java\",\n        \"jcl\",\n        \"js\",\n        \"json\",\n        \"jsp\",\n        \"kotlin\",\n        \"kubernetes\",\n        \"objc\",\n        \"php\",\n        \"pli\",\n        \"plsql\",\n        \"powershell\",\n        \"py\",\n        \"rpg\",\n        \"ruby\",\n        \"rust\",\n        \"scala\",\n        \"secrets\",\n        \"shell\",\n        \"sql\",\n        \"swift\",\n        \"terraform\",\n        \"text\",\n        \"ts\",\n        \"tsql\",\n        \"vb\",\n        \"vbnet\",\n        \"web\",\n        \"xml\",\n        \"yaml\"\n      ],\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"qualityProfile\": {\n      \"description\": \"Quality profile name\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetQualityprofilesSearch tool (Status: 200, Content-Type: application/json)
const GetQualityprofilesSearchResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetQualityprofilesSearchMCPTool creates the MCP Tool instance for GetQualityprofilesSearch
func NewGetQualityprofilesSearchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetQualityprofilesSearch",
		"Search quality profiles. - Search quality profiles",
		[]byte(GetQualityprofilesSearchInputSchema),
	)
}

// GetQualityprofilesSearchHandler is the handler function for the GetQualityprofilesSearch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetQualityprofilesSearchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/qualityprofiles/search", args, []string{}, contentType, "GetQualityprofilesSearch")
}
