// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetQualitygatesApplicationStatus tool
const GetQualitygatesApplicationStatusInputSchema = "{\n  \"properties\": {\n    \"application\": {\n      \"description\": \"Application key\",\n      \"type\": \"string\"\n    },\n    \"branch\": {\n      \"description\": \"Branch name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"application\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetQualitygatesApplicationStatus tool (Status: 200, Content-Type: application/json)
const GetQualitygatesApplicationStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetQualitygatesApplicationStatusMCPTool creates the MCP Tool instance for GetQualitygatesApplicationStatus
func NewGetQualitygatesApplicationStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetQualitygatesApplicationStatus",
		"Get the quality gate status of an application. - Get the quality gate status of an application. Requires the following permission: 'Browse' on the specified application and on its child projects.",
		[]byte(GetQualitygatesApplicationStatusInputSchema),
	)
}

// GetQualitygatesApplicationStatusHandler is the handler function for the GetQualitygatesApplicationStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetQualitygatesApplicationStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/qualitygates/application_status", args, []string{}, contentType, "GetQualitygatesApplicationStatus")
}
