// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetRulesShow tool
const GetRulesShowInputSchema = "{\n  \"properties\": {\n    \"actives\": {\n      \"description\": \"Show rule's activations for all profiles (\\\"active rules\\\")\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Rule key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetRulesShow tool (Status: 200, Content-Type: application/json)
const GetRulesShowResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetRulesShowMCPTool creates the MCP Tool instance for GetRulesShow
func NewGetRulesShowMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetRulesShow",
		"Get detailed information about a rule. - Get detailed information about a rule",
		[]byte(GetRulesShowInputSchema),
	)
}

// GetRulesShowHandler is the handler function for the GetRulesShow tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetRulesShowHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/rules/show", args, []string{}, contentType, "GetRulesShow")
}
