// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetRegulatoryReportsDownload tool
const GetRegulatoryReportsDownloadInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetRegulatoryReportsDownload tool (Status: 200, Content-Type: application/json)
const GetRegulatoryReportsDownloadResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Structure (Type: object):\n"

// NewGetRegulatoryReportsDownloadMCPTool creates the MCP Tool instance for GetRegulatoryReportsDownload
func NewGetRegulatoryReportsDownloadMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetRegulatoryReportsDownload",
		"Download a zip file containing the regulatory report and related files. - Download a zip file containing the regulatory report and related files. Requires the 'Browse' permission on the Project.",
		[]byte(GetRegulatoryReportsDownloadInputSchema),
	)
}

// GetRegulatoryReportsDownloadHandler is the handler function for the GetRegulatoryReportsDownload tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetRegulatoryReportsDownloadHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/regulatory_reports/download", args, []string{}, contentType, "GetRegulatoryReportsDownload")
}
