// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSystemStatus tool
const GetSystemStatusInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetSystemStatus tool (Status: 200, Content-Type: application/json)
const GetSystemStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetSystemStatusMCPTool creates the MCP Tool instance for GetSystemStatus
func NewGetSystemStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSystemStatus",
		"Get state information about SonarQube. - Get state information about SonarQube. status: the running status - STARTING: SonarQube Web Server is up and serving some Web Services (eg. api/system/status) but initialization is still ongoing - UP: SonarQube instance is up and running - DOWN: SonarQube instance is up but not running because migration has failed (refer to WS /api/system/migrate_db for details) or some other reason (check logs). - RESTARTING: SonarQube instance is still up but a restart has been requested (refer to WS /api/system/restart for details). - DB_MIGRATION_NEEDED: database migration is required. DB migration can be started using WS /api/system/migrate_db. - DB_MIGRATION_RUNNING: DB migration is running (refer to WS /api/system/migrate_db for details)",
		[]byte(GetSystemStatusInputSchema),
	)
}

// GetSystemStatusHandler is the handler function for the GetSystemStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSystemStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/system/status", args, []string{}, contentType, "GetSystemStatus")
}
