// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSettingsCheckSecretKey tool
const GetSettingsCheckSecretKeyInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetSettingsCheckSecretKey tool (Status: 200, Content-Type: application/json)
const GetSettingsCheckSecretKeyResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetSettingsCheckSecretKeyMCPTool creates the MCP Tool instance for GetSettingsCheckSecretKey
func NewGetSettingsCheckSecretKeyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSettingsCheckSecretKey",
		"Check if a secret key is available. - Check if a secret key is available. Requires the 'Administer System' permission.",
		[]byte(GetSettingsCheckSecretKeyInputSchema),
	)
}

// GetSettingsCheckSecretKeyHandler is the handler function for the GetSettingsCheckSecretKey tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSettingsCheckSecretKeyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/settings/check_secret_key", args, []string{}, contentType, "GetSettingsCheckSecretKey")
}
