// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSamlValidationInit tool
const GetSamlValidationInitInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetSamlValidationInit tool (Status: 200, Content-Type: application/json)
const GetSamlValidationInitResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Structure (Type: object):\n"

// NewGetSamlValidationInitMCPTool creates the MCP Tool instance for GetSamlValidationInit
func NewGetSamlValidationInitMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSamlValidationInit",
		"Initiate a SAML request to the identity Provider for configuration validation purpose. - Initiate a SAML request to the identity Provider for configuration validation purpose.",
		[]byte(GetSamlValidationInitInputSchema),
	)
}

// GetSamlValidationInitHandler is the handler function for the GetSamlValidationInit tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSamlValidationInitHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/saml/validation_init", args, []string{}, contentType, "GetSamlValidationInit")
}
