// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSystemDbMigrationStatus tool
const GetSystemDbMigrationStatusInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetSystemDbMigrationStatus tool (Status: 200, Content-Type: application/json)
const GetSystemDbMigrationStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetSystemDbMigrationStatusMCPTool creates the MCP Tool instance for GetSystemDbMigrationStatus
func NewGetSystemDbMigrationStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSystemDbMigrationStatus",
		"Display the database migration status of SonarQube. - Display the database migration status of SonarQube. State values are: - NO_MIGRATION: DB is up to date with current version of SonarQube. - NOT_SUPPORTED: Migration is not supported on embedded databases. - MIGRATION_RUNNING: DB migration is under go. - MIGRATION_SUCCEEDED: DB migration has run and has been successful. - MIGRATION_FAILED: DB migration has run and failed. SonarQube must be restarted in order to retry a DB migration (optionally after DB has been restored from backup). - MIGRATION_REQUIRED: DB migration is required.",
		[]byte(GetSystemDbMigrationStatusInputSchema),
	)
}

// GetSystemDbMigrationStatusHandler is the handler function for the GetSystemDbMigrationStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSystemDbMigrationStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/system/db_migration_status", args, []string{}, contentType, "GetSystemDbMigrationStatus")
}
