// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSourcesShow tool
const GetSourcesShowInputSchema = "{\n  \"properties\": {\n    \"from\": {\n      \"default\": \"1\",\n      \"description\": \"First line to return. Starts at 1\",\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"File key\",\n      \"type\": \"string\"\n    },\n    \"to\": {\n      \"description\": \"Last line to return (inclusive)\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetSourcesShow tool (Status: 200, Content-Type: application/json)
const GetSourcesShowResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetSourcesShowMCPTool creates the MCP Tool instance for GetSourcesShow
func NewGetSourcesShowMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSourcesShow",
		"Get source code. - Get source code. Requires See Source Code permission on file's project Each element of the result array is composed of: - Line number - Content of the line",
		[]byte(GetSourcesShowInputSchema),
	)
}

// GetSourcesShowHandler is the handler function for the GetSourcesShow tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSourcesShowHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/sources/show", args, []string{}, contentType, "GetSourcesShow")
}
