// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSettingsGenerateSecretKey tool
const GetSettingsGenerateSecretKeyInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetSettingsGenerateSecretKey tool (Status: 200, Content-Type: application/json)
const GetSettingsGenerateSecretKeyResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetSettingsGenerateSecretKeyMCPTool creates the MCP Tool instance for GetSettingsGenerateSecretKey
func NewGetSettingsGenerateSecretKeyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSettingsGenerateSecretKey",
		"Generate a secret key. - Generate a secret key. Requires the 'Administer System' permission",
		[]byte(GetSettingsGenerateSecretKeyInputSchema),
	)
}

// GetSettingsGenerateSecretKeyHandler is the handler function for the GetSettingsGenerateSecretKey tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSettingsGenerateSecretKeyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/settings/generate_secret_key", args, []string{}, contentType, "GetSettingsGenerateSecretKey")
}
