// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSupportInfo tool
const GetSupportInfoInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetSupportInfo tool (Status: 200, Content-Type: application/json)
const GetSupportInfoResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Structure (Type: object):\n"

// NewGetSupportInfoMCPTool creates the MCP Tool instance for GetSupportInfo
func NewGetSupportInfoMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSupportInfo",
		"Get information about the system and the currently installed license. - Get information about the system and the currently installed license. Requires 'Administer System' permission.",
		[]byte(GetSupportInfoInputSchema),
	)
}

// GetSupportInfoHandler is the handler function for the GetSupportInfo tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSupportInfoHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/support/info", args, []string{}, contentType, "GetSupportInfo")
}
