// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetScimManagementStatus tool
const GetScimManagementStatusInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetScimManagementStatus tool (Status: 200, Content-Type: application/json)
const GetScimManagementStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetScimManagementStatusMCPTool creates the MCP Tool instance for GetScimManagementStatus
func NewGetScimManagementStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetScimManagementStatus",
		"return SCIM activation status. - return SCIM activation status. Requires the 'Administer System' permission.",
		[]byte(GetScimManagementStatusInputSchema),
	)
}

// GetScimManagementStatusHandler is the handler function for the GetScimManagementStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetScimManagementStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/scim_management/status", args, []string{}, contentType, "GetScimManagementStatus")
}
