// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetUsersGroups tool
const GetUsersGroupsInputSchema = "{\n  \"properties\": {\n    \"login\": {\n      \"description\": \"A user login\",\n      \"type\": \"string\"\n    },\n    \"p\": {\n      \"default\": \"1\",\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"default\": \"25\",\n      \"description\": \"Page size. Must be greater than 0.\",\n      \"type\": \"string\"\n    },\n    \"q\": {\n      \"description\": \"Limit search to group names that contain the supplied string.\",\n      \"type\": \"string\"\n    },\n    \"selected\": {\n      \"description\": \"Depending on the value, show only selected items (selected=selected), deselected items (selected=deselected), or all items with their selection status (selected=all).\",\n      \"enum\": [\n        \"all\",\n        \"deselected\",\n        \"selected\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetUsersGroups tool (Status: 200, Content-Type: application/json)
const GetUsersGroupsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetUsersGroupsMCPTool creates the MCP Tool instance for GetUsersGroups
func NewGetUsersGroupsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetUsersGroups",
		"Lists the groups a user belongs to. - Lists the groups a user belongs to. Requires Administer System permission.",
		[]byte(GetUsersGroupsInputSchema),
	)
}

// GetUsersGroupsHandler is the handler function for the GetUsersGroups tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetUsersGroupsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/users/groups", args, []string{}, contentType, "GetUsersGroups")
}
