// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetUserTokensSearch tool
const GetUserTokensSearchInputSchema = "{\n  \"properties\": {\n    \"login\": {\n      \"description\": \"User login\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetUserTokensSearch tool (Status: 200, Content-Type: application/json)
const GetUserTokensSearchResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetUserTokensSearchMCPTool creates the MCP Tool instance for GetUserTokensSearch
func NewGetUserTokensSearchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetUserTokensSearch",
		"List the access tokens of a user. - List the access tokens of a user. The login must exist and active. Field 'lastConnectionDate' is only updated every hour, so it may not be accurate, for instance when a user is using a token many times in less than one hour. It requires administration permissions to specify a 'login' and list the tokens of another user. Otherwise, tokens for the current user are listed. Authentication is required for this API endpoint",
		[]byte(GetUserTokensSearchInputSchema),
	)
}

// GetUserTokensSearchHandler is the handler function for the GetUserTokensSearch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetUserTokensSearchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/user_tokens/search", args, []string{}, contentType, "GetUserTokensSearch")
}
