// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetUserGroupsUsers tool
const GetUserGroupsUsersInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"Group name\",\n      \"type\": \"string\"\n    },\n    \"p\": {\n      \"default\": \"1\",\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"default\": \"25\",\n      \"description\": \"Page size. Must be greater than 0.\",\n      \"type\": \"string\"\n    },\n    \"q\": {\n      \"description\": \"Limit search to names or logins that contain the supplied string.\",\n      \"type\": \"string\"\n    },\n    \"selected\": {\n      \"description\": \"Depending on the value, show only selected items (selected=selected), deselected items (selected=deselected), or all items with their selection status (selected=all).\",\n      \"enum\": [\n        \"all\",\n        \"deselected\",\n        \"selected\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetUserGroupsUsers tool (Status: 200, Content-Type: application/json)
const GetUserGroupsUsersResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetUserGroupsUsersMCPTool creates the MCP Tool instance for GetUserGroupsUsers
func NewGetUserGroupsUsersMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetUserGroupsUsers",
		"Search for users with membership information with respect to a group. - Search for users with membership information with respect to a group. Requires the following permission: 'Administer System'.",
		[]byte(GetUserGroupsUsersInputSchema),
	)
}

// GetUserGroupsUsersHandler is the handler function for the GetUserGroupsUsers tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetUserGroupsUsersHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/user_groups/users", args, []string{}, contentType, "GetUserGroupsUsers")
}
