// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetViewsList tool
const GetViewsListInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the GetViewsList tool (Status: 200, Content-Type: application/json)
const GetViewsListResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetViewsListMCPTool creates the MCP Tool instance for GetViewsList
func NewGetViewsListMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetViewsList",
		"List root portfolios. - List root portfolios. Requires authentication. Only portfolios with the admin permission are returned.",
		[]byte(GetViewsListInputSchema),
	)
}

// GetViewsListHandler is the handler function for the GetViewsList tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetViewsListHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/views/list", args, []string{}, contentType, "GetViewsList")
}
