// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetWebhooksList tool
const GetWebhooksListInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetWebhooksList tool (Status: 200, Content-Type: application/json)
const GetWebhooksListResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetWebhooksListMCPTool creates the MCP Tool instance for GetWebhooksList
func NewGetWebhooksListMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetWebhooksList",
		"Search for global webhooks or project webhooks. - Search for global webhooks or project webhooks. Webhooks are ordered by name. Requires 'Administer' permission on the specified project, or global 'Administer' permission.",
		[]byte(GetWebhooksListInputSchema),
	)
}

// GetWebhooksListHandler is the handler function for the GetWebhooksList tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetWebhooksListHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/webhooks/list", args, []string{}, contentType, "GetWebhooksList")
}
