// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetWebhooksDeliveries tool
const GetWebhooksDeliveriesInputSchema = "{\n  \"properties\": {\n    \"ceTaskId\": {\n      \"description\": \"Id of the Compute Engine task\",\n      \"type\": \"string\"\n    },\n    \"componentKey\": {\n      \"description\": \"Key of the project\",\n      \"type\": \"string\"\n    },\n    \"p\": {\n      \"default\": \"1\",\n      \"description\": \"1-based page number\",\n      \"type\": \"string\"\n    },\n    \"ps\": {\n      \"description\": \"Page size. Must be greater than 0 and less than 500\",\n      \"maximum\": 500,\n      \"type\": \"integer\"\n    },\n    \"webhook\": {\n      \"description\": \"Key of the webhook that triggered those deliveries, auto-generated value that can be obtained through api/webhooks/create or api/webhooks/list\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the GetWebhooksDeliveries tool (Status: 200, Content-Type: application/json)
const GetWebhooksDeliveriesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewGetWebhooksDeliveriesMCPTool creates the MCP Tool instance for GetWebhooksDeliveries
func NewGetWebhooksDeliveriesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetWebhooksDeliveries",
		"Get the recent deliveries for a specified project or Compute Engine task. - Get the recent deliveries for a specified project or Compute Engine task. Require 'Administer' permission on the related project. Note that additional information are returned by api/webhooks/delivery.",
		[]byte(GetWebhooksDeliveriesInputSchema),
	)
}

// GetWebhooksDeliveriesHandler is the handler function for the GetWebhooksDeliveries tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetWebhooksDeliveriesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/api/webhooks/deliveries", args, []string{}, contentType, "GetWebhooksDeliveries")
}
