// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsAddProjectBranch tool
const PostViewsAddProjectBranchInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Key of the branch\",\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Key of the portfolio\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Key of the project\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"branch\",\n    \"key\",\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsAddProjectBranchMCPTool creates the MCP Tool instance for PostViewsAddProjectBranch
func NewPostViewsAddProjectBranchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsAddProjectBranch",
		"Add a branch of a project selected in a portfolio. - Add a branch of a project selected in a portfolio. Requires 'Administrator' permission on the portfolio and 'Browse' permission for the project.",
		[]byte(PostViewsAddProjectBranchInputSchema),
	)
}

// PostViewsAddProjectBranchHandler is the handler function for the PostViewsAddProjectBranch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsAddProjectBranchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/add_project_branch", args, []string{}, contentType, "PostViewsAddProjectBranch")
}
