// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostEditionsActivateGracePeriod tool
const PostEditionsActivateGracePeriodInputSchema = "{\n  \"type\": \"object\"\n}"

// NewPostEditionsActivateGracePeriodMCPTool creates the MCP Tool instance for PostEditionsActivateGracePeriod
func NewPostEditionsActivateGracePeriodMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostEditionsActivateGracePeriod",
		"Enable a license 7-days grace period if the Server ID is invalid. - Enable a license 7-days grace period if the Server ID is invalid. Require 'Administer System' permission.",
		[]byte(PostEditionsActivateGracePeriodInputSchema),
	)
}

// PostEditionsActivateGracePeriodHandler is the handler function for the PostEditionsActivateGracePeriod tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostEditionsActivateGracePeriodHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/editions/activate_grace_period", args, []string{}, contentType, "PostEditionsActivateGracePeriod")
}
