// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUsersCreate tool
const PostUsersCreateInputSchema = "{\n  \"properties\": {\n    \"email\": {\n      \"description\": \"User email\",\n      \"maxLength\": 100,\n      \"type\": \"string\"\n    },\n    \"local\": {\n      \"description\": \"Specify if the user should be authenticated from SonarQube server or from an external authentication system. Password should not be set when local is set to false.\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"login\": {\n      \"description\": \"User login\",\n      \"maxLength\": 255,\n      \"minLength\": 2,\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"User name\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"password\": {\n      \"description\": \"User password. Only mandatory when creating local user, otherwise it should not be set\",\n      \"type\": \"string\"\n    },\n    \"scmAccount\": {\n      \"description\": \"List of SCM accounts. To set several values, the parameter must be called once for each value.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\",\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostUsersCreate tool (Status: 200, Content-Type: application/json)
const PostUsersCreateResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostUsersCreateMCPTool creates the MCP Tool instance for PostUsersCreate
func NewPostUsersCreateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUsersCreate",
		"Create a user. - Create a user. If a deactivated user account exists with the given login, it will be reactivated. Requires Administer System permission",
		[]byte(PostUsersCreateInputSchema),
	)
}

// PostUsersCreateHandler is the handler function for the PostUsersCreate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUsersCreateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/users/create", args, []string{}, contentType, "PostUsersCreate")
}
