// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostQualityprofilesActivateRule tool
const PostQualityprofilesActivateRuleInputSchema = "{\n  \"properties\": {\n    \"impacts\": {\n      \"description\": \"Override of impact severities for the rule. Cannot be used as the same time as 'severity'. Ignored if parameter reset is true.\",\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Quality Profile key. Can be obtained through api/qualityprofiles/search\",\n      \"type\": \"string\"\n    },\n    \"params\": {\n      \"description\": \"Parameters as semi-colon list of key=value. Ignored if parameter reset is true.\",\n      \"type\": \"string\"\n    },\n    \"prioritizedRule\": {\n      \"description\": \"Mark activated rule as prioritized, so all corresponding Issues will have to be fixed.\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"reset\": {\n      \"description\": \"Reset severity and parameters of activated rule. Set the values defined on parent profile or from rule default values.\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"rule\": {\n      \"description\": \"Rule key\",\n      \"type\": \"string\"\n    },\n    \"severity\": {\n      \"description\": \"Severity. Cannot be used as the same time as 'impacts'.Ignored if parameter reset is true.\",\n      \"enum\": [\n        \"INFO\",\n        \"MINOR\",\n        \"MAJOR\",\n        \"CRITICAL\",\n        \"BLOCKER\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\",\n    \"rule\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostQualityprofilesActivateRuleMCPTool creates the MCP Tool instance for PostQualityprofilesActivateRule
func NewPostQualityprofilesActivateRuleMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostQualityprofilesActivateRule",
		"Activate a rule on a Quality Profile. - Activate a rule on a Quality Profile. Requires one of the following permissions: - 'Administer Quality Profiles' - Edit right on the specified quality profile",
		[]byte(PostQualityprofilesActivateRuleInputSchema),
	)
}

// PostQualityprofilesActivateRuleHandler is the handler function for the PostQualityprofilesActivateRule tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostQualityprofilesActivateRuleHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/qualityprofiles/activate_rule", args, []string{}, contentType, "PostQualityprofilesActivateRule")
}
