// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUsersUpdateLogin tool
const PostUsersUpdateLoginInputSchema = "{\n  \"properties\": {\n    \"login\": {\n      \"description\": \"The current login (case-sensitive)\",\n      \"type\": \"string\"\n    },\n    \"newLogin\": {\n      \"description\": \"The new login. It must not already exist.\",\n      \"maxLength\": 255,\n      \"minLength\": 2,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\",\n    \"newLogin\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostUsersUpdateLoginMCPTool creates the MCP Tool instance for PostUsersUpdateLogin
func NewPostUsersUpdateLoginMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUsersUpdateLogin",
		"Update a user login. - Update a user login. A login can be updated many times. Requires Administer System permission",
		[]byte(PostUsersUpdateLoginInputSchema),
	)
}

// PostUsersUpdateLoginHandler is the handler function for the PostUsersUpdateLogin tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUsersUpdateLoginHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/users/update_login", args, []string{}, contentType, "PostUsersUpdateLogin")
}
