// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsUpdateGithub tool
const PostAlmSettingsUpdateGithubInputSchema = "{\n  \"properties\": {\n    \"appId\": {\n      \"description\": \"GitHub API ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    },\n    \"clientId\": {\n      \"description\": \"GitHub App Client ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    },\n    \"clientSecret\": {\n      \"description\": \"GitHub App Client Secret\",\n      \"maxLength\": 160,\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Unique key of the GitHub instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"newKey\": {\n      \"description\": \"Optional new value for an unique key of the GitHub instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"privateKey\": {\n      \"description\": \"GitHub App private key\",\n      \"maxLength\": 2500,\n      \"type\": \"string\"\n    },\n    \"url\": {\n      \"description\": \"GitHub API URL\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"webhookSecret\": {\n      \"description\": \"GitHub App Webhook Secret\",\n      \"maxLength\": 160,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"appId\",\n    \"clientId\",\n    \"key\",\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsUpdateGithubMCPTool creates the MCP Tool instance for PostAlmSettingsUpdateGithub
func NewPostAlmSettingsUpdateGithubMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsUpdateGithub",
		"Update GitHub instance Setting. - Update GitHub instance Setting. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsUpdateGithubInputSchema),
	)
}

// PostAlmSettingsUpdateGithubHandler is the handler function for the PostAlmSettingsUpdateGithub tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsUpdateGithubHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/update_github", args, []string{}, contentType, "PostAlmSettingsUpdateGithub")
}
