// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsCreateGitlab tool
const PostAlmSettingsCreateGitlabInputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"Unique key of the GitLab instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"personalAccessToken\": {\n      \"description\": \"GitLab personal access token\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"url\": {\n      \"description\": \"GitLab API URL\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\",\n    \"personalAccessToken\",\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsCreateGitlabMCPTool creates the MCP Tool instance for PostAlmSettingsCreateGitlab
func NewPostAlmSettingsCreateGitlabMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsCreateGitlab",
		"Create GitLab instance Setting. - Create GitLab instance Setting. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsCreateGitlabInputSchema),
	)
}

// PostAlmSettingsCreateGitlabHandler is the handler function for the PostAlmSettingsCreateGitlab tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsCreateGitlabHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/create_gitlab", args, []string{}, contentType, "PostAlmSettingsCreateGitlab")
}
