// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmIntegrationsImportAzureProject tool
const PostAlmIntegrationsImportAzureProjectInputSchema = "{\n  \"properties\": {\n    \"almSetting\": {\n      \"description\": \"DevOps Platform configuration key. This parameter is optional if you have only one Azure integration.\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"newCodeDefinitionType\": {\n      \"description\": \"Project New Code Definition Type New code definitions of the following types are allowed: - PREVIOUS_VERSION - NUMBER_OF_DAYS - REFERENCE_BRANCH - will default to the main branch.\",\n      \"type\": \"string\"\n    },\n    \"newCodeDefinitionValue\": {\n      \"description\": \"Project New Code Definition Value For each new code definition type, a different value is expected: - no value, when the new code definition type is PREVIOUS_VERSION and REFERENCE_BRANCH - a number between 1 and 90, when the new code definition type is NUMBER_OF_DAYS\",\n      \"type\": \"string\"\n    },\n    \"projectName\": {\n      \"description\": \"Azure project name\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"repositoryName\": {\n      \"description\": \"Azure repository name\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"projectName\",\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmIntegrationsImportAzureProjectMCPTool creates the MCP Tool instance for PostAlmIntegrationsImportAzureProject
func NewPostAlmIntegrationsImportAzureProjectMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmIntegrationsImportAzureProject",
		"Create a SonarQube project with the information from the provided Azure DevOps project. - Create a SonarQube project with the information from the provided Azure DevOps project. Autoconfigure pull request decoration mechanism. Requires the 'Create Projects' permission",
		[]byte(PostAlmIntegrationsImportAzureProjectInputSchema),
	)
}

// PostAlmIntegrationsImportAzureProjectHandler is the handler function for the PostAlmIntegrationsImportAzureProject tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmIntegrationsImportAzureProjectHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_integrations/import_azure_project", args, []string{}, contentType, "PostAlmIntegrationsImportAzureProject")
}
