// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectBranchesRename tool
const PostProjectBranchesRenameInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"New name of the main branch\",\n      \"maxLength\": 255,\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\",\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectBranchesRenameMCPTool creates the MCP Tool instance for PostProjectBranchesRename
func NewPostProjectBranchesRenameMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectBranchesRename",
		"Rename the main branch of a project or application. - Rename the main branch of a project or application. Requires 'Administer' permission on the specified project or application.",
		[]byte(PostProjectBranchesRenameInputSchema),
	)
}

// PostProjectBranchesRenameHandler is the handler function for the PostProjectBranchesRename tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectBranchesRenameHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/project_branches/rename", args, []string{}, contentType, "PostProjectBranchesRename")
}
