// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsUpdateBitbucketcloud tool
const PostAlmSettingsUpdateBitbucketcloudInputSchema = "{\n  \"properties\": {\n    \"clientId\": {\n      \"description\": \"Bitbucket Cloud Client ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    },\n    \"clientSecret\": {\n      \"description\": \"Optional new value for the Bitbucket Cloud client secret\",\n      \"maxLength\": 160,\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Unique key of the Bitbucket Cloud setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"newKey\": {\n      \"description\": \"Optional new value for an unique key of the Bitbucket Cloud setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"workspace\": {\n      \"description\": \"Bitbucket Cloud workspace ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"clientId\",\n    \"key\",\n    \"workspace\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsUpdateBitbucketcloudMCPTool creates the MCP Tool instance for PostAlmSettingsUpdateBitbucketcloud
func NewPostAlmSettingsUpdateBitbucketcloudMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsUpdateBitbucketcloud",
		"Update Bitbucket Cloud Setting. - Update Bitbucket Cloud Setting. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsUpdateBitbucketcloudInputSchema),
	)
}

// PostAlmSettingsUpdateBitbucketcloudHandler is the handler function for the PostAlmSettingsUpdateBitbucketcloud tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsUpdateBitbucketcloudHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/update_bitbucketcloud", args, []string{}, contentType, "PostAlmSettingsUpdateBitbucketcloud")
}
