// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsDelete tool
const PostViewsDeleteInputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"Portfolio key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsDeleteMCPTool creates the MCP Tool instance for PostViewsDelete
func NewPostViewsDeleteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsDelete",
		"Delete a portfolio definition. - Delete a portfolio definition. Requires 'Administrator' permission on the portfolio.",
		[]byte(PostViewsDeleteInputSchema),
	)
}

// PostViewsDeleteHandler is the handler function for the PostViewsDelete tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsDeleteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/delete", args, []string{}, contentType, "PostViewsDelete")
}
