// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAuthenticationLogin tool
const PostAuthenticationLoginInputSchema = "{\n  \"properties\": {\n    \"login\": {\n      \"description\": \"Login of the user\",\n      \"type\": \"string\"\n    },\n    \"password\": {\n      \"description\": \"Password of the user\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\",\n    \"password\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAuthenticationLoginMCPTool creates the MCP Tool instance for PostAuthenticationLogin
func NewPostAuthenticationLoginMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAuthenticationLogin",
		"Authenticate a user. - Authenticate a user.",
		[]byte(PostAuthenticationLoginInputSchema),
	)
}

// PostAuthenticationLoginHandler is the handler function for the PostAuthenticationLogin tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAuthenticationLoginHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/authentication/login", args, []string{}, contentType, "PostAuthenticationLogin")
}
