// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostCeCancel tool
const PostCeCancelInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Id of the task to cancel.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostCeCancelMCPTool creates the MCP Tool instance for PostCeCancel
func NewPostCeCancelMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostCeCancel",
		"Cancels a pending task. - Cancels a pending task. In-progress tasks cannot be canceled. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the project related to the task",
		[]byte(PostCeCancelInputSchema),
	)
}

// PostCeCancelHandler is the handler function for the PostCeCancel tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostCeCancelHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/ce/cancel", args, []string{}, contentType, "PostCeCancel")
}
