// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsAddPortfolio tool
const PostViewsAddPortfolioInputSchema = "{\n  \"properties\": {\n    \"portfolio\": {\n      \"description\": \"Key of the portfolio where a reference will be added\",\n      \"type\": \"string\"\n    },\n    \"reference\": {\n      \"description\": \"Key of the portfolio to be added\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"portfolio\",\n    \"reference\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsAddPortfolioMCPTool creates the MCP Tool instance for PostViewsAddPortfolio
func NewPostViewsAddPortfolioMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsAddPortfolio",
		"Add an existing portfolio to the structure of another portfolio. - Add an existing portfolio to the structure of another portfolio. Authentication is required for this API endpoint.",
		[]byte(PostViewsAddPortfolioInputSchema),
	)
}

// PostViewsAddPortfolioHandler is the handler function for the PostViewsAddPortfolio tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsAddPortfolioHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/add_portfolio", args, []string{}, contentType, "PostViewsAddPortfolio")
}
