// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsDeleteBinding tool
const PostAlmSettingsDeleteBindingInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsDeleteBindingMCPTool creates the MCP Tool instance for PostAlmSettingsDeleteBinding
func NewPostAlmSettingsDeleteBindingMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsDeleteBinding",
		"Delete the DevOps Platform binding of a project. - Delete the DevOps Platform binding of a project. Requires the 'Administer' permission on the project",
		[]byte(PostAlmSettingsDeleteBindingInputSchema),
	)
}

// PostAlmSettingsDeleteBindingHandler is the handler function for the PostAlmSettingsDeleteBinding tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsDeleteBindingHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/delete_binding", args, []string{}, contentType, "PostAlmSettingsDeleteBinding")
}
