// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsUpdateAzure tool
const PostAlmSettingsUpdateAzureInputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"Unique key of the Azure instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"newKey\": {\n      \"description\": \"Optional new value for an unique key of the Azure Devops instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"personalAccessToken\": {\n      \"description\": \"Azure Devops personal access token\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"url\": {\n      \"description\": \"Azure API URL\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\",\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsUpdateAzureMCPTool creates the MCP Tool instance for PostAlmSettingsUpdateAzure
func NewPostAlmSettingsUpdateAzureMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsUpdateAzure",
		"Update Azure instance Setting. - Update Azure instance Setting. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsUpdateAzureInputSchema),
	)
}

// PostAlmSettingsUpdateAzureHandler is the handler function for the PostAlmSettingsUpdateAzure tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsUpdateAzureHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/update_azure", args, []string{}, contentType, "PostAlmSettingsUpdateAzure")
}
