// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostGithubProvisioningSync tool
const PostGithubProvisioningSyncInputSchema = "{\n  \"type\": \"object\"\n}"

// NewPostGithubProvisioningSyncMCPTool creates the MCP Tool instance for PostGithubProvisioningSync
func NewPostGithubProvisioningSyncMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostGithubProvisioningSync",
		"Schedule a GitHub provisioning task. - Schedule a GitHub provisioning task. Requires GitHub provisioning feature to be enabled. Requires the 'Administer System' permission.",
		[]byte(PostGithubProvisioningSyncInputSchema),
	)
}

// PostGithubProvisioningSyncHandler is the handler function for the PostGithubProvisioningSync tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostGithubProvisioningSyncHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/github_provisioning/sync", args, []string{}, contentType, "PostGithubProvisioningSync")
}
