// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostPermissionsCreateTemplate tool
const PostPermissionsCreateTemplateInputSchema = "{\n  \"properties\": {\n    \"description\": {\n      \"description\": \"Description\",\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"Name\",\n      \"type\": \"string\"\n    },\n    \"projectKeyPattern\": {\n      \"description\": \"Project key pattern. Must be a valid Java regular expression\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostPermissionsCreateTemplate tool (Status: 200, Content-Type: application/json)
const PostPermissionsCreateTemplateResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostPermissionsCreateTemplateMCPTool creates the MCP Tool instance for PostPermissionsCreateTemplate
func NewPostPermissionsCreateTemplateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostPermissionsCreateTemplate",
		"Create a permission template. - Create a permission template. Requires the following permission: 'Administer System'.",
		[]byte(PostPermissionsCreateTemplateInputSchema),
	)
}

// PostPermissionsCreateTemplateHandler is the handler function for the PostPermissionsCreateTemplate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostPermissionsCreateTemplateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/permissions/create_template", args, []string{}, contentType, "PostPermissionsCreateTemplate")
}
