// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostApplicationsAddProject tool
const PostApplicationsAddProjectInputSchema = "{\n  \"properties\": {\n    \"application\": {\n      \"description\": \"Key of the application\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Key of the project\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"application\",\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostApplicationsAddProjectMCPTool creates the MCP Tool instance for PostApplicationsAddProject
func NewPostApplicationsAddProjectMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostApplicationsAddProject",
		"Add a project to an application. - Add a project to an application. Requires 'Administrator' permission on the application",
		[]byte(PostApplicationsAddProjectInputSchema),
	)
}

// PostApplicationsAddProjectHandler is the handler function for the PostApplicationsAddProject tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostApplicationsAddProjectHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/applications/add_project", args, []string{}, contentType, "PostApplicationsAddProject")
}
