// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectAnalysesUpdateEvent tool
const PostProjectAnalysesUpdateEventInputSchema = "{\n  \"properties\": {\n    \"event\": {\n      \"description\": \"Event key\",\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"New name\",\n      \"maxLength\": 400,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"event\",\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostProjectAnalysesUpdateEvent tool (Status: 200, Content-Type: application/json)
const PostProjectAnalysesUpdateEventResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostProjectAnalysesUpdateEventMCPTool creates the MCP Tool instance for PostProjectAnalysesUpdateEvent
func NewPostProjectAnalysesUpdateEventMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectAnalysesUpdateEvent",
		"Update a project analysis event. - Update a project analysis event. Only events of category 'VERSION' and 'OTHER' can be updated. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the specified project",
		[]byte(PostProjectAnalysesUpdateEventInputSchema),
	)
}

// PostProjectAnalysesUpdateEventHandler is the handler function for the PostProjectAnalysesUpdateEvent tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectAnalysesUpdateEventHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/project_analyses/update_event", args, []string{}, contentType, "PostProjectAnalysesUpdateEvent")
}
