// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostRulesDelete tool
const PostRulesDeleteInputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"Rule key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostRulesDeleteMCPTool creates the MCP Tool instance for PostRulesDelete
func NewPostRulesDeleteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostRulesDelete",
		"Delete custom rule. - Delete custom rule. Requires the 'Administer Quality Profiles' permission",
		[]byte(PostRulesDeleteInputSchema),
	)
}

// PostRulesDeleteHandler is the handler function for the PostRulesDelete tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostRulesDeleteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/rules/delete", args, []string{}, contentType, "PostRulesDelete")
}
