// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectTagsSet tool
const PostProjectTagsSetInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"tags\": {\n      \"description\": \"Comma-separated list of tags\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\",\n    \"tags\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectTagsSetMCPTool creates the MCP Tool instance for PostProjectTagsSet
func NewPostProjectTagsSetMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectTagsSet",
		"Set tags on a project. - Set tags on a project. Requires the following permission: 'Administer' rights on the specified project",
		[]byte(PostProjectTagsSetInputSchema),
	)
}

// PostProjectTagsSetHandler is the handler function for the PostProjectTagsSet tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectTagsSetHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/project_tags/set", args, []string{}, contentType, "PostProjectTagsSet")
}
