// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsRemovePortfolio tool
const PostViewsRemovePortfolioInputSchema = "{\n  \"properties\": {\n    \"portfolio\": {\n      \"description\": \"Portfolio key\",\n      \"type\": \"string\"\n    },\n    \"reference\": {\n      \"description\": \"Key of the referenced portfolio to be removed\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"portfolio\",\n    \"reference\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsRemovePortfolioMCPTool creates the MCP Tool instance for PostViewsRemovePortfolio
func NewPostViewsRemovePortfolioMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsRemovePortfolio",
		"Remove a reference to a portfolio. - Remove a reference to a portfolio. Requires 'Administrator' permission on the portfolio.",
		[]byte(PostViewsRemovePortfolioInputSchema),
	)
}

// PostViewsRemovePortfolioHandler is the handler function for the PostViewsRemovePortfolio tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsRemovePortfolioHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/remove_portfolio", args, []string{}, contentType, "PostViewsRemovePortfolio")
}
