// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostCeSetWorkerCount tool
const PostCeSetWorkerCountInputSchema = "{\n  \"properties\": {\n    \"count\": {\n      \"description\": \"The number of workers to be used in the Compute Engine. Value must be between 1 and 10.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"count\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostCeSetWorkerCountMCPTool creates the MCP Tool instance for PostCeSetWorkerCount
func NewPostCeSetWorkerCountMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostCeSetWorkerCount",
		"Set the number of workers in the Compute Engine. - Set the number of workers in the Compute Engine. If your queue backs up behind analysis reports from large projects, increasing the number of Compute Engine workers will allow you to take full advantage of having configured increased Compute Engine memory on a multi-core server (vertical scaling). Requires the system administration permission",
		[]byte(PostCeSetWorkerCountInputSchema),
	)
}

// PostCeSetWorkerCountHandler is the handler function for the PostCeSetWorkerCount tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostCeSetWorkerCountHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/ce/set_worker_count", args, []string{}, contentType, "PostCeSetWorkerCount")
}
