// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostPermissionsRemoveGroup tool
const PostPermissionsRemoveGroupInputSchema = "{\n  \"properties\": {\n    \"groupName\": {\n      \"description\": \"Group name or 'anyone' (case insensitive)\",\n      \"type\": \"string\"\n    },\n    \"permission\": {\n      \"description\": \"The permission you would like to revoke from the group. - Possible values for global permissions: admin, gateadmin, profileadmin, provisioning, scan, applicationcreator, portfoliocreator - Possible values for project permissions admin, codeviewer, issueadmin, securityhotspotadmin, architectureadmin, scan, user\",\n      \"type\": \"string\"\n    },\n    \"projectId\": {\n      \"description\": \"Project id\",\n      \"type\": \"string\"\n    },\n    \"projectKey\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"groupName\",\n    \"permission\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostPermissionsRemoveGroupMCPTool creates the MCP Tool instance for PostPermissionsRemoveGroup
func NewPostPermissionsRemoveGroupMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostPermissionsRemoveGroup",
		"Remove a permission from a group. - Remove a permission from a group. This service defaults to global permissions, but can be limited to project permissions by providing project id or project key. The group name must be provided. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the specified project",
		[]byte(PostPermissionsRemoveGroupInputSchema),
	)
}

// PostPermissionsRemoveGroupHandler is the handler function for the PostPermissionsRemoveGroup tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostPermissionsRemoveGroupHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/permissions/remove_group", args, []string{}, contentType, "PostPermissionsRemoveGroup")
}
