// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsRemoveApplicationBranch tool
const PostViewsRemoveApplicationBranchInputSchema = "{\n  \"properties\": {\n    \"application\": {\n      \"description\": \"Key of the project\",\n      \"type\": \"string\"\n    },\n    \"branch\": {\n      \"description\": \"Key of the branch\",\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Key of the portfolio\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"application\",\n    \"branch\",\n    \"key\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsRemoveApplicationBranchMCPTool creates the MCP Tool instance for PostViewsRemoveApplicationBranch
func NewPostViewsRemoveApplicationBranchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsRemoveApplicationBranch",
		"Remove a branch of an application selected in a portfolio. - Remove a branch of an application selected in a portfolio. Requires 'Administrator' permission on the portfolio and 'Browse' permission for the application.",
		[]byte(PostViewsRemoveApplicationBranchInputSchema),
	)
}

// PostViewsRemoveApplicationBranchHandler is the handler function for the PostViewsRemoveApplicationBranch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsRemoveApplicationBranchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/remove_application_branch", args, []string{}, contentType, "PostViewsRemoveApplicationBranch")
}
