// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostSettingsReset tool
const PostSettingsResetInputSchema = "{\n  \"properties\": {\n    \"component\": {\n      \"description\": \"Component key. Only keys for projects, applications, portfolios or subportfolios are accepted.\",\n      \"type\": \"string\"\n    },\n    \"keys\": {\n      \"description\": \"Comma-separated list of keys\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"keys\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostSettingsResetMCPTool creates the MCP Tool instance for PostSettingsReset
func NewPostSettingsResetMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostSettingsReset",
		"Remove a setting value. - Remove a setting value. The settings defined in conf/sonar.properties are read-only and can't be changed. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the specified component",
		[]byte(PostSettingsResetInputSchema),
	)
}

// PostSettingsResetHandler is the handler function for the PostSettingsReset tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostSettingsResetHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/settings/reset", args, []string{}, contentType, "PostSettingsReset")
}
