// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostEmailsSend tool
const PostEmailsSendInputSchema = "{\n  \"properties\": {\n    \"message\": {\n      \"description\": \"Content of the email\",\n      \"type\": \"string\"\n    },\n    \"subject\": {\n      \"description\": \"Subject of the email\",\n      \"type\": \"string\"\n    },\n    \"to\": {\n      \"description\": \"Email address\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"message\",\n    \"to\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostEmailsSendMCPTool creates the MCP Tool instance for PostEmailsSend
func NewPostEmailsSendMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostEmailsSend",
		"Test email configuration by sending an email. - Test email configuration by sending an email Requires 'Administer System' permission.",
		[]byte(PostEmailsSendInputSchema),
	)
}

// PostEmailsSendHandler is the handler function for the PostEmailsSend tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostEmailsSendHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/emails/send", args, []string{}, contentType, "PostEmailsSend")
}
