// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectsUpdateKey tool
const PostProjectsUpdateKeyInputSchema = "{\n  \"properties\": {\n    \"from\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"to\": {\n      \"description\": \"New project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"from\",\n    \"to\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectsUpdateKeyMCPTool creates the MCP Tool instance for PostProjectsUpdateKey
func NewPostProjectsUpdateKeyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectsUpdateKey",
		"Update a project all its sub-components keys. - Update a project all its sub-components keys. Requires 'Administer' permission on the project.",
		[]byte(PostProjectsUpdateKeyInputSchema),
	)
}

// PostProjectsUpdateKeyHandler is the handler function for the PostProjectsUpdateKey tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectsUpdateKeyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/projects/update_key", args, []string{}, contentType, "PostProjectsUpdateKey")
}
