// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostPermissionsUpdateTemplate tool
const PostPermissionsUpdateTemplateInputSchema = "{\n  \"properties\": {\n    \"description\": {\n      \"description\": \"Description\",\n      \"type\": \"string\"\n    },\n    \"id\": {\n      \"description\": \"Id\",\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"Name\",\n      \"type\": \"string\"\n    },\n    \"projectKeyPattern\": {\n      \"description\": \"Project key pattern. Must be a valid Java regular expression\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostPermissionsUpdateTemplate tool (Status: 200, Content-Type: application/json)
const PostPermissionsUpdateTemplateResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostPermissionsUpdateTemplateMCPTool creates the MCP Tool instance for PostPermissionsUpdateTemplate
func NewPostPermissionsUpdateTemplateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostPermissionsUpdateTemplate",
		"Update a permission template. - Update a permission template. Requires the following permission: 'Administer System'.",
		[]byte(PostPermissionsUpdateTemplateInputSchema),
	)
}

// PostPermissionsUpdateTemplateHandler is the handler function for the PostPermissionsUpdateTemplate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostPermissionsUpdateTemplateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/permissions/update_template", args, []string{}, contentType, "PostPermissionsUpdateTemplate")
}
