// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUsersUpdateIdentityProvider tool
const PostUsersUpdateIdentityProviderInputSchema = "{\n  \"properties\": {\n    \"login\": {\n      \"description\": \"User login\",\n      \"type\": \"string\"\n    },\n    \"newExternalIdentity\": {\n      \"description\": \"New external identity, usually the login used in the authentication system. If not provided previous identity will be used.\",\n      \"type\": \"string\"\n    },\n    \"newExternalProvider\": {\n      \"description\": \"New external provider. Only authentication system installed are available. Use 'LDAP' identity provider for single server LDAP setup.Use 'LDAP_{serverKey}' identity provider for multiple LDAP servers setup.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\",\n    \"newExternalProvider\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostUsersUpdateIdentityProviderMCPTool creates the MCP Tool instance for PostUsersUpdateIdentityProvider
func NewPostUsersUpdateIdentityProviderMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUsersUpdateIdentityProvider",
		"Update identity provider information. - Update identity provider information. It's only possible to migrate to an installed identity provider. Be careful that as soon as this information has been updated for a user, the user will only be able to authenticate on the new identity provider. It is not possible to migrate external user to local one. Requires Administer System permission.",
		[]byte(PostUsersUpdateIdentityProviderInputSchema),
	)
}

// PostUsersUpdateIdentityProviderHandler is the handler function for the PostUsersUpdateIdentityProvider tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUsersUpdateIdentityProviderHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/users/update_identity_provider", args, []string{}, contentType, "PostUsersUpdateIdentityProvider")
}
