// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUserGroupsDelete tool
const PostUserGroupsDeleteInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"Group name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostUserGroupsDeleteMCPTool creates the MCP Tool instance for PostUserGroupsDelete
func NewPostUserGroupsDeleteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUserGroupsDelete",
		"Delete a group. - Delete a group. The default groups cannot be deleted. 'name' must be provided. Requires the following permission: 'Administer System'.",
		[]byte(PostUserGroupsDeleteInputSchema),
	)
}

// PostUserGroupsDeleteHandler is the handler function for the PostUserGroupsDelete tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUserGroupsDeleteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/user_groups/delete", args, []string{}, contentType, "PostUserGroupsDelete")
}
