// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsUpdateBitbucket tool
const PostAlmSettingsUpdateBitbucketInputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"Unique key of the Bitbucket instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"newKey\": {\n      \"description\": \"Optional new value for an unique key of the Bitbucket instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"personalAccessToken\": {\n      \"description\": \"Bitbucket personal access token\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"url\": {\n      \"description\": \"Bitbucket API URL\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\",\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsUpdateBitbucketMCPTool creates the MCP Tool instance for PostAlmSettingsUpdateBitbucket
func NewPostAlmSettingsUpdateBitbucketMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsUpdateBitbucket",
		"Update Bitbucket instance Setting. - Update Bitbucket instance Setting. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsUpdateBitbucketInputSchema),
	)
}

// PostAlmSettingsUpdateBitbucketHandler is the handler function for the PostAlmSettingsUpdateBitbucket tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsUpdateBitbucketHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/update_bitbucket", args, []string{}, contentType, "PostAlmSettingsUpdateBitbucket")
}
