// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostIssuesBulkChange tool
const PostIssuesBulkChangeInputSchema = "{\n  \"properties\": {\n    \"add_tags\": {\n      \"description\": \"Add tags\",\n      \"type\": \"string\"\n    },\n    \"assign\": {\n      \"description\": \"To assign the list of issues to a specific user (login), or un-assign all the issues\",\n      \"type\": \"string\"\n    },\n    \"comment\": {\n      \"description\": \"Add a comment. The comment will only be added to issues that are affected either by a change of type or a change of severity as a result of the same WS call.\",\n      \"type\": \"string\"\n    },\n    \"do_transition\": {\n      \"description\": \"Transition\",\n      \"enum\": [\n        \"confirm\",\n        \"unconfirm\",\n        \"reopen\",\n        \"resolve\",\n        \"falsepositive\",\n        \"wontfix\",\n        \"resolveasreviewed\",\n        \"resetastoreview\",\n        \"accept\"\n      ],\n      \"type\": \"string\"\n    },\n    \"issues\": {\n      \"description\": \"Comma-separated list of issue keys\",\n      \"type\": \"string\"\n    },\n    \"remove_tags\": {\n      \"description\": \"Remove tags\",\n      \"type\": \"string\"\n    },\n    \"sendNotifications\": {\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    },\n    \"set_severity\": {\n      \"description\": \"To change the severity of the list of issues\",\n      \"enum\": [\n        \"INFO\",\n        \"MINOR\",\n        \"MAJOR\",\n        \"CRITICAL\",\n        \"BLOCKER\"\n      ],\n      \"type\": \"string\"\n    },\n    \"set_type\": {\n      \"description\": \"To change the type of the list of issues\",\n      \"enum\": [\n        \"CODE_SMELL\",\n        \"BUG\",\n        \"VULNERABILITY\",\n        \"SECURITY_HOTSPOT\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"issues\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostIssuesBulkChange tool (Status: 200, Content-Type: application/json)
const PostIssuesBulkChangeResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostIssuesBulkChangeMCPTool creates the MCP Tool instance for PostIssuesBulkChange
func NewPostIssuesBulkChangeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostIssuesBulkChange",
		"Bulk change on issues. - Bulk change on issues. Up to 500 issues can be updated. Requires authentication.",
		[]byte(PostIssuesBulkChangeInputSchema),
	)
}

// PostIssuesBulkChangeHandler is the handler function for the PostIssuesBulkChange tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostIssuesBulkChangeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/issues/bulk_change", args, []string{}, contentType, "PostIssuesBulkChange")
}
