// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostScimManagementEnable tool
const PostScimManagementEnableInputSchema = "{\n  \"type\": \"object\"\n}"

// NewPostScimManagementEnableMCPTool creates the MCP Tool instance for PostScimManagementEnable
func NewPostScimManagementEnableMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostScimManagementEnable",
		"Enable SCIM at the instance level. - Enable SCIM at the instance level. Enabling SCIM will turn users and groups read-only on SonarQube. To administer users and groups, use your Identity Provider Requires the 'Administer System' permission.",
		[]byte(PostScimManagementEnableInputSchema),
	)
}

// PostScimManagementEnableHandler is the handler function for the PostScimManagementEnable tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostScimManagementEnableHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/scim_management/enable", args, []string{}, contentType, "PostScimManagementEnable")
}
