// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostPermissionsRemoveProjectCreatorFromTemplate tool
const PostPermissionsRemoveProjectCreatorFromTemplateInputSchema = "{\n  \"properties\": {\n    \"permission\": {\n      \"description\": \"Permission - Possible values for project permissions admin, codeviewer, issueadmin, securityhotspotadmin, architectureadmin, scan, user\",\n      \"enum\": [\n        \"admin\",\n        \"codeviewer\",\n        \"issueadmin\",\n        \"securityhotspotadmin\",\n        \"architectureadmin\",\n        \"scan\",\n        \"user\"\n      ],\n      \"type\": \"string\"\n    },\n    \"templateId\": {\n      \"description\": \"Template id\",\n      \"type\": \"string\"\n    },\n    \"templateName\": {\n      \"description\": \"Template name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"permission\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostPermissionsRemoveProjectCreatorFromTemplateMCPTool creates the MCP Tool instance for PostPermissionsRemoveProjectCreatorFromTemplate
func NewPostPermissionsRemoveProjectCreatorFromTemplateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostPermissionsRemoveProjectCreatorFromTemplate",
		"Remove a project creator from a permission template. - Remove a project creator from a permission template. Requires the following permission: 'Administer System'.",
		[]byte(PostPermissionsRemoveProjectCreatorFromTemplateInputSchema),
	)
}

// PostPermissionsRemoveProjectCreatorFromTemplateHandler is the handler function for the PostPermissionsRemoveProjectCreatorFromTemplate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostPermissionsRemoveProjectCreatorFromTemplateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/permissions/remove_project_creator_from_template", args, []string{}, contentType, "PostPermissionsRemoveProjectCreatorFromTemplate")
}
