// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmIntegrationsSetPat tool
const PostAlmIntegrationsSetPatInputSchema = "{\n  \"properties\": {\n    \"almSetting\": {\n      \"description\": \"DevOps Platform configuration key. This parameter is optional if you have only one single DevOps Platform integration.\",\n      \"type\": \"string\"\n    },\n    \"pat\": {\n      \"description\": \"Personal Access Token\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"username\": {\n      \"description\": \"Username\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"pat\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmIntegrationsSetPatMCPTool creates the MCP Tool instance for PostAlmIntegrationsSetPat
func NewPostAlmIntegrationsSetPatMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmIntegrationsSetPat",
		"Set a Personal Access Token for the given DevOps Platform setting. - Set a Personal Access Token for the given DevOps Platform setting Requires the 'Create Projects' permission",
		[]byte(PostAlmIntegrationsSetPatInputSchema),
	)
}

// PostAlmIntegrationsSetPatHandler is the handler function for the PostAlmIntegrationsSetPat tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmIntegrationsSetPatHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_integrations/set_pat", args, []string{}, contentType, "PostAlmIntegrationsSetPat")
}
