// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostQualityprofilesRemoveUser tool
const PostQualityprofilesRemoveUserInputSchema = "{\n  \"properties\": {\n    \"language\": {\n      \"description\": \"Quality profile language\",\n      \"enum\": [\n        \"kubernetes\",\n        \"css\",\n        \"py\",\n        \"plsql\",\n        \"apex\",\n        \"java\",\n        \"xml\",\n        \"powershell\",\n        \"ipynb\",\n        \"text\",\n        \"azurepipelines\",\n        \"swift\",\n        \"yaml\",\n        \"cpp\",\n        \"vb\",\n        \"secrets\",\n        \"groovy\",\n        \"shell\",\n        \"terraform\",\n        \"azureresourcemanager\",\n        \"abap\",\n        \"scala\",\n        \"jsp\",\n        \"js\",\n        \"sql\",\n        \"docker\",\n        \"ansible\",\n        \"dart\",\n        \"rust\",\n        \"jcl\",\n        \"web\",\n        \"flex\",\n        \"json\",\n        \"vbnet\",\n        \"cloudformation\",\n        \"c\",\n        \"go\",\n        \"kotlin\",\n        \"rpg\",\n        \"pli\",\n        \"tsql\",\n        \"ruby\",\n        \"cs\",\n        \"cobol\",\n        \"php\",\n        \"gosu\",\n        \"objc\",\n        \"ts\",\n        \"githubactions\"\n      ],\n      \"type\": \"string\"\n    },\n    \"login\": {\n      \"description\": \"User login\",\n      \"type\": \"string\"\n    },\n    \"qualityProfile\": {\n      \"description\": \"Quality Profile name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"language\",\n    \"login\",\n    \"qualityProfile\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostQualityprofilesRemoveUserMCPTool creates the MCP Tool instance for PostQualityprofilesRemoveUser
func NewPostQualityprofilesRemoveUserMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostQualityprofilesRemoveUser",
		"Remove the ability from a user to edit a Quality Profile. - Remove the ability from a user to edit a Quality Profile. Requires one of the following permissions: - 'Administer Quality Profiles' - Edit right on the specified quality profile",
		[]byte(PostQualityprofilesRemoveUserInputSchema),
	)
}

// PostQualityprofilesRemoveUserHandler is the handler function for the PostQualityprofilesRemoveUser tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostQualityprofilesRemoveUserHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/qualityprofiles/remove_user", args, []string{}, contentType, "PostQualityprofilesRemoveUser")
}
