// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectPullRequestsDelete tool
const PostProjectPullRequestsDeleteInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"pullRequest\": {\n      \"description\": \"Pull request id\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\",\n    \"pullRequest\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectPullRequestsDeleteMCPTool creates the MCP Tool instance for PostProjectPullRequestsDelete
func NewPostProjectPullRequestsDeleteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectPullRequestsDelete",
		"Delete a pull request. - Delete a pull request. Requires 'Administer' rights on the specified project.",
		[]byte(PostProjectPullRequestsDeleteInputSchema),
	)
}

// PostProjectPullRequestsDeleteHandler is the handler function for the PostProjectPullRequestsDelete tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectPullRequestsDeleteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/project_pull_requests/delete", args, []string{}, contentType, "PostProjectPullRequestsDelete")
}
