// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsAddApplication tool
const PostViewsAddApplicationInputSchema = "{\n  \"properties\": {\n    \"application\": {\n      \"description\": \"Key of the application to be added\",\n      \"type\": \"string\"\n    },\n    \"portfolio\": {\n      \"description\": \"Key of the portfolio where the application will be added\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"application\",\n    \"portfolio\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsAddApplicationMCPTool creates the MCP Tool instance for PostViewsAddApplication
func NewPostViewsAddApplicationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsAddApplication",
		"Add an existing application to a portfolio. - Add an existing application to a portfolio. Authentication is required for this API endpoint.",
		[]byte(PostViewsAddApplicationInputSchema),
	)
}

// PostViewsAddApplicationHandler is the handler function for the PostViewsAddApplication tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsAddApplicationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/add_application", args, []string{}, contentType, "PostViewsAddApplication")
}
