// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUsersSetAiToolUsage tool
const PostUsersSetAiToolUsageInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostUsersSetAiToolUsageMCPTool creates the MCP Tool instance for PostUsersSetAiToolUsage
func NewPostUsersSetAiToolUsageMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUsersSetAiToolUsage",
		"Indicates whether the current user utilizes any tool that generates AI code for a given project. - Indicates whether the current user utilizes any tool that generates AI code for a given project. Requires 'Browse' permission on the specified project.",
		[]byte(PostUsersSetAiToolUsageInputSchema),
	)
}

// PostUsersSetAiToolUsageHandler is the handler function for the PostUsersSetAiToolUsage tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUsersSetAiToolUsageHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/users/set_ai_tool_usage", args, []string{}, contentType, "PostUsersSetAiToolUsage")
}
