// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostPermissionsAddUser tool
const PostPermissionsAddUserInputSchema = "{\n  \"properties\": {\n    \"login\": {\n      \"description\": \"User login\",\n      \"type\": \"string\"\n    },\n    \"permission\": {\n      \"description\": \"The permission you would like to grant to the user - Possible values for global permissions: admin, gateadmin, profileadmin, provisioning, scan, applicationcreator, portfoliocreator - Possible values for project permissions admin, codeviewer, issueadmin, securityhotspotadmin, architectureadmin, scan, user\",\n      \"type\": \"string\"\n    },\n    \"projectId\": {\n      \"description\": \"Project id\",\n      \"type\": \"string\"\n    },\n    \"projectKey\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\",\n    \"permission\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostPermissionsAddUserMCPTool creates the MCP Tool instance for PostPermissionsAddUser
func NewPostPermissionsAddUserMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostPermissionsAddUser",
		"Add permission to a user. - Add permission to a user. This service defaults to global permissions, but can be limited to project permissions by providing project id or project key. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the specified project",
		[]byte(PostPermissionsAddUserInputSchema),
	)
}

// PostPermissionsAddUserHandler is the handler function for the PostPermissionsAddUser tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostPermissionsAddUserHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/permissions/add_user", args, []string{}, contentType, "PostPermissionsAddUser")
}
