// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUserTokensGenerate tool
const PostUserTokensGenerateInputSchema = "{\n  \"properties\": {\n    \"expirationDate\": {\n      \"description\": \"The expiration date of the token being generated, in ISO 8601 format (YYYY-MM-DD). If not set, default to no expiration.\",\n      \"type\": \"string\"\n    },\n    \"login\": {\n      \"description\": \"User login. If not set, the token is generated for the authenticated user.\",\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"Token name\",\n      \"maxLength\": 100,\n      \"type\": \"string\"\n    },\n    \"projectKey\": {\n      \"description\": \"The key of the only project that can be analyzed by the PROJECT_ANALYSIS_TOKEN being generated.\",\n      \"type\": \"string\"\n    },\n    \"type\": {\n      \"description\": \"Token Type. If this parameters is set to PROJECT_ANALYSIS_TOKEN, it is necessary to provide the projectKey parameter too.\",\n      \"enum\": [\n        \"USER_TOKEN\",\n        \"GLOBAL_ANALYSIS_TOKEN\",\n        \"PROJECT_ANALYSIS_TOKEN\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostUserTokensGenerate tool (Status: 200, Content-Type: application/json)
const PostUserTokensGenerateResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostUserTokensGenerateMCPTool creates the MCP Tool instance for PostUserTokensGenerate
func NewPostUserTokensGenerateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUserTokensGenerate",
		"Generate a user access token. - Generate a user access token. Please keep your tokens secret. They enable to authenticate and analyze projects. It requires administration permissions to specify a 'login' and generate a token for another user. Otherwise, a token is generated for the current user.",
		[]byte(PostUserTokensGenerateInputSchema),
	)
}

// PostUserTokensGenerateHandler is the handler function for the PostUserTokensGenerate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUserTokensGenerateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/user_tokens/generate", args, []string{}, contentType, "PostUserTokensGenerate")
}
