// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsCreateGithub tool
const PostAlmSettingsCreateGithubInputSchema = "{\n  \"properties\": {\n    \"appId\": {\n      \"description\": \"GitHub App ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    },\n    \"clientId\": {\n      \"description\": \"GitHub App Client ID\",\n      \"maxLength\": 80,\n      \"type\": \"string\"\n    },\n    \"clientSecret\": {\n      \"description\": \"GitHub App Client Secret\",\n      \"maxLength\": 160,\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Unique key of the GitHub instance setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"privateKey\": {\n      \"description\": \"GitHub App private key\",\n      \"maxLength\": 2500,\n      \"type\": \"string\"\n    },\n    \"url\": {\n      \"description\": \"GitHub API URL\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"webhookSecret\": {\n      \"description\": \"GitHub App Webhook Secret\",\n      \"maxLength\": 160,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"appId\",\n    \"clientId\",\n    \"clientSecret\",\n    \"key\",\n    \"privateKey\",\n    \"url\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsCreateGithubMCPTool creates the MCP Tool instance for PostAlmSettingsCreateGithub
func NewPostAlmSettingsCreateGithubMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsCreateGithub",
		"Create GitHub instance Setting. - Create GitHub instance Setting. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsCreateGithubInputSchema),
	)
}

// PostAlmSettingsCreateGithubHandler is the handler function for the PostAlmSettingsCreateGithub tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsCreateGithubHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/create_github", args, []string{}, contentType, "PostAlmSettingsCreateGithub")
}
