// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsSetRegexpMode tool
const PostViewsSetRegexpModeInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Selects a branch in all matched projects, instead of using their main branches\",\n      \"type\": \"string\"\n    },\n    \"portfolio\": {\n      \"description\": \"Key of the portfolio or sub-portfolio to update\",\n      \"type\": \"string\"\n    },\n    \"regexp\": {\n      \"description\": \"A valid regexp with respect to the JDK's " + "\x60" + "" + "\x60" + "java.util.regex.Pattern" + "\x60" + "" + "\x60" + " class\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"portfolio\",\n    \"regexp\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsSetRegexpModeMCPTool creates the MCP Tool instance for PostViewsSetRegexpMode
func NewPostViewsSetRegexpModeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsSetRegexpMode",
		"Set the projects selection mode of a portfolio on regular expression. - Set the projects selection mode of a portfolio on regular expression. Requires 'Administrator' permission on the portfolio.",
		[]byte(PostViewsSetRegexpModeInputSchema),
	)
}

// PostViewsSetRegexpModeHandler is the handler function for the PostViewsSetRegexpMode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsSetRegexpModeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/set_regexp_mode", args, []string{}, contentType, "PostViewsSetRegexpMode")
}
