// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostHotspotsAssign tool
const PostHotspotsAssignInputSchema = "{\n  \"properties\": {\n    \"assignee\": {\n      \"description\": \"Login of the assignee with 'Browse' project permission\",\n      \"type\": \"string\"\n    },\n    \"comment\": {\n      \"description\": \"A comment provided with assign action\",\n      \"type\": \"string\"\n    },\n    \"hotspot\": {\n      \"description\": \"Hotspot key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"hotspot\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostHotspotsAssignMCPTool creates the MCP Tool instance for PostHotspotsAssign
func NewPostHotspotsAssignMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostHotspotsAssign",
		"Assign a hotspot to an active user. - Assign a hotspot to an active user. Requires authentication and Browse permission on project",
		[]byte(PostHotspotsAssignInputSchema),
	)
}

// PostHotspotsAssignHandler is the handler function for the PostHotspotsAssign tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostHotspotsAssignHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/hotspots/assign", args, []string{}, contentType, "PostHotspotsAssign")
}
