// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostFavoritesRemove tool
const PostFavoritesRemoveInputSchema = "{\n  \"properties\": {\n    \"component\": {\n      \"description\": \"Component key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"component\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostFavoritesRemoveMCPTool creates the MCP Tool instance for PostFavoritesRemove
func NewPostFavoritesRemoveMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostFavoritesRemove",
		"Remove a component (project, portfolio, application etc.) as favorite for the authenticated user. - Remove a component (project, portfolio, application etc.) as favorite for the authenticated user. Requires authentication.",
		[]byte(PostFavoritesRemoveInputSchema),
	)
}

// PostFavoritesRemoveHandler is the handler function for the PostFavoritesRemove tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostFavoritesRemoveHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/favorites/remove", args, []string{}, contentType, "PostFavoritesRemove")
}
