// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmIntegrationsImportGithubProject tool
const PostAlmIntegrationsImportGithubProjectInputSchema = "{\n  \"properties\": {\n    \"almSetting\": {\n      \"description\": \"DevOps Platform configuration key. This parameter is optional if you have only one GitHub integration.\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"newCodeDefinitionType\": {\n      \"description\": \"Project New Code Definition Type New code definitions of the following types are allowed: - PREVIOUS_VERSION - NUMBER_OF_DAYS - REFERENCE_BRANCH - will default to the main branch.\",\n      \"type\": \"string\"\n    },\n    \"newCodeDefinitionValue\": {\n      \"description\": \"Project New Code Definition Value For each new code definition type, a different value is expected: - no value, when the new code definition type is PREVIOUS_VERSION and REFERENCE_BRANCH - a number between 1 and 90, when the new code definition type is NUMBER_OF_DAYS\",\n      \"type\": \"string\"\n    },\n    \"repositoryKey\": {\n      \"description\": \"GitHub repository key (organization/repoSlug\",\n      \"maxLength\": 256,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryKey\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmIntegrationsImportGithubProjectMCPTool creates the MCP Tool instance for PostAlmIntegrationsImportGithubProject
func NewPostAlmIntegrationsImportGithubProjectMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmIntegrationsImportGithubProject",
		"Create a SonarQube project with the information from the provided GitHub repository. - Create a SonarQube project with the information from the provided GitHub repository. Autoconfigure pull request decoration mechanism. If Automatic Provisioning is enable for GitHub, it will also synchronize permissions from the repository. Requires the 'Create Projects' permission",
		[]byte(PostAlmIntegrationsImportGithubProjectInputSchema),
	)
}

// PostAlmIntegrationsImportGithubProjectHandler is the handler function for the PostAlmIntegrationsImportGithubProject tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmIntegrationsImportGithubProjectHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_integrations/import_github_project", args, []string{}, contentType, "PostAlmIntegrationsImportGithubProject")
}
