// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostSystemMigrateDb tool
const PostSystemMigrateDbInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the PostSystemMigrateDb tool (Status: 200, Content-Type: application/json)
const PostSystemMigrateDbResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostSystemMigrateDbMCPTool creates the MCP Tool instance for PostSystemMigrateDb
func NewPostSystemMigrateDbMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostSystemMigrateDb",
		"Migrate the database to match the current version of SonarQube. - Migrate the database to match the current version of SonarQube. Sending a POST request to this URL starts the DB migration. It is strongly advised to make a database backup before invoking this WS. State values are: - NO_MIGRATION: DB is up to date with current version of SonarQube. - NOT_SUPPORTED: Migration is not supported on embedded databases. - MIGRATION_RUNNING: DB migration is under go. - MIGRATION_SUCCEEDED: DB migration has run and has been successful. - MIGRATION_FAILED: DB migration has run and failed. SonarQube must be restarted in order to retry a DB migration (optionally after DB has been restored from backup). - MIGRATION_REQUIRED: DB migration is required.",
		[]byte(PostSystemMigrateDbInputSchema),
	)
}

// PostSystemMigrateDbHandler is the handler function for the PostSystemMigrateDb tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostSystemMigrateDbHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/system/migrate_db", args, []string{}, contentType, "PostSystemMigrateDb")
}
