// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostHotspotsChangeStatus tool
const PostHotspotsChangeStatusInputSchema = "{\n  \"properties\": {\n    \"comment\": {\n      \"description\": \"Comment text.\",\n      \"type\": \"string\"\n    },\n    \"hotspot\": {\n      \"description\": \"Key of the Security Hotspot\",\n      \"type\": \"string\"\n    },\n    \"resolution\": {\n      \"description\": \"Resolution of the Security Hotspot when new status is REVIEWED, otherwise must not be set.\",\n      \"enum\": [\n        \"FIXED\",\n        \"SAFE\",\n        \"ACKNOWLEDGED\"\n      ],\n      \"type\": \"string\"\n    },\n    \"status\": {\n      \"description\": \"New status of the Security Hotspot.\",\n      \"enum\": [\n        \"TO_REVIEW\",\n        \"REVIEWED\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"hotspot\",\n    \"status\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostHotspotsChangeStatusMCPTool creates the MCP Tool instance for PostHotspotsChangeStatus
func NewPostHotspotsChangeStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostHotspotsChangeStatus",
		"Change the status of a Security Hotpot. - Change the status of a Security Hotpot. Requires the 'Administer Security Hotspot' permission.",
		[]byte(PostHotspotsChangeStatusInputSchema),
	)
}

// PostHotspotsChangeStatusHandler is the handler function for the PostHotspotsChangeStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostHotspotsChangeStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/hotspots/change_status", args, []string{}, contentType, "PostHotspotsChangeStatus")
}
