// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostNewCodePeriodsUnset tool
const PostNewCodePeriodsUnsetInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewPostNewCodePeriodsUnsetMCPTool creates the MCP Tool instance for PostNewCodePeriodsUnset
func NewPostNewCodePeriodsUnsetMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostNewCodePeriodsUnset",
		"Unsets the new code definition for a branch, project or global. - Unsets the new code definition for a branch, project or global. It requires the inherited New Code Definition to be compatible with the Clean as You Code methodology, and one of the following permissions: - 'Administer System' to change the global setting - 'Administer' rights for a specified component",
		[]byte(PostNewCodePeriodsUnsetInputSchema),
	)
}

// PostNewCodePeriodsUnsetHandler is the handler function for the PostNewCodePeriodsUnset tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostNewCodePeriodsUnsetHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/new_code_periods/unset", args, []string{}, contentType, "PostNewCodePeriodsUnset")
}
