// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostNewCodePeriodsSet tool
const PostNewCodePeriodsSetInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"type\": {\n      \"description\": \"Type New code definitions of the following types are allowed: - SPECIFIC_ANALYSIS - can be set at branch level only - PREVIOUS_VERSION - can be set at any level (global, project, branch) - NUMBER_OF_DAYS - can be set at any level (global, project, branch) - REFERENCE_BRANCH - can only be set for projects and branches\",\n      \"type\": \"string\"\n    },\n    \"value\": {\n      \"description\": \"Value For each type, a different value is expected: - the uuid of an analysis, when type is SPECIFIC_ANALYSIS - no value, when type is PREVIOUS_VERSION - a number between 1 and 90, when type is NUMBER_OF_DAYS - a string, when type is REFERENCE_BRANCH\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"type\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostNewCodePeriodsSetMCPTool creates the MCP Tool instance for PostNewCodePeriodsSet
func NewPostNewCodePeriodsSetMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostNewCodePeriodsSet",
		"Updates the new code definition on different levels:. - Updates the new code definition on different levels: - Not providing a project key and a branch key will update the default value at global level. Existing projects or branches having a specific new code definition will not be impacted - Project key must be provided to update the value for a project - Both project and branch keys must be provided to update the value for a branchRequires one of the following permissions: - 'Administer System' to change the global setting - 'Administer' rights on the specified project to change the project setting",
		[]byte(PostNewCodePeriodsSetInputSchema),
	)
}

// PostNewCodePeriodsSetHandler is the handler function for the PostNewCodePeriodsSet tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostNewCodePeriodsSetHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/new_code_periods/set", args, []string{}, contentType, "PostNewCodePeriodsSet")
}
