// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectsUpdateVisibility tool
const PostProjectsUpdateVisibilityInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project, application or portfolio key\",\n      \"type\": \"string\"\n    },\n    \"visibility\": {\n      \"description\": \"New visibility\",\n      \"enum\": [\n        \"private\",\n        \"public\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\",\n    \"visibility\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectsUpdateVisibilityMCPTool creates the MCP Tool instance for PostProjectsUpdateVisibility
func NewPostProjectsUpdateVisibilityMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectsUpdateVisibility",
		"Updates visibility of a project, application or a portfolio. - Updates visibility of a project, application or a portfolio. Requires 'Project administer' permission on the specified entity",
		[]byte(PostProjectsUpdateVisibilityInputSchema),
	)
}

// PostProjectsUpdateVisibilityHandler is the handler function for the PostProjectsUpdateVisibility tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectsUpdateVisibilityHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/projects/update_visibility", args, []string{}, contentType, "PostProjectsUpdateVisibility")
}
