// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostSystemChangeLogLevel tool
const PostSystemChangeLogLevelInputSchema = "{\n  \"properties\": {\n    \"level\": {\n      \"description\": \"The new level. Be cautious: DEBUG, and even more TRACE, may have performance impacts.\",\n      \"enum\": [\n        \"TRACE\",\n        \"DEBUG\",\n        \"INFO\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"level\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostSystemChangeLogLevelMCPTool creates the MCP Tool instance for PostSystemChangeLogLevel
func NewPostSystemChangeLogLevelMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostSystemChangeLogLevel",
		"Temporarily changes level of logs. - Temporarily changes level of logs. New level is not persistent and is lost when restarting server. Requires system administration permission.",
		[]byte(PostSystemChangeLogLevelInputSchema),
	)
}

// PostSystemChangeLogLevelHandler is the handler function for the PostSystemChangeLogLevel tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostSystemChangeLogLevelHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/system/change_log_level", args, []string{}, contentType, "PostSystemChangeLogLevel")
}
