// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostQualitygatesDestroy tool
const PostQualitygatesDestroyInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"Name of the quality gate to delete\",\n      \"maxLength\": 100,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostQualitygatesDestroyMCPTool creates the MCP Tool instance for PostQualitygatesDestroy
func NewPostQualitygatesDestroyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostQualitygatesDestroy",
		"Delete a Quality Gate. - Delete a Quality Gate. Parameter 'name' must be specified. Requires the 'Administer Quality Gates' permission.",
		[]byte(PostQualitygatesDestroyInputSchema),
	)
}

// PostQualitygatesDestroyHandler is the handler function for the PostQualitygatesDestroy tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostQualitygatesDestroyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/qualitygates/destroy", args, []string{}, contentType, "PostQualitygatesDestroy")
}
