// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUsersUpdate tool
const PostUsersUpdateInputSchema = "{\n  \"properties\": {\n    \"email\": {\n      \"description\": \"User email\",\n      \"maxLength\": 100,\n      \"type\": \"string\"\n    },\n    \"login\": {\n      \"description\": \"User login\",\n      \"maxLength\": 255,\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"User name\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"scmAccount\": {\n      \"description\": \"SCM accounts. To set several values, the parameter must be called once for each value.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostUsersUpdate tool (Status: 200, Content-Type: application/json)
const PostUsersUpdateResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostUsersUpdateMCPTool creates the MCP Tool instance for PostUsersUpdate
func NewPostUsersUpdateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUsersUpdate",
		"Update a user. - Update a user. Requires Administer System permission",
		[]byte(PostUsersUpdateInputSchema),
	)
}

// PostUsersUpdateHandler is the handler function for the PostUsersUpdate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUsersUpdateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/users/update", args, []string{}, contentType, "PostUsersUpdate")
}
