// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectBranchesSetAutomaticDeletionProtection tool
const PostProjectBranchesSetAutomaticDeletionProtectionInputSchema = "{\n  \"properties\": {\n    \"branch\": {\n      \"description\": \"Branch key\",\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    },\n    \"value\": {\n      \"description\": \"Sets whether the branch should be protected from automatic deletion when it hasn't been analyzed for a set period of time.\",\n      \"enum\": [\n        \"true\",\n        \"false\",\n        \"yes\",\n        \"no\"\n      ],\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"branch\",\n    \"project\",\n    \"value\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectBranchesSetAutomaticDeletionProtectionMCPTool creates the MCP Tool instance for PostProjectBranchesSetAutomaticDeletionProtection
func NewPostProjectBranchesSetAutomaticDeletionProtectionMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectBranchesSetAutomaticDeletionProtection",
		"Protect a specific branch from automatic deletion. - Protect a specific branch from automatic deletion. Protection can't be disabled for the main branch. Requires 'Administer' permission on the specified project or application.",
		[]byte(PostProjectBranchesSetAutomaticDeletionProtectionInputSchema),
	)
}

// PostProjectBranchesSetAutomaticDeletionProtectionHandler is the handler function for the PostProjectBranchesSetAutomaticDeletionProtection tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectBranchesSetAutomaticDeletionProtectionHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/project_branches/set_automatic_deletion_protection", args, []string{}, contentType, "PostProjectBranchesSetAutomaticDeletionProtection")
}
