// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostPermissionsAddProjectCreatorToTemplate tool
const PostPermissionsAddProjectCreatorToTemplateInputSchema = "{\n  \"properties\": {\n    \"permission\": {\n      \"description\": \"Permission - Possible values for project permissions admin, codeviewer, issueadmin, securityhotspotadmin, architectureadmin, scan, user\",\n      \"enum\": [\n        \"admin\",\n        \"codeviewer\",\n        \"issueadmin\",\n        \"securityhotspotadmin\",\n        \"architectureadmin\",\n        \"scan\",\n        \"user\"\n      ],\n      \"type\": \"string\"\n    },\n    \"templateId\": {\n      \"description\": \"Template id\",\n      \"type\": \"string\"\n    },\n    \"templateName\": {\n      \"description\": \"Template name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"permission\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostPermissionsAddProjectCreatorToTemplateMCPTool creates the MCP Tool instance for PostPermissionsAddProjectCreatorToTemplate
func NewPostPermissionsAddProjectCreatorToTemplateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostPermissionsAddProjectCreatorToTemplate",
		"Add a project creator to a permission template. - Add a project creator to a permission template. Requires the following permission: 'Administer System'.",
		[]byte(PostPermissionsAddProjectCreatorToTemplateInputSchema),
	)
}

// PostPermissionsAddProjectCreatorToTemplateHandler is the handler function for the PostPermissionsAddProjectCreatorToTemplate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostPermissionsAddProjectCreatorToTemplateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/permissions/add_project_creator_to_template", args, []string{}, contentType, "PostPermissionsAddProjectCreatorToTemplate")
}
