// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsSetManualMode tool
const PostViewsSetManualModeInputSchema = "{\n  \"properties\": {\n    \"portfolio\": {\n      \"description\": \"Key of the portfolio or sub-portfolio to update\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"portfolio\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsSetManualModeMCPTool creates the MCP Tool instance for PostViewsSetManualMode
func NewPostViewsSetManualModeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsSetManualMode",
		"Set the projects selection mode of a portfolio on manual selection. - Set the projects selection mode of a portfolio on manual selection. In order to add project, please use api/view/add_project. Requires 'Administrator' permission on the portfolio.",
		[]byte(PostViewsSetManualModeInputSchema),
	)
}

// PostViewsSetManualModeHandler is the handler function for the PostViewsSetManualMode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsSetManualModeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/set_manual_mode", args, []string{}, contentType, "PostViewsSetManualMode")
}
