// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostHotspotsEditComment tool
const PostHotspotsEditCommentInputSchema = "{\n  \"properties\": {\n    \"comment\": {\n      \"description\": \"Comment key\",\n      \"type\": \"string\"\n    },\n    \"text\": {\n      \"description\": \"Comment text\",\n      \"maxLength\": 1000,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"comment\",\n    \"text\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the PostHotspotsEditComment tool (Status: 200, Content-Type: application/json)
const PostHotspotsEditCommentResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful response\n\n## Response Structure\n\n- Response data (see SonarQube API documentation for schema details) (Type: object):\n"

// NewPostHotspotsEditCommentMCPTool creates the MCP Tool instance for PostHotspotsEditComment
func NewPostHotspotsEditCommentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostHotspotsEditComment",
		"Edit a comment. - Edit a comment. Requires authentication and the following permission: 'Browse' on the project of the specified hotspot.",
		[]byte(PostHotspotsEditCommentInputSchema),
	)
}

// PostHotspotsEditCommentHandler is the handler function for the PostHotspotsEditComment tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostHotspotsEditCommentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/hotspots/edit_comment", args, []string{}, contentType, "PostHotspotsEditComment")
}
