// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostCeCancelAll tool
const PostCeCancelAllInputSchema = "{\n  \"type\": \"object\"\n}"

// NewPostCeCancelAllMCPTool creates the MCP Tool instance for PostCeCancelAll
func NewPostCeCancelAllMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostCeCancelAll",
		"Cancels all pending tasks. - Cancels all pending tasks. Requires system administration permission. In-progress tasks are not canceled.",
		[]byte(PostCeCancelAllInputSchema),
	)
}

// PostCeCancelAllHandler is the handler function for the PostCeCancelAll tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostCeCancelAllHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/ce/cancel_all", args, []string{}, contentType, "PostCeCancelAll")
}
