// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostViewsUpdate tool
const PostViewsUpdateInputSchema = "{\n  \"properties\": {\n    \"description\": {\n      \"description\": \"New description for the portfolio\",\n      \"maxLength\": 256,\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Key of the portfolio to update\",\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"New name for the portfolio\",\n      \"maxLength\": 256,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\",\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostViewsUpdateMCPTool creates the MCP Tool instance for PostViewsUpdate
func NewPostViewsUpdateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostViewsUpdate",
		"Update a portfolio. - Update a portfolio. Requires 'Administrator' permission on the portfolio.",
		[]byte(PostViewsUpdateInputSchema),
	)
}

// PostViewsUpdateHandler is the handler function for the PostViewsUpdate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostViewsUpdateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/views/update", args, []string{}, contentType, "PostViewsUpdate")
}
