// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostUsersChangePassword tool
const PostUsersChangePasswordInputSchema = "{\n  \"properties\": {\n    \"login\": {\n      \"description\": \"User login\",\n      \"type\": \"string\"\n    },\n    \"password\": {\n      \"description\": \"The password needs to fulfill the following requirements: at least 12 characters and contain at least one uppercase character, one lowercase character, one digit and one special character.\",\n      \"minLength\": 12,\n      \"type\": \"string\"\n    },\n    \"previousPassword\": {\n      \"description\": \"Previous password. Required when changing one's own password.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"login\",\n    \"password\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostUsersChangePasswordMCPTool creates the MCP Tool instance for PostUsersChangePassword
func NewPostUsersChangePasswordMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostUsersChangePassword",
		"Update a user's password. - Update a user's password. Authenticated users can change their own password, provided that the account is not linked to an external authentication system. Administer System permission is required to change another user's password.",
		[]byte(PostUsersChangePasswordInputSchema),
	)
}

// PostUsersChangePasswordHandler is the handler function for the PostUsersChangePassword tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostUsersChangePasswordHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/users/change_password", args, []string{}, contentType, "PostUsersChangePassword")
}
