// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectsDelete tool
const PostProjectsDeleteInputSchema = "{\n  \"properties\": {\n    \"project\": {\n      \"description\": \"Project key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"project\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectsDeleteMCPTool creates the MCP Tool instance for PostProjectsDelete
func NewPostProjectsDeleteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectsDelete",
		"Delete a project. - Delete a project. Requires 'Administer System' permission or 'Administer' permission on the project.",
		[]byte(PostProjectsDeleteInputSchema),
	)
}

// PostProjectsDeleteHandler is the handler function for the PostProjectsDelete tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectsDeleteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/projects/delete", args, []string{}, contentType, "PostProjectsDelete")
}
