// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostPermissionsAddGroupToTemplate tool
const PostPermissionsAddGroupToTemplateInputSchema = "{\n  \"properties\": {\n    \"groupName\": {\n      \"description\": \"Group name or 'anyone' (case insensitive)\",\n      \"type\": \"string\"\n    },\n    \"permission\": {\n      \"description\": \"Permission - Possible values for project permissions admin, codeviewer, issueadmin, securityhotspotadmin, architectureadmin, scan, user\",\n      \"enum\": [\n        \"admin\",\n        \"codeviewer\",\n        \"issueadmin\",\n        \"securityhotspotadmin\",\n        \"architectureadmin\",\n        \"scan\",\n        \"user\"\n      ],\n      \"type\": \"string\"\n    },\n    \"templateId\": {\n      \"description\": \"Template id\",\n      \"type\": \"string\"\n    },\n    \"templateName\": {\n      \"description\": \"Template name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"groupName\",\n    \"permission\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostPermissionsAddGroupToTemplateMCPTool creates the MCP Tool instance for PostPermissionsAddGroupToTemplate
func NewPostPermissionsAddGroupToTemplateMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostPermissionsAddGroupToTemplate",
		"Add a group to a permission template. - Add a group to a permission template. The group name must be provided. Requires the following permission: 'Administer System'.",
		[]byte(PostPermissionsAddGroupToTemplateInputSchema),
	)
}

// PostPermissionsAddGroupToTemplateHandler is the handler function for the PostPermissionsAddGroupToTemplate tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostPermissionsAddGroupToTemplateHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/permissions/add_group_to_template", args, []string{}, contentType, "PostPermissionsAddGroupToTemplate")
}
