// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostAlmSettingsCreateBitbucketcloud tool
const PostAlmSettingsCreateBitbucketcloudInputSchema = "{\n  \"properties\": {\n    \"clientId\": {\n      \"description\": \"Bitbucket Cloud Client ID\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"clientSecret\": {\n      \"description\": \"Bitbucket Cloud Client Secret\",\n      \"maxLength\": 2000,\n      \"type\": \"string\"\n    },\n    \"key\": {\n      \"description\": \"Unique key of the Bitbucket Cloud setting\",\n      \"maxLength\": 200,\n      \"type\": \"string\"\n    },\n    \"workspace\": {\n      \"description\": \"Bitbucket Cloud workspace ID\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"clientId\",\n    \"clientSecret\",\n    \"key\",\n    \"workspace\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostAlmSettingsCreateBitbucketcloudMCPTool creates the MCP Tool instance for PostAlmSettingsCreateBitbucketcloud
func NewPostAlmSettingsCreateBitbucketcloudMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostAlmSettingsCreateBitbucketcloud",
		"Configure a new instance of Bitbucket Cloud. - Configure a new instance of Bitbucket Cloud. Requires the 'Administer System' permission",
		[]byte(PostAlmSettingsCreateBitbucketcloudInputSchema),
	)
}

// PostAlmSettingsCreateBitbucketcloudHandler is the handler function for the PostAlmSettingsCreateBitbucketcloud tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostAlmSettingsCreateBitbucketcloudHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/alm_settings/create_bitbucketcloud", args, []string{}, contentType, "PostAlmSettingsCreateBitbucketcloud")
}
