// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostHotspotsDeleteComment tool
const PostHotspotsDeleteCommentInputSchema = "{\n  \"properties\": {\n    \"comment\": {\n      \"description\": \"Comment key.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"comment\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostHotspotsDeleteCommentMCPTool creates the MCP Tool instance for PostHotspotsDeleteComment
func NewPostHotspotsDeleteCommentMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostHotspotsDeleteComment",
		"Delete comment from Security Hotpot. - Delete comment from Security Hotpot. Requires authentication and the following permission: 'Browse' on the project of the specified Security Hotspot.",
		[]byte(PostHotspotsDeleteCommentInputSchema),
	)
}

// PostHotspotsDeleteCommentHandler is the handler function for the PostHotspotsDeleteComment tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostHotspotsDeleteCommentHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/hotspots/delete_comment", args, []string{}, contentType, "PostHotspotsDeleteComment")
}
