// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostQualityprofilesRename tool
const PostQualityprofilesRenameInputSchema = "{\n  \"properties\": {\n    \"key\": {\n      \"description\": \"Quality profile key\",\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"New quality profile name\",\n      \"maxLength\": 100,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"key\",\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostQualityprofilesRenameMCPTool creates the MCP Tool instance for PostQualityprofilesRename
func NewPostQualityprofilesRenameMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostQualityprofilesRename",
		"Rename a quality profile. - Rename a quality profile. Requires one of the following permissions: - 'Administer Quality Profiles' - Edit right on the specified quality profile",
		[]byte(PostQualityprofilesRenameInputSchema),
	)
}

// PostQualityprofilesRenameHandler is the handler function for the PostQualityprofilesRename tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostQualityprofilesRenameHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/qualityprofiles/rename", args, []string{}, contentType, "PostQualityprofilesRename")
}
