// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostApplicationsUpdateBranch tool
const PostApplicationsUpdateBranchInputSchema = "{\n  \"properties\": {\n    \"application\": {\n      \"description\": \"Application key\",\n      \"type\": \"string\"\n    },\n    \"branch\": {\n      \"description\": \"Branch name\",\n      \"type\": \"string\"\n    },\n    \"name\": {\n      \"description\": \"New branch name\",\n      \"maxLength\": 255,\n      \"type\": \"string\"\n    },\n    \"project\": {\n      \"description\": \"Project keys. To set several values, the parameter must be called once for each value.\",\n      \"type\": \"string\"\n    },\n    \"projectBranch\": {\n      \"description\": \"Project branches. To set main branch, provide an empty value. To set several values, the parameter must be called once for each value.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"application\",\n    \"branch\",\n    \"name\",\n    \"project\",\n    \"projectBranch\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostApplicationsUpdateBranchMCPTool creates the MCP Tool instance for PostApplicationsUpdateBranch
func NewPostApplicationsUpdateBranchMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostApplicationsUpdateBranch",
		"Update a branch on a given application. - Update a branch on a given application. Requires 'Administrator' permission on the application and 'Browse' permission on its child projects",
		[]byte(PostApplicationsUpdateBranchInputSchema),
	)
}

// PostApplicationsUpdateBranchHandler is the handler function for the PostApplicationsUpdateBranch tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostApplicationsUpdateBranchHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/applications/update_branch", args, []string{}, contentType, "PostApplicationsUpdateBranch")
}
