// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"sonarqube-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the PostProjectAnalysesDelete tool
const PostProjectAnalysesDeleteInputSchema = "{\n  \"properties\": {\n    \"analysis\": {\n      \"description\": \"Analysis key\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"analysis\"\n  ],\n  \"type\": \"object\"\n}"

// NewPostProjectAnalysesDeleteMCPTool creates the MCP Tool instance for PostProjectAnalysesDelete
func NewPostProjectAnalysesDeleteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"PostProjectAnalysesDelete",
		"Delete a project analysis. - Delete a project analysis. Requires one of the following permissions: - 'Administer System' - 'Administer' rights on the project of the specified analysis",
		[]byte(PostProjectAnalysesDeleteInputSchema),
	)
}

// PostProjectAnalysesDeleteHandler is the handler function for the PostProjectAnalysesDelete tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func PostProjectAnalysesDeleteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/api/project_analyses/delete", args, []string{}, contentType, "PostProjectAnalysesDelete")
}
