// Code generated by https://github.com/flowgent-labs/mcpfather

package mcputils

import (
	"bytes"
	"context"
	"crypto/sha1"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/mark3labs/mcp-go/mcp"

	"github.com/google/uuid"
)

type contextKey string

const HTTPHeadersContextKey contextKey = "mcp-http-headers"
const HTTPRequestContextKey contextKey = "mcp-http-request"

const binaryDownloadKind = "dl.tfs.mcpfather.com/v1"
const tfsInProgressSuffix = ".inprogress"

const defaultTFSCleanJobTTL = 5 * time.Minute
const tfsCleanJobInterval = 10 * time.Second

type tfsFileMeta struct {
	Name        string
	ContentType string
}

var tfsDownloadMeta sync.Map

// WithHTTPHeaders stores HTTP headers in the context for forwarding to upstream.
func WithHTTPHeaders(ctx context.Context, headers http.Header) context.Context {
	return context.WithValue(ctx, HTTPHeadersContextKey, headers)
}

// GetHTTPHeaders retrieves HTTP headers from the context.
func GetHTTPHeaders(ctx context.Context) http.Header {
	if h, ok := ctx.Value(HTTPHeadersContextKey).(http.Header); ok {
		return h
	}
	return nil
}

// WithHTTPRequest stores the inbound HTTP request in the context for helpers
// that need to derive public URLs from the MCP client's request.
func WithHTTPRequest(ctx context.Context, r *http.Request) context.Context {
	return context.WithValue(ctx, HTTPRequestContextKey, r)
}

func GetHTTPRequest(ctx context.Context) *http.Request {
	if r, ok := ctx.Value(HTTPRequestContextKey).(*http.Request); ok {
		return r
	}
	return nil
}

// ForwardRequest sends an HTTP request to the upstream endpoint and returns the response.
// All HTTP headers stored in ctx are forwarded to the upstream service.
func ForwardRequest(ctx context.Context, upstreamBase string, method string, path string, args map[string]interface{}, pathKeys []string, contentType string) (*http.Response, error) {
	// Build URL
	upstreamURL := strings.TrimSuffix(upstreamBase, "/") + path

	// Replace path parameters and collect query parameters
	query := url.Values{}
	for key, val := range args {
		// "body" is reserved for request body, never goes in query
		if key == "body" {
			continue
		}
		placeholder := "{" + key + "}"
		if strings.Contains(upstreamURL, placeholder) {
			upstreamURL = strings.ReplaceAll(upstreamURL, placeholder, valueToString(val))
		} else {
			if strVal, ok := val.(string); ok {
				query.Set(key, strVal)
			} else {
				query.Set(key, valueToString(val))
			}
		}
	}
	if len(query) > 0 {
		upstreamURL += "?" + query.Encode()
	}

	// Build request body
	var bodyReader io.Reader
	var bodyBytes []byte
	var err error
	if method != "GET" && method != "HEAD" {
		var bodyData interface{}
		if bodyArg, ok := args["body"]; ok {
			bodyData = bodyArg
		} else {
			bodyData = buildJSONBody(args, pathKeys)
		}
		bodyBytes, err = marshalJSONNoSci(bodyData)
		if err != nil {
			return nil, fmt.Errorf("failed to marshal request body: %w", err)
		}
		bodyReader = strings.NewReader(string(bodyBytes))
	}

	req, err := http.NewRequestWithContext(ctx, method, upstreamURL, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("failed to create upstream request: %w", err)
	}

	if contentType != "" {
		req.Header.Set("Content-Type", contentType)
	}

	// Forward all headers from context (skip hop-by-hop and MCP-specific)
	if forwarded := GetHTTPHeaders(ctx); forwarded != nil {
		for key, values := range forwarded {
			lowerKey := strings.ToLower(key)
			if lowerKey == "host" || lowerKey == "connection" || lowerKey == "keep-alive" || lowerKey == "proxy-authenticate" || lowerKey == "proxy-authorization" || lowerKey == "te" || lowerKey == "trailer" || lowerKey == "transfer-encoding" || lowerKey == "upgrade" || lowerKey == "authorization" || lowerKey == "cookie" || lowerKey == "content-length" || lowerKey == "mcp-session-id" || lowerKey == "content-type" {
				continue
			}
			for _, v := range values {
				req.Header.Add(key, v)
			}
		}
	}

	// The client's own Authorization header is deliberately excluded above
	// (see "authorization" in the skip list) and never falls through here.
	// Per the MCP Authorization spec's Token Passthrough Prohibition, a
	// token issued for this MCP server (validated by the server resource
	// server layer, see resource_server.go) MUST NOT be forwarded as-is to
	// upstream APIs it was never issued for. The server always uses its own
	// backend credential instead.
	if token := GetUpstreamToken(); token != "" {
		req.Header.Set("Authorization", FormatAuthorizationHeader(token))
	}

	// Attach upstream cookie from config (for session-based auth like JSESSIONID)
	if cookie := GetUpstreamCookie(); cookie != "" {
		req.Header.Set("Cookie", cookie)
	}

	// Forward MCP session ID when enable_mcp_session_forward is configured.
	if cfg := GetConfig(); cfg != nil && cfg.Upstream["default"].EnableMCPSessionForward {
		if sid := GetSessionID(ctx); sid != "" {
			req.Header.Set("X-MCP-Session-ID", sid)
		}
	}

	// Forward validated client token claims when enable_client_token_claim_forward
	// is configured (default: true). These are extracted from the frontend JWT
	// by the resource server layer — never from the inbound Authorization header.
	if cfg := GetConfig(); cfg != nil && cfg.Server.Auth.OIDC.EnableClientTokenClaimForward {
		if sub := GetClientTokenSub(ctx); sub != "" {
			req.Header.Set("X-MCP-Client-Token-Sub", sub)
		}
		if email := GetClientTokenEmail(ctx); email != "" {
			req.Header.Set("X-MCP-Client-Token-Email", email)
		}
		for _, claim := range cfg.Server.Auth.OIDC.AdditionalClientTokenClaimForward {
			if v := GetClientTokenClaim(ctx, claim); v != "" {
				req.Header.Set("X-MCP-Client-Token-"+HeaderizeClaim(claim), v)
			}
		}
	}

	// Log outgoing request with final headers
	LogRequest(method, upstreamURL, query, req.Header, bodyBytes)

	// Inject W3C trace context for distributed tracing
	InjectTraceContext(ctx, req.Header)

	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
	return client.Do(req)
}

// FormatAuthorizationHeader normalizes a token for use in an HTTP Authorization header.
// If the token already has a recognized prefix (Bearer or Basic, case-insensitive),
// it is returned unchanged. Otherwise, "Bearer " is prepended.
func FormatAuthorizationHeader(token string) string {
	token = strings.TrimSpace(token)
	if token == "" {
		return token
	}
	lower := strings.ToLower(token)
	if strings.HasPrefix(lower, "bearer ") || strings.HasPrefix(lower, "basic ") {
		return token
	}
	return "Bearer " + token
}

// NamedUpstreamHTTPClient implements pipeline.HTTPClient for extra_upstream endpoints.
type NamedUpstreamHTTPClient struct{}

func (c *NamedUpstreamHTTPClient) Call(ctx context.Context, upstream, method, path string, queryParams, headers map[string]string, body interface{}) (int, []byte, error) {
	endpoint := GetNamedUpstreamEndpoint(upstream)
	if endpoint == "" {
		return 0, nil, fmt.Errorf("extra_upstream %q not found in config", upstream)
	}

	fullURL := strings.TrimSuffix(endpoint, "/") + path
	if len(queryParams) > 0 {
		q := url.Values{}
		for k, v := range queryParams {
			q.Set(k, v)
		}
		fullURL += "?" + q.Encode()
	}

	var bodyReader io.Reader
	var bodyBytes []byte
	if body != nil && method != "GET" && method != "HEAD" {
		var err error
		bodyBytes, err = marshalJSONNoSci(body)
		if err != nil {
			return 0, nil, fmt.Errorf("failed to marshal request body: %w", err)
		}
		bodyReader = strings.NewReader(string(bodyBytes))
	}

	req, err := http.NewRequestWithContext(ctx, method, fullURL, bodyReader)
	if err != nil {
		return 0, nil, fmt.Errorf("failed to create request: %w", err)
	}

	if bodyReader != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	for k, v := range headers {
		req.Header.Set(k, v)
	}

	if forwarded := GetHTTPHeaders(ctx); forwarded != nil {
		for key, values := range forwarded {
			lowerKey := strings.ToLower(key)
			if lowerKey == "host" || lowerKey == "connection" || lowerKey == "keep-alive" ||
				lowerKey == "proxy-authenticate" || lowerKey == "proxy-authorization" ||
				lowerKey == "te" || lowerKey == "trailer" || lowerKey == "transfer-encoding" ||
				lowerKey == "upgrade" || lowerKey == "authorization" || lowerKey == "cookie" ||
				lowerKey == "content-length" || lowerKey == "mcp-session-id" || lowerKey == "content-type" {
				continue
			}
			for _, v := range values {
				req.Header.Add(key, v)
			}
		}
	}

	if token := GetNamedUpstreamToken(upstream); token != "" {
		req.Header.Set("Authorization", FormatAuthorizationHeader(token))
	}
	if cookie := GetNamedUpstreamCookie(upstream); cookie != "" {
		req.Header.Set("Cookie", cookie)
	}
	if IsNamedUpstreamSessionForwardEnabled(upstream) {
		if sid := GetSessionID(ctx); sid != "" {
			req.Header.Set("X-MCP-Session-ID", sid)
		}
	}
	if cfg := GetConfig(); cfg != nil && cfg.Server.Auth.OIDC.EnableClientTokenClaimForward {
		if sub := GetClientTokenSub(ctx); sub != "" {
			req.Header.Set("X-MCP-Client-Token-Sub", sub)
		}
		if email := GetClientTokenEmail(ctx); email != "" {
			req.Header.Set("X-MCP-Client-Token-Email", email)
		}
		for _, claim := range cfg.Server.Auth.OIDC.AdditionalClientTokenClaimForward {
			if v := GetClientTokenClaim(ctx, claim); v != "" {
				req.Header.Set("X-MCP-Client-Token-"+HeaderizeClaim(claim), v)
			}
		}
	}

	InjectTraceContext(ctx, req.Header)
	LogRequest(method, fullURL, url.Values{}, req.Header, bodyBytes)

	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
	resp, err := client.Do(req)
	if err != nil {
		return 0, nil, fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return 0, nil, fmt.Errorf("failed to read response: %w", err)
	}

	return resp.StatusCode, respBody, nil
}

// valueToString converts an interface{} to a string suitable for URLs and
// query parameters. It handles float64 values (from JSON unmarshalling)
// without scientific notation, which would break integer path parameters.
func valueToString(val interface{}) string {
	switch v := val.(type) {
	case float64:
		return strconv.FormatFloat(v, 'f', -1, 64)
	case float32:
		return strconv.FormatFloat(float64(v), 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", val)
	}
}

// buildJSONBody creates a map of args that should be included in the JSON body
// (i.e., args that are not path params or query params).
func buildJSONBody(args map[string]interface{}, pathAndQueryKeys []string) map[string]interface{} {
	skip := make(map[string]bool, len(pathAndQueryKeys))
	for _, k := range pathAndQueryKeys {
		skip[k] = true
	}
	body := make(map[string]interface{}, len(args))
	for k, v := range args {
		if !skip[k] {
			body[k] = v
		}
	}
	return body
}

// ParamsParser provides a generic way to parse MCP tool arguments into typed structs.
func ParamsParser[T any](args map[string]interface{}) (*T, error) {
	jsonData, err := marshalJSONNoSci(args)
	if err != nil {
		return nil, fmt.Errorf("failed to process arguments: %w", err)
	}

	var typedArgs T
	if err := json.Unmarshal(jsonData, &typedArgs); err != nil {
		return nil, fmt.Errorf("invalid argument structure: %w", err)
	}

	return &typedArgs, nil
}

// HeaderizeClaim converts a snake_case claim name to an HTTP header suffix.
// e.g. "given_name" → "Given-Name", "preferred_username" → "Preferred-Username".
func HeaderizeClaim(claim string) string {
	parts := strings.Split(claim, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "-")
}

// marshalJSONNoSci marshals data to JSON without scientific notation for
// floating point / integer values (which may come from JSON
// unmarshalling as float64). It recursively sanitises maps and slices.
func marshalJSONNoSci(v interface{}) ([]byte, error) {
	return json.Marshal(sanitizeForJSON(v))
}

// sanitizeForJSON recursively replaces float64/float32 values with
// json.RawMessage containing the decimal representation of the number.
// This prevents json.Marshal from emitting scientific notation.
func sanitizeForJSON(v interface{}) interface{} {
	switch val := v.(type) {
	case float64:
		return json.RawMessage(strconv.FormatFloat(val, 'f', -1, 64))
	case float32:
		return json.RawMessage(strconv.FormatFloat(float64(val), 'f', -1, 32))
	case []interface{}:
		out := make([]interface{}, len(val))
		for i, item := range val {
			out[i] = sanitizeForJSON(item)
		}
		return out
	case map[string]interface{}:
		out := make(map[string]interface{}, len(val))
		for k, item := range val {
			out[k] = sanitizeForJSON(item)
		}
		return out
	}
	return v
}

// IsBinaryContentType checks whether a Content-Type indicates binary data.
// The logic is inverted: instead of maintaining a whitelist of binary types,
// we define what is TEXT and treat everything else as binary.
func IsBinaryContentType(ct string) bool {
	ct = strings.TrimSpace(strings.ToLower(ct))
	mediaType, _, _ := mime.ParseMediaType(ct)
	if mediaType == "" {
		return true // unknown content-type, treat as binary to be safe
	}

	if strings.HasPrefix(mediaType, "text/") {
		return false
	}
	switch mediaType {
	case "application/json",
		"application/javascript",
		"application/x-www-form-urlencoded",
		"application/xml",
		"application/atom+xml",
		"application/rss+xml",
		"application/soap+xml":
		return false
	}
	if strings.HasSuffix(mediaType, "+json") ||
		strings.HasSuffix(mediaType, "+xml") {
		return false
	}

	return true
}

// IsBinaryDownload checks whether an HTTP response represents a binary file download.
func IsBinaryDownload(resp *http.Response) bool {
	if resp.Header.Get("Content-Disposition") != "" {
		return true
	}
	return IsBinaryContentType(resp.Header.Get("Content-Type"))
}

// DetermineFileName extracts a filename from the HTTP response, falling back to a
// default name with an extension derived from the response Content-Type.
func DetermineFileName(resp *http.Response, defaultName string) string {
	if cd := resp.Header.Get("Content-Disposition"); cd != "" {
		if _, params, err := mime.ParseMediaType(cd); err == nil {
			if fn := params["filename"]; fn != "" {
				return filepath.Clean(fn)
			}
		}
	}
	if u, err := url.Parse(resp.Request.URL.String()); err == nil {
		if segs := strings.Split(strings.Trim(u.Path, "/"), "/"); len(segs) > 0 {
			if name, _ := url.QueryUnescape(segs[len(segs)-1]); name != "" {
				return filepath.Clean(name)
			}
		}
	}
	ct := resp.Header.Get("Content-Type")
	ext := ""
	if ct != "" {
		mediaType, _, _ := mime.ParseMediaType(ct)
		ext = mime.TypeByExtension(mediaType)
		if ext == "" {
			switch {
			case strings.HasPrefix(mediaType, "image/"):
				ext = ".png"
			case strings.HasPrefix(mediaType, "video/"):
				ext = ".mp4"
			case strings.HasPrefix(mediaType, "audio/"):
				ext = ".mp3"
			case mediaType == "application/pdf":
				ext = ".pdf"
			case mediaType == "application/octet-stream":
				ext = ".bin"
			case mediaType == "application/zip":
				ext = ".zip"
			default:
				ext = ".dat"
			}
		}
	}
	return defaultName + ext
}

type BinaryDownloadInfo struct {
	Kind      string `json:"kind"`
	URL       string `json:"url"`
	Name      string `json:"name"`
	Type      string `json:"type"`
	SHA1      string `json:"sha1"`
	Size      int64  `json:"size"`
	CreatedAt string `json:"createdAt"`

	tfsPath  string
	localURL string
}

// SaveBinaryStream streams the response body directly to a file in the download
// directory without buffering the entire content in memory.
func SaveBinaryStream(resp *http.Response, defaultName string) (*BinaryDownloadInfo, error) {
	fileName := DetermineFileName(resp, defaultName)
	downloadDir, err := resolveDownloadDir()
	if err != nil {
		return nil, err
	}
	createdAt := time.Now()
	if err := os.MkdirAll(downloadDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create TFS download directory %s: %w", downloadDir, err)
	}
	fileID := uuid.New().String()
	filePath := filepath.Join(downloadDir, fileID)
	inProgressPath := filePath + tfsInProgressSuffix
	f, err := os.Create(inProgressPath)
	if err != nil {
		return nil, fmt.Errorf("failed to create file %s: %w", inProgressPath, err)
	}
	hash := sha1.New()
	written, err := io.Copy(f, io.TeeReader(resp.Body, hash))
	closeErr := f.Close()
	if err != nil {
		os.Remove(inProgressPath)
		return nil, fmt.Errorf("failed to stream response to file %s: %w", inProgressPath, err)
	}
	if closeErr != nil {
		os.Remove(inProgressPath)
		return nil, fmt.Errorf("failed to close file %s: %w", inProgressPath, closeErr)
	}
	if err := os.Rename(inProgressPath, filePath); err != nil {
		os.Remove(inProgressPath)
		return nil, fmt.Errorf("failed to finalize file %s: %w", filePath, err)
	}
	tfsPath := "/_/tfs/download/" + fileID
	contentType := resp.Header.Get("Content-Type")
	if contentType == "" {
		contentType = "application/octet-stream"
	} else if mediaType, _, err := mime.ParseMediaType(contentType); err == nil && mediaType != "" {
		contentType = mediaType
	}
	tfsDownloadMeta.Store(fileID, tfsFileMeta{Name: fileName, ContentType: contentType})
	return &BinaryDownloadInfo{
		Kind:      binaryDownloadKind,
		Name:      fileName,
		Type:      contentType,
		SHA1:      hex.EncodeToString(hash.Sum(nil)),
		Size:      written,
		CreatedAt: formatRFC3339Millis(createdAt),
		tfsPath:   tfsPath,
		localURL:  fileURI(filePath),
	}, nil
}

func binaryDownloadToolResult(ctx context.Context, info *BinaryDownloadInfo) (*mcp.CallToolResult, error) {
	if info == nil {
		return mcp.NewToolResultError("binary download result is empty"), nil
	}
	out := *info
	out.URL = resolveTFSDownloadURL(ctx, info.tfsPath, info.localURL)
	b, err := json.Marshal(out)
	if err != nil {
		return nil, fmt.Errorf("failed to encode binary download result: %w", err)
	}
	return mcp.NewToolResultText(string(b)), nil
}

func fileURI(path string) string {
	abs, err := filepath.Abs(path)
	if err != nil {
		abs = path
	}
	return (&url.URL{Scheme: "file", Path: filepath.ToSlash(abs)}).String()
}

func resolveTFSDownloadURL(ctx context.Context, tfsPath, localURL string) string {
	if tfsPath == "" {
		return ""
	}
	base := resolveTFSBaseURI(ctx)
	if base == "" {
		return localURL
	}
	return strings.TrimRight(base, "/") + tfsPath
}

func resolveTFSBaseURI(ctx context.Context) string {
	if cfg := GetConfig(); cfg != nil {
		if base := strings.TrimSpace(cfg.Server.TFS.BaseURI); base != "" {
			return strings.TrimRight(base, "/")
		}
	}
	r := GetHTTPRequest(ctx)
	if r == nil {
		return ""
	}

	host := firstHeaderValue(r.Header.Get("X-Forwarded-Host"))
	if host == "" {
		host = firstHeaderValue(r.Host)
	}
	if host == "" {
		return ""
	}

	proto := firstHeaderValue(r.Header.Get("X-Forwarded-Proto"))
	if proto == "" {
		proto = forwardedHeaderProto(r.Header.Get("Forwarded"))
	}
	if proto == "" {
		if r.TLS != nil {
			proto = "https"
		} else {
			proto = "http"
		}
	}
	return proto + "://" + host
}

func firstHeaderValue(v string) string {
	if v == "" {
		return ""
	}
	first, _, _ := strings.Cut(v, ",")
	return strings.TrimSpace(first)
}

func forwardedHeaderProto(v string) string {
	first := firstHeaderValue(v)
	for _, part := range strings.Split(first, ";") {
		key, value, ok := strings.Cut(strings.TrimSpace(part), "=")
		if !ok || !strings.EqualFold(strings.TrimSpace(key), "proto") {
			continue
		}
		return strings.Trim(strings.TrimSpace(value), `"`)
	}
	return ""
}

func formatRFC3339Millis(t time.Time) string {
	return t.Format("2006-01-02T15:04:05.000Z07:00")
}

func tfsCleanJobTTL() time.Duration {
	raw := ""
	if cfg := GetConfig(); cfg != nil {
		raw = strings.TrimSpace(cfg.Server.TFS.CleanJobTTLSeconds)
	}
	if raw == "" {
		return defaultTFSCleanJobTTL
	}
	if d, err := time.ParseDuration(raw); err == nil && d > 0 {
		return d
	}
	if seconds, err := strconv.Atoi(raw); err == nil && seconds > 0 {
		return time.Duration(seconds) * time.Second
	}
	return defaultTFSCleanJobTTL
}

// StartTFSCleanJob periodically removes completed temporary TFS files older
// than server.tfs.clean-job-ttl-seconds. Files still ending in .inprogress are
// skipped so partially written transfers cannot be served or removed.
func StartTFSCleanJob(ctx context.Context) {
	go func() {
		cleanTFSOnce(time.Now())
		ticker := time.NewTicker(tfsCleanJobInterval)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case now := <-ticker.C:
				cleanTFSOnce(now)
			}
		}
	}()
}

func cleanTFSOnce(now time.Time) {
	ttl := tfsCleanJobTTL()
	if ttl <= 0 {
		ttl = defaultTFSCleanJobTTL
	}
	for _, resolve := range []func() (string, error){resolveDownloadDir, resolveUploadDir} {
		dir, err := resolve()
		if err != nil {
			continue
		}
		cleanTFSDir(dir, now.Add(-ttl))
	}
}

func cleanTFSDir(root string, cutoff time.Time) {
	_ = filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			return nil
		}
		if strings.HasSuffix(d.Name(), tfsInProgressSuffix) {
			return nil
		}
		info, err := d.Info()
		if err != nil {
			return nil
		}
		if info.ModTime().Before(cutoff) {
			_ = os.Remove(path)
			tfsDownloadMeta.Delete(d.Name())
		}
		return nil
	})
}

// ForwardAndParseResponse sends a request to the upstream and handles the full
// response lifecycle: error status codes, binary download, and text responses.
// All non-upload tool handlers call this to eliminate per-tool boilerplate.
func ForwardAndParseResponse(ctx context.Context, upstreamBase, method, path string, args map[string]interface{}, pathKeys []string, contentType, toolName string) (*mcp.CallToolResult, error) {
	startTime := time.Now()
	resp, err := ForwardRequest(ctx, upstreamBase, method, path, args, pathKeys, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if IsBinaryDownload(resp) {
		info, err := SaveBinaryStream(resp, toolName)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return binaryDownloadToolResult(ctx, info)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, body)

	return mcp.NewToolResultText(string(body)), nil
}

// ForwardBinaryUploadRequest handles non-multipart file uploads (octet-stream,
// image/*, video/*, audio/*). It downloads the file URI to the TFS temp cache
// and forwards it as a raw binary request body to the upstream service.
//
// Like ForwardMultipartRequest, empty file refs are handled gracefully — when
// the URI is empty, an empty request body is sent.
func ForwardBinaryUploadRequest(ctx context.Context, upstreamBase, method, path string, args map[string]interface{}, fileRefs map[string]string, contentType, toolName string) (*mcp.CallToolResult, error) {
	// Build URL with query parameters, excluding file refs and path params.
	upstreamURL := strings.TrimSuffix(upstreamBase, "/") + path
	query := url.Values{}
	for key, val := range args {
		if key == "body" {
			continue
		}
		if _, isFile := fileRefs[key]; isFile {
			continue
		}
		placeholder := "{" + key + "}"
		if strings.Contains(upstreamURL, placeholder) {
			upstreamURL = strings.ReplaceAll(upstreamURL, placeholder, valueToString(val))
			continue
		}
		if strVal, ok := val.(string); ok {
			query.Set(key, strVal)
		} else {
			query.Set(key, valueToString(val))
		}
	}
	if len(query) > 0 {
		upstreamURL += "?" + query.Encode()
	}

	// Download the first file ref to TFS temp cache.
	var fileData []byte
	uri := fileRefs["file"]
	if uri != "" {
		tmpDir, err := resolveUploadTmpDir()
		if err != nil {
			return nil, fmt.Errorf("failed to resolve upload tmp dir: %w", err)
		}
		localPath, _, err := downloadFileFromURI(ctx, uri, tmpDir)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("failed to download file from %s: %v", uri, err)), nil
		}
		defer os.Remove(localPath)
		defer cleanupTFSUploadSourceURI(uri)

		fileData, err = os.ReadFile(localPath)
		if err != nil {
			return nil, fmt.Errorf("failed to read downloaded file %s: %w", localPath, err)
		}
	}

	startTime := time.Now()

	req, err := http.NewRequestWithContext(ctx, method, upstreamURL, bytes.NewReader(fileData))
	if err != nil {
		return nil, fmt.Errorf("failed to create upstream request: %w", err)
	}
	req.Header.Set("Content-Type", contentType)

	if forwarded := GetHTTPHeaders(ctx); forwarded != nil {
		for key, values := range forwarded {
			lowerKey := strings.ToLower(key)
			if lowerKey == "host" || lowerKey == "connection" || lowerKey == "keep-alive" || lowerKey == "proxy-authenticate" || lowerKey == "proxy-authorization" || lowerKey == "te" || lowerKey == "trailer" || lowerKey == "transfer-encoding" || lowerKey == "upgrade" || lowerKey == "authorization" || lowerKey == "cookie" || lowerKey == "content-length" || lowerKey == "mcp-session-id" || lowerKey == "content-type" {
				continue
			}
			for _, v := range values {
				req.Header.Add(key, v)
			}
		}
	}
	if token := GetUpstreamToken(); token != "" {
		req.Header.Set("Authorization", FormatAuthorizationHeader(token))
	}

	if cookie := GetUpstreamCookie(); cookie != "" {
		req.Header.Set("Cookie", cookie)
	}

	if cfg := GetConfig(); cfg != nil && cfg.Upstream["default"].EnableMCPSessionForward {
		if sid := GetSessionID(ctx); sid != "" {
			req.Header.Set("X-MCP-Session-ID", sid)
		}
	}

	if cfg := GetConfig(); cfg != nil && cfg.Server.Auth.OIDC.EnableClientTokenClaimForward {
		if sub := GetClientTokenSub(ctx); sub != "" {
			req.Header.Set("X-MCP-Client-Token-Sub", sub)
		}
		if email := GetClientTokenEmail(ctx); email != "" {
			req.Header.Set("X-MCP-Client-Token-Email", email)
		}
		for _, claim := range cfg.Server.Auth.OIDC.AdditionalClientTokenClaimForward {
			if v := GetClientTokenClaim(ctx, claim); v != "" {
				req.Header.Set("X-MCP-Client-Token-"+HeaderizeClaim(claim), v)
			}
		}
	}

	LogRequest(method, upstreamURL, nil, req.Header, fileData)

	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if IsBinaryDownload(resp) {
		info, err := SaveBinaryStream(resp, toolName)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return binaryDownloadToolResult(ctx, info)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, body)

	return mcp.NewToolResultText(string(body)), nil
}

// resolveUploadTmpDir returns the upload staging directory where files
// downloaded from URIs are temporarily kept while forwarding an upstream
// upload request.
func resolveUploadTmpDir() (string, error) {
	return resolveUploadDir()
}

// downloadFileFromURI download a file from the given URI to a local
// temporary file and returns the local file path and original filename.
// Supports file:/// (local filesystem) and http(s):// (remote download).
// The caller is responsible for removing the file when it is no longer needed.
func downloadFileFromURI(ctx context.Context, uri string, tmpDir string) (localPath string, originalName string, err error) {
	// Handle file:/// URIs — copy directly from local filesystem.
	if strings.HasPrefix(uri, "file://") {
		filePath := strings.TrimPrefix(uri, "file://")
		// Also handle file://localhost/... and file:///...
		filePath = strings.TrimPrefix(filePath, "localhost")
		if !strings.HasPrefix(filePath, "/") {
			return "", "", fmt.Errorf("invalid file URI: %s", uri)
		}
		if err := os.MkdirAll(tmpDir, 0755); err != nil {
			return "", "", fmt.Errorf("create tmp dir %s: %w", tmpDir, err)
		}
		origName := filepath.Base(filePath)
		fileID := generateFileID(origName)
		localPath = filepath.Join(tmpDir, fileID)
		inProgressPath := localPath + tfsInProgressSuffix

		src, err := os.Open(filePath)
		if err != nil {
			return "", "", fmt.Errorf("open %s: %w", filePath, err)
		}
		defer src.Close()

		dst, err := os.Create(inProgressPath)
		if err != nil {
			return "", "", fmt.Errorf("create %s: %w", inProgressPath, err)
		}

		if _, err := io.Copy(dst, src); err != nil {
			dst.Close()
			os.Remove(inProgressPath)
			return "", "", fmt.Errorf("copy %s: %w", filePath, err)
		}
		if err := dst.Close(); err != nil {
			os.Remove(inProgressPath)
			return "", "", fmt.Errorf("close %s: %w", inProgressPath, err)
		}
		if err := os.Rename(inProgressPath, localPath); err != nil {
			os.Remove(inProgressPath)
			return "", "", fmt.Errorf("finalize %s: %w", localPath, err)
		}
		return localPath, origName, nil
	}

	req, err := http.NewRequestWithContext(ctx, "GET", uri, nil)
	if err != nil {
		return "", "", fmt.Errorf("failed to create download request for %s: %w", uri, err)
	}

	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
	resp, err := client.Do(req)
	if err != nil {
		return "", "", fmt.Errorf("failed to download from %s: %w", uri, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return "", "", fmt.Errorf("download from %s returned status %d", uri, resp.StatusCode)
	}

	// Determine filename from response headers or URL
	fileName := ""
	if cd := resp.Header.Get("Content-Disposition"); cd != "" {
		if _, params, err := mime.ParseMediaType(cd); err == nil {
			if fn := params["filename"]; fn != "" {
				fileName = filepath.Clean(fn)
			}
		}
	}
	if fileName == "" {
		// Extract filename from URL path
		if u, err := url.Parse(uri); err == nil {
			if segs := strings.Split(strings.Trim(u.Path, "/"), "/"); len(segs) > 0 {
				if name, _ := url.QueryUnescape(segs[len(segs)-1]); name != "" {
					fileName = filepath.Clean(name)
				}
			}
		}
	}
	if fileName == "" {
		fileName = "downloaded_file"
	}

	if err := os.MkdirAll(tmpDir, 0755); err != nil {
		return "", "", fmt.Errorf("failed to create tmp directory %s: %w", tmpDir, err)
	}

	// Use UUID.{suffix} naming in TFS directory to avoid collisions.
	fileID := generateFileID(fileName)
	localPath = filepath.Join(tmpDir, fileID)
	inProgressPath := localPath + tfsInProgressSuffix
	f, err := os.Create(inProgressPath)
	if err != nil {
		return "", "", fmt.Errorf("failed to create local file %s: %w", inProgressPath, err)
	}

	if _, err := io.Copy(f, resp.Body); err != nil {
		f.Close()
		os.Remove(inProgressPath)
		return "", "", fmt.Errorf("failed to write downloaded file %s: %w", inProgressPath, err)
	}
	if err := f.Close(); err != nil {
		os.Remove(inProgressPath)
		return "", "", fmt.Errorf("failed to close downloaded file %s: %w", inProgressPath, err)
	}
	if err := os.Rename(inProgressPath, localPath); err != nil {
		os.Remove(inProgressPath)
		return "", "", fmt.Errorf("failed to finalize downloaded file %s: %w", localPath, err)
	}

	return localPath, fileName, nil
}

func fileURIPath(uri string) (string, bool) {
	u, err := url.Parse(uri)
	if err != nil || u.Scheme != "file" {
		return "", false
	}
	if u.Host != "" && u.Host != "localhost" {
		return "", false
	}
	if u.Path == "" || !filepath.IsAbs(u.Path) {
		return "", false
	}
	return filepath.Clean(u.Path), true
}

func isPathWithinDir(path string, dir string) bool {
	rel, err := filepath.Rel(filepath.Clean(dir), filepath.Clean(path))
	if err != nil || rel == "." || rel == ".." {
		return false
	}
	return !strings.HasPrefix(rel, ".."+string(os.PathSeparator))
}

func cleanupTFSUploadSourceURI(uri string) {
	path, ok := fileURIPath(uri)
	if !ok || strings.HasSuffix(path, tfsInProgressSuffix) {
		return
	}
	uploadDir, err := resolveUploadDir()
	if err != nil || !isPathWithinDir(path, uploadDir) {
		return
	}
	_ = os.Remove(path)
	tfsDownloadMeta.Delete(filepath.Base(path))
}

func isDownloadableFileURI(uri string) bool {
	u, err := url.Parse(uri)
	if err != nil {
		return false
	}
	switch u.Scheme {
	case "file":
		return u.Path != "" && filepath.IsAbs(u.Path) && (u.Host == "" || u.Host == "localhost")
	case "http", "https":
		return u.Host != ""
	default:
		return false
	}
}

func filePartContentType(fileName string) string {
	ext := strings.ToLower(filepath.Ext(fileName))
	switch ext {
	case ".zip":
		return "application/zip"
	case ".war", ".jar", ".ear":
		return "application/java-archive"
	}
	if ext != "" {
		if ct := mime.TypeByExtension(ext); ct != "" {
			if mediaType, _, err := mime.ParseMediaType(ct); err == nil && mediaType != "" {
				return mediaType
			}
			return ct
		}
	}
	return "application/octet-stream"
}

func multipartPartContentType(partContentTypes map[string]string, fieldName string) string {
	if partContentTypes == nil {
		return ""
	}
	return strings.TrimSpace(partContentTypes[fieldName])
}

func isJSONContentType(contentType string) bool {
	mediaType, _, err := mime.ParseMediaType(contentType)
	if err != nil {
		mediaType = strings.TrimSpace(strings.Split(contentType, ";")[0])
	}
	mediaType = strings.ToLower(mediaType)
	return mediaType == "application/json" || strings.HasSuffix(mediaType, "+json")
}

func createMultipartValuePart(writer *multipart.Writer, fieldName string, val interface{}, contentType string) error {
	contentType = strings.TrimSpace(contentType)
	if contentType == "" {
		return writer.WriteField(fieldName, valueToString(val))
	}
	header := make(textproto.MIMEHeader)
	header.Set("Content-Disposition", mime.FormatMediaType("form-data", map[string]string{
		"name": fieldName,
	}))
	header.Set("Content-Type", contentType)
	part, err := writer.CreatePart(header)
	if err != nil {
		return err
	}
	if isJSONContentType(contentType) {
		data, err := json.Marshal(sanitizeForJSON(val))
		if err != nil {
			return err
		}
		_, err = part.Write(data)
		return err
	}
	_, err = io.WriteString(part, valueToString(val))
	return err
}

func createMultipartFilePart(writer *multipart.Writer, fieldName string, fileName string, contentType string) (io.Writer, error) {
	if fileName == "" {
		fileName = fieldName
	}
	contentType = strings.TrimSpace(contentType)
	if contentType == "" {
		contentType = filePartContentType(fileName)
	}
	header := make(textproto.MIMEHeader)
	header.Set("Content-Disposition", mime.FormatMediaType("form-data", map[string]string{
		"name":     fieldName,
		"filename": filepath.Base(fileName),
	}))
	header.Set("Content-Type", contentType)
	return writer.CreatePart(header)
}

// ForwardMultipartRequest handles multipart/form-data requests where file
// arguments are provided as URIs (the FileRef pattern). It:
//  1. Downloads each file URI to a local temp directory (~/.{service}/download/tmp/)
//  2. Builds a multipart/form-data request body with form fields and file parts
//  3. Sends the request to the upstream service
//  4. Cleans up temporary files
//  5. Returns the upstream response (or saves it as a binary download)
//
// Empty optional file refs are omitted. Non-empty file refs with file/http(s)
// schemes become file parts; other values are forwarded as normal text form
// fields so anyOf binary|string multipart schemas remain usable.
func ForwardMultipartRequest(ctx context.Context, upstreamBase, method, path string, args map[string]interface{}, fileRefs map[string]string, pathKeys []string, queryKeys []string, partContentTypes map[string]string, toolName string) (*mcp.CallToolResult, error) {
	startTime := time.Now()

	// Build URL with path parameter substitution and declared query parameters.
	// Body/form fields must not be mirrored into the query string; multipart
	// forwarding should match a normal HTTP client call for the OpenAPI operation.
	upstreamURL := strings.TrimSuffix(upstreamBase, "/") + path
	query := url.Values{}
	for key, val := range args {
		if key == "body" {
			continue
		}
		// Check if this is a file ref — skip for URL building
		if _, isFile := fileRefs[key]; isFile {
			continue
		}
		placeholder := "{" + key + "}"
		if strings.Contains(upstreamURL, placeholder) {
			upstreamURL = strings.ReplaceAll(upstreamURL, placeholder, valueToString(val))
		} else if isPathKey(key, queryKeys) {
			if strVal, ok := val.(string); ok {
				query.Set(key, strVal)
			} else {
				query.Set(key, valueToString(val))
			}
		}
	}
	if len(query) > 0 {
		upstreamURL += "?" + query.Encode()
	}

	// Download each non-empty file URI to a local temp file.
	hasDownloads := false
	for _, uri := range fileRefs {
		if isDownloadableFileURI(strings.TrimSpace(uri)) {
			hasDownloads = true
			break
		}
	}
	var localFiles map[string]string
	var origNames map[string]string
	var sourceURIs []string
	if hasDownloads {
		tmpDir, err := resolveUploadTmpDir()
		if err != nil {
			return nil, fmt.Errorf("failed to resolve upload tmp dir: %w", err)
		}
		localFiles = make(map[string]string)
		origNames = make(map[string]string)
		for fieldName, uri := range fileRefs {
			uri = strings.TrimSpace(uri)
			if !isDownloadableFileURI(uri) {
				continue
			}
			localPath, origName, err := downloadFileFromURI(ctx, uri, tmpDir)
			if err != nil {
				for _, lp := range localFiles {
					os.Remove(lp)
				}
				return mcp.NewToolResultError(fmt.Sprintf("failed to download %s from %s: %v", fieldName, uri, err)), nil
			}
			localFiles[fieldName] = localPath
			origNames[fieldName] = origName
			sourceURIs = append(sourceURIs, uri)
		}
		// Clean up temp files when done
		defer func() {
			for _, lp := range localFiles {
				os.Remove(lp)
			}
			for _, uri := range sourceURIs {
				cleanupTFSUploadSourceURI(uri)
			}
		}()
	}

	// Build multipart form body
	var buf bytes.Buffer
	writer := multipart.NewWriter(&buf)

	// Add non-file form fields
	for key, val := range args {
		if key == "body" {
			continue
		}
		if uri, isFile := fileRefs[key]; isFile {
			uri = strings.TrimSpace(uri)
			if uri != "" && !isDownloadableFileURI(uri) {
				if err := createMultipartValuePart(writer, key, uri, multipartPartContentType(partContentTypes, key)); err != nil {
					return nil, fmt.Errorf("failed to write form field %s: %w", key, err)
				}
			}
			continue
		}
		if isPathKey(key, pathKeys) {
			continue
		}
		if isPathKey(key, queryKeys) {
			continue
		}
		if err := createMultipartValuePart(writer, key, val, multipartPartContentType(partContentTypes, key)); err != nil {
			return nil, fmt.Errorf("failed to write form field %s: %w", key, err)
		}
	}

	// Add file parts for supplied file URIs. Omitted optional file args are not
	// serialized as empty files; that matches normal multipart clients and avoids
	// triggering upstream filename/extension validators with filename="file".
	for fieldName := range fileRefs {
		if localPath, ok := localFiles[fieldName]; ok {
			origName := origNames[fieldName]
			if origName == "" {
				origName = filepath.Base(localPath)
			}
			part, err := createMultipartFilePart(writer, fieldName, origName, multipartPartContentType(partContentTypes, fieldName))
			if err != nil {
				return nil, fmt.Errorf("failed to create form file for %s: %w", fieldName, err)
			}
			f, err := os.Open(localPath)
			if err != nil {
				return nil, fmt.Errorf("failed to open local file %s: %w", localPath, err)
			}
			if _, err := io.Copy(part, f); err != nil {
				f.Close()
				return nil, fmt.Errorf("failed to copy file data for %s: %w", fieldName, err)
			}
			f.Close()
		}
	}
	writer.Close()

	// Build HTTP request
	req, err := http.NewRequestWithContext(ctx, method, upstreamURL, &buf)
	if err != nil {
		return nil, fmt.Errorf("failed to create upstream request: %w", err)
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	// Forward headers from context (same logic as ForwardRequest)
	if forwarded := GetHTTPHeaders(ctx); forwarded != nil {
		for key, values := range forwarded {
			lowerKey := strings.ToLower(key)
			if lowerKey == "host" || lowerKey == "connection" || lowerKey == "keep-alive" || lowerKey == "proxy-authenticate" || lowerKey == "proxy-authorization" || lowerKey == "te" || lowerKey == "trailer" || lowerKey == "transfer-encoding" || lowerKey == "upgrade" || lowerKey == "authorization" || lowerKey == "cookie" || lowerKey == "content-length" || lowerKey == "mcp-session-id" || lowerKey == "content-type" {
				continue
			}
			for _, v := range values {
				req.Header.Add(key, v)
			}
		}
	}
	if token := GetUpstreamToken(); token != "" {
		req.Header.Set("Authorization", FormatAuthorizationHeader(token))
	}
	if cookie := GetUpstreamCookie(); cookie != "" {
		req.Header.Set("Cookie", cookie)
	}
	if cfg := GetConfig(); cfg != nil && cfg.Upstream["default"].EnableMCPSessionForward {
		if sid := GetSessionID(ctx); sid != "" {
			req.Header.Set("X-MCP-Session-ID", sid)
		}
	}
	if cfg := GetConfig(); cfg != nil && cfg.Server.Auth.OIDC.EnableClientTokenClaimForward {
		if sub := GetClientTokenSub(ctx); sub != "" {
			req.Header.Set("X-MCP-Client-Token-Sub", sub)
		}
		if email := GetClientTokenEmail(ctx); email != "" {
			req.Header.Set("X-MCP-Client-Token-Email", email)
		}
		for _, claim := range cfg.Server.Auth.OIDC.AdditionalClientTokenClaimForward {
			if v := GetClientTokenClaim(ctx, claim); v != "" {
				req.Header.Set("X-MCP-Client-Token-"+HeaderizeClaim(claim), v)
			}
		}
	}

	LogRequest(method, upstreamURL, query, req.Header, buf.Bytes())

	client := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyFromEnvironment,
		},
	}
	resp, err := client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, nil)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if IsBinaryDownload(resp) {
		info, err := SaveBinaryStream(resp, toolName)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		return binaryDownloadToolResult(ctx, info)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	LogResponse(ctx, resp.StatusCode, method, resp.Request.URL.String(), time.Since(startTime), resp.Header, body)

	return mcp.NewToolResultText(string(body)), nil
}

// isPathKey returns true when key is in the pathKeys slice.
func isPathKey(key string, pathKeys []string) bool {
	for _, pk := range pathKeys {
		if pk == key {
			return true
		}
	}
	return false
}

// ---- TFS (Temporary File System) helpers ----

// generateFileID creates a UUID-based filename preserving the original suffix.
// e.g. "report.pdf" → "550e8400-e29b-41d4-a716-446655440000.pdf"
func generateFileID(originalName string) string {
	suffix := filepath.Ext(originalName)
	if suffix == "" {
		suffix = ".bin"
	}
	return uuid.New().String() + suffix
}

func validTFSObjectName(name string) bool {
	if name == "" || name == "." || name == ".." {
		return false
	}
	if strings.ContainsAny(name, `/\`) {
		return false
	}
	return !strings.HasSuffix(name, tfsInProgressSuffix)
}

func contentDispositionAttachment(name string) string {
	if name == "" {
		return "attachment"
	}
	safe := strings.NewReplacer("\\", "_", `"`, "_", "\r", "_", "\n", "_").Replace(filepath.Base(name))
	return fmt.Sprintf(`attachment; filename="%s"; filename*=UTF-8''%s`, safe, url.PathEscape(safe))
}

func resolveTFSObjectPath(fileID string, dirs ...func() (string, error)) (string, error) {
	for _, resolve := range dirs {
		dir, err := resolve()
		if err != nil {
			continue
		}
		filePath := filepath.Clean(filepath.Join(dir, fileID))
		if !isPathWithinDir(filePath, dir) {
			continue
		}
		if _, err := os.Stat(filePath); err == nil {
			return filePath, nil
		}
	}
	return "", os.ErrNotExist
}

type tfsDownloadResponseRecorder struct {
	http.ResponseWriter
	status   int
	written  int64
	writeErr error
}

func (r *tfsDownloadResponseRecorder) WriteHeader(status int) {
	if r.status != 0 {
		return
	}
	r.status = status
	r.ResponseWriter.WriteHeader(status)
}

func (r *tfsDownloadResponseRecorder) Write(p []byte) (int, error) {
	if r.status == 0 {
		r.status = http.StatusOK
	}
	n, err := r.ResponseWriter.Write(p)
	r.written += int64(n)
	if err != nil && r.writeErr == nil {
		r.writeErr = err
	}
	return n, err
}

func (r *tfsDownloadResponseRecorder) completed(fileSize int64) bool {
	status := r.status
	if status == 0 {
		status = http.StatusOK
	}
	return status == http.StatusOK &&
		r.writeErr == nil &&
		r.written == fileSize
}

// ---- TFS Data Plane HTTP Handlers ----
//
// These built-in REST endpoints form the "data plane" for binary file transfer,
// separate from the JSON-RPC 2.0 "control plane" at /mcp.

// HandleTFSDownload serves a binary file from the TFS download/upload staging
// directories once.
// URL pattern: GET /_/tfs/download/{uuid}
func HandleTFSDownload(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Extract path after /_/tfs/download/
	fileID := strings.TrimPrefix(r.URL.Path, "/_/tfs/download/")
	if fileID == "" || fileID == r.URL.Path || !validTFSObjectName(fileID) {
		http.Error(w, "invalid path", http.StatusBadRequest)
		return
	}

	filePath, err := resolveTFSObjectPath(fileID, resolveDownloadDir, resolveUploadDir)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	f, err := os.Open(filePath)
	if err != nil {
		http.NotFound(w, r)
		return
	}
	defer f.Close()

	stat, err := f.Stat()
	if err != nil {
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}
	if metaRaw, ok := tfsDownloadMeta.Load(fileID); ok {
		if meta, ok := metaRaw.(tfsFileMeta); ok {
			if meta.ContentType != "" {
				w.Header().Set("Content-Type", meta.ContentType)
			}
			if meta.Name != "" {
				w.Header().Set("Content-Disposition", contentDispositionAttachment(meta.Name))
			}
		}
	}
	recorder := &tfsDownloadResponseRecorder{ResponseWriter: w}
	http.ServeContent(recorder, r, fileID, stat.ModTime(), f)
	if recorder.completed(stat.Size()) {
		_ = os.Remove(filePath)
		tfsDownloadMeta.Delete(fileID)
	}
}

// HandleTFSUpload accepts binary file upload into the TFS data plane.
// URL pattern: POST /_/tfs/upload/{uuid}
// The client can POST raw binary body (Content-Type: application/octet-stream)
// or multipart/form-data with a "file" field.
// Returns the one-time download URL for the stored file.
func HandleTFSUpload(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost && r.Method != http.MethodPut {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	// Extract path after /_/tfs/upload/
	fileID := strings.TrimPrefix(r.URL.Path, "/_/tfs/upload/")
	if fileID == "" || fileID == r.URL.Path || !validTFSObjectName(fileID) {
		http.Error(w, "invalid path", http.StatusBadRequest)
		return
	}

	// Save uploaded files to the upload directory. Tool forwarding treats this
	// as temporary staging and removes TFS upload files once upstream forwarding
	// completes.
	uploadDir, err := resolveUploadDir()
	if err != nil {
		http.Error(w, "internal error", http.StatusInternalServerError)
		return
	}

	if err := os.MkdirAll(uploadDir, 0755); err != nil {
		http.Error(w, fmt.Sprintf("failed to create upload directory: %v", err), http.StatusInternalServerError)
		return
	}

	destPath := filepath.Join(uploadDir, fileID)
	// Prevent directory traversal
	destPath = filepath.Clean(destPath)
	if !isPathWithinDir(destPath, uploadDir) {
		http.Error(w, "forbidden", http.StatusForbidden)
		return
	}

	// Accept raw binary body or multipart file upload
	var fileData []byte
	fileName := fileID
	contentType := r.Header.Get("Content-Type")
	mediaType, _, _ := mime.ParseMediaType(contentType)
	if mediaType == "multipart/form-data" {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			http.Error(w, fmt.Sprintf("failed to parse multipart form: %v", err), http.StatusBadRequest)
			return
		}
		file, header, err := r.FormFile("file")
		if err != nil {
			http.Error(w, fmt.Sprintf("missing 'file' field in multipart form: %v", err), http.StatusBadRequest)
			return
		}
		if header != nil && header.Filename != "" {
			fileName = filepath.Base(header.Filename)
		}
		defer file.Close()
		fileData, err = io.ReadAll(file)
		if err != nil {
			http.Error(w, fmt.Sprintf("failed to read uploaded file: %v", err), http.StatusInternalServerError)
			return
		}
	} else {
		fileData, err = io.ReadAll(r.Body)
		if err != nil {
			http.Error(w, fmt.Sprintf("failed to read request body: %v", err), http.StatusBadRequest)
			return
		}
	}
	if contentType == "" || mediaType == "multipart/form-data" {
		contentType = "application/octet-stream"
	} else if mediaType != "" {
		contentType = mediaType
	}

	inProgressPath := destPath + tfsInProgressSuffix
	if err := os.WriteFile(inProgressPath, fileData, 0644); err != nil {
		http.Error(w, fmt.Sprintf("failed to write file: %v", err), http.StatusInternalServerError)
		return
	}
	if err := os.Rename(inProgressPath, destPath); err != nil {
		os.Remove(inProgressPath)
		http.Error(w, fmt.Sprintf("failed to finalize file: %v", err), http.StatusInternalServerError)
		return
	}

	// Return the download URL
	tfsPath := fmt.Sprintf("/_/tfs/download/%s", fileID)
	tfsDownloadMeta.Store(fileID, tfsFileMeta{Name: fileName, ContentType: contentType})
	downloadURL := resolveTFSDownloadURL(WithHTTPRequest(r.Context(), r), tfsPath, fileURI(destPath))
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(map[string]interface{}{
		"status":       "ok",
		"path":         fileURI(destPath),
		"download_url": downloadURL,
		"size":         len(fileData),
	})
}
