// Code generated by https://github.com/flowgent-labs/mcpfather

package mcputils

import (
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestFormatAuthorizationHeader(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  string
	}{
		{"empty", "", ""},
		{"bare token", "abc123", "Bearer abc123"},
		{"already bearer", "Bearer abc123", "Bearer abc123"},
		{"already basic", "Basic dXNlcjpwYXNz", "Basic dXNlcjpwYXNz"},
		{"lower bearer", "bearer abc123", "bearer abc123"},
		{"trim spaces", "  abc123  ", "Bearer abc123"},
		{"basic lower", "basic dXNlcjpwYXNz", "basic dXNlcjpwYXNz"},
		{"all uppercase", "BEARER xyz", "BEARER xyz"},
		{"token with spaces inside", "  token with spaces  ", "Bearer token with spaces"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := FormatAuthorizationHeader(tt.input)
			if got != tt.want {
				t.Errorf("FormatAuthorizationHeader(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestValueToString(t *testing.T) {
	tests := []struct {
		name  string
		input interface{}
		want  string
	}{
		{"string", "hello", "hello"},
		{"int", 42, "42"},
		{"float64 no sci", float64(123), "123"},
		{"float64 large", float64(1e9), "1000000000"},
		{"float32", float32(3.14), "3.14"},
		{"bool", true, "true"},
		{"nil", nil, "<nil>"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := valueToString(tt.input)
			if got != tt.want {
				t.Errorf("valueToString(%v) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestBuildJSONBody(t *testing.T) {
	args := map[string]interface{}{
		"body":  "should be in body",
		"name":  "test",
		"age":   42,
		"debug": true,
	}
	pathKeys := []string{"name"}
	result := buildJSONBody(args, pathKeys)
	if _, ok := result["name"]; ok {
		t.Error("path key 'name' should be excluded from body")
	}
	if _, ok := result["body"]; !ok {
		t.Error("body key should be in body")
	}
	if v, ok := result["age"]; !ok || v != 42 {
		t.Errorf("age should be 42, got %v", v)
	}
}

func TestHeaderizeClaim(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"given_name", "Given-Name"},
		{"preferred_username", "Preferred-Username"},
		{"email", "Email"},
		{"family_name", "Family-Name"},
		{"", ""},
		{"single", "Single"},
	}
	for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := HeaderizeClaim(tt.input)
			if got != tt.want {
				t.Errorf("HeaderizeClaim(%q) = %q, want %q", tt.input, got, tt.want)
			}
		})
	}
}

func TestSanitizeForJSON(t *testing.T) {
	t.Run("float64 no sci", func(t *testing.T) {
		result := sanitizeForJSON(1e10)
		if stringResult, ok := result.([]byte); ok {
			if string(stringResult) != "10000000000" {
				t.Errorf("got %q, want %q", string(stringResult), "10000000000")
			}
		}
	})
	t.Run("nested map", func(t *testing.T) {
		result := sanitizeForJSON(map[string]interface{}{"count": float64(100)})
		m := result.(map[string]interface{})
		if m == nil {
			t.Error("map should not be nil")
		}
	})
	t.Run("simple string passthrough", func(t *testing.T) {
		result := sanitizeForJSON("hello")
		if result.(string) != "hello" {
			t.Error("string should pass through")
		}
	})
}

func TestMarshalJSONNoSci(t *testing.T) {
	data := map[string]interface{}{"id": float64(1000000000000000)}
	result, err := marshalJSONNoSci(data)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if strings.Contains(string(result), "e+") {
		t.Errorf("scientific notation found: %s", string(result))
	}
}

func TestIsBinaryContentType(t *testing.T) {
	tests := []struct {
		ct   string
		want bool
	}{
		{"text/html", false},
		{"application/json", false},
		{"application/xml", false},
		{"application/soap+xml", false},
		{"application/problem+json", false},
		{"application/octet-stream", true},
		{"image/png", true},
		{"video/mp4", true},
		{"application/pdf", true},
		{"", true},
		{"application/zip", true},
		{"application/javascript", false},
		{"application/atom+xml", false},
		{"application/rss+xml", false},
		{"application/x-www-form-urlencoded", false},
	}
	for _, tt := range tests {
		t.Run(tt.ct, func(t *testing.T) {
			if got := IsBinaryContentType(tt.ct); got != tt.want {
				t.Errorf("IsBinaryContentType(%q) = %v, want %v", tt.ct, got, tt.want)
			}
		})
	}
}

func TestIsBinaryDownload(t *testing.T) {
	t.Run("with content-disposition", func(t *testing.T) {
		resp := &http.Response{Header: http.Header{"Content-Disposition": {"attachment; filename=report.pdf"}}}
		if !IsBinaryDownload(resp) {
			t.Error("should be binary download")
		}
	})
	t.Run("binary content type", func(t *testing.T) {
		resp := &http.Response{Header: http.Header{"Content-Type": {"application/octet-stream"}}}
		if !IsBinaryDownload(resp) {
			t.Error("should be binary download")
		}
	})
	t.Run("json is not binary", func(t *testing.T) {
		resp := &http.Response{Header: http.Header{"Content-Type": {"application/json"}}}
		if IsBinaryDownload(resp) {
			t.Error("JSON should not be binary")
		}
	})
}

func TestDetermineFileName(t *testing.T) {
	t.Run("from content-disposition", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Disposition", `attachment; filename="report.pdf"`)
		resp.Request, _ = http.NewRequest("GET", ts.URL+"/api/download", nil)
		got := DetermineFileName(resp, "default")
		if got != "report.pdf" {
			t.Errorf("got %q, want %q", got, "report.pdf")
		}
		resp.Body.Close()
	})
	t.Run("from URL path", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL + "/download/data.csv")
		resp.Header.Set("Content-Type", "text/csv")
		resp.Request, _ = http.NewRequest("GET", ts.URL+"/download/data.csv", nil)
		got := DetermineFileName(resp, "default")
		if got != "data.csv" {
			t.Errorf("got %q, want %q", got, "data.csv")
		}
		resp.Body.Close()
	})
	t.Run("fallback with content-type extension", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Type", "application/pdf")
		resp.Request, _ = http.NewRequest("GET", ts.URL, nil)
		got := DetermineFileName(resp, "output")
		if got != "output.pdf" {
			t.Errorf("got %q, want %q", got, "output.pdf")
		}
		resp.Body.Close()
	})
	t.Run("unknown content type fallback", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Type", "application/octet-stream")
		resp.Request, _ = http.NewRequest("GET", ts.URL, nil)
		got := DetermineFileName(resp, "download")
		if got != "download.bin" {
			t.Errorf("got %q, want %q", got, "download.bin")
		}
		resp.Body.Close()
	})
	t.Run("video content type", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {}))
		defer ts.Close()
		resp, _ := http.Get(ts.URL)
		resp.Header.Set("Content-Type", "video/mp4")
		resp.Request, _ = http.NewRequest("GET", ts.URL, nil)
		got := DetermineFileName(resp, "clip")
		if got != "clip.mp4" {
			t.Errorf("got %q, want %q", got, "clip.mp4")
		}
		resp.Body.Close()
	})
}

func TestParamsParser(t *testing.T) {
	type testArgs struct {
		Name  string `json:"name"`
		Count int    `json:"count"`
	}
	args := map[string]interface{}{
		"name":  "test",
		"count": float64(5),
	}
	result, err := ParamsParser[testArgs](args)
	if err != nil {
		t.Fatalf("ParamsParser failed: %v", err)
	}
	if result.Name != "test" {
		t.Errorf("name: got %q, want %q", result.Name, "test")
	}
	if result.Count != 5 {
		t.Errorf("count: got %d, want %d", result.Count, 5)
	}
}

func TestForwardRequest_WithMockUpstream(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == "GET" && r.URL.Path == "/api/test" {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"status":"ok"}`))
			return
		}
		if r.Method == "POST" && r.URL.Path == "/api/create" {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusCreated)
			w.Write([]byte(`{"id":1}`))
			return
		}
		w.WriteHeader(http.StatusNotFound)
	}))
	defer ts.Close()

	t.Setenv("MCP__UPSTREAM__DEFAULT__ENDPOINT", ts.URL)
	LoadConfig("sonarqube-mcp")

	t.Run("GET request", func(t *testing.T) {
		ctx := context.Background()
		resp, err := ForwardRequest(ctx, ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusOK {
			t.Errorf("expected 200, got %d", resp.StatusCode)
		}
	})

	t.Run("POST with body", func(t *testing.T) {
		ctx := context.Background()
		args := map[string]interface{}{"body": map[string]interface{}{"name": "test"}}
		resp, err := ForwardRequest(ctx, ts.URL, "POST", "/api/create", args, []string{}, "application/json")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
		if resp.StatusCode != http.StatusCreated {
			t.Errorf("expected 201, got %d", resp.StatusCode)
		}
	})

	t.Run("path parameter substitution", func(t *testing.T) {
		ctx := context.Background()
		resp, err := ForwardRequest(ctx, ts.URL, "GET", "/api/item/{id}", map[string]interface{}{"id": "42"}, []string{"id"}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
	})

	t.Run("query parameters", func(t *testing.T) {
		ctx := context.Background()
		resp, err := ForwardRequest(ctx, ts.URL, "GET", "/api/search", map[string]interface{}{"q": "test", "page": float64(1)}, []string{}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
	})

	t.Run("POST auto body", func(t *testing.T) {
		ctx := context.Background()
		args := map[string]interface{}{"name": "test", "age": float64(30)}
		resp, err := ForwardRequest(ctx, ts.URL, "POST", "/api/create", args, []string{"name"}, "")
		if err != nil {
			t.Fatalf("ForwardRequest failed: %v", err)
		}
		defer resp.Body.Close()
	})
}

func TestForwardAndParseResponse(t *testing.T) {
	t.Run("success", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		result, err := ForwardAndParseResponse(context.Background(), ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "", "TestTool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
		if result.IsError {
			t.Error("unexpected error result")
		}
	})

	t.Run("upstream error 500", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusInternalServerError)
			w.Write([]byte(`{"error":"boom"}`))
		}))
		defer ts.Close()

		result, err := ForwardAndParseResponse(context.Background(), ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "", "TestTool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !result.IsError {
			t.Error("expected error result")
		}
	})

	t.Run("upstream error 404", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusNotFound)
			w.Write([]byte(`{"error":"not found"}`))
		}))
		defer ts.Close()

		result, err := ForwardAndParseResponse(context.Background(), ts.URL, "GET", "/api/test", map[string]interface{}{}, []string{}, "", "TestTool")
		if err != nil {
			t.Fatalf("unexpected error: %v", err)
		}
		if !result.IsError {
			t.Error("expected error result for 404")
		}
	})
}

func TestWithHTTPHeaders(t *testing.T) {
	headers := http.Header{"X-Custom": {"custom-value"}}
	ctx := WithHTTPHeaders(context.Background(), headers)
	got := GetHTTPHeaders(ctx)
	if got == nil {
		t.Fatal("GetHTTPHeaders returned nil")
	}
	if got.Get("X-Custom") != "custom-value" {
		t.Errorf("expected custom-value, got %q", got.Get("X-Custom"))
	}
}

func TestGetHTTPHeaders_Nil(t *testing.T) {
	got := GetHTTPHeaders(context.Background())
	if got != nil {
		t.Error("expected nil for context without headers")
	}
}

func TestIFSDownloadURLResolution(t *testing.T) {
	ifsPath := "/_/ifs/download/550e8400-e29b-41d4-a716-446655440000"
	localURL := "file:///tmp/550e8400-e29b-41d4-a716-446655440000"

	t.Run("configured base URI wins", func(t *testing.T) {
		SetConfig(&Config{Server: ServerConfig{IFS: IFSConfig{BaseURI: "https://files.example.com/base/"}}})
		req := httptest.NewRequest("POST", "http://internal:8080/mcp", nil)
		ctx := WithHTTPRequest(context.Background(), req)
		got := resolveIFSDownloadURL(ctx, ifsPath, localURL)
		want := "https://files.example.com/base" + ifsPath
		if got != want {
			t.Fatalf("resolveIFSDownloadURL = %q, want %q", got, want)
		}
	})

	t.Run("forwarded headers", func(t *testing.T) {
		SetConfig(&Config{})
		req := httptest.NewRequest("POST", "http://internal:8080/mcp", nil)
		req.Header.Set("X-Forwarded-Proto", "https")
		req.Header.Set("X-Forwarded-Host", "mcp.example.com")
		ctx := WithHTTPRequest(context.Background(), req)
		got := resolveIFSDownloadURL(ctx, ifsPath, localURL)
		want := "https://mcp.example.com" + ifsPath
		if got != want {
			t.Fatalf("resolveIFSDownloadURL = %q, want %q", got, want)
		}
	})

	t.Run("request host", func(t *testing.T) {
		SetConfig(&Config{})
		req := httptest.NewRequest("POST", "http://localhost:18889/mcp", nil)
		ctx := WithHTTPRequest(context.Background(), req)
		got := resolveIFSDownloadURL(ctx, ifsPath, localURL)
		want := "http://localhost:18889" + ifsPath
		if got != want {
			t.Fatalf("resolveIFSDownloadURL = %q, want %q", got, want)
		}
	})

	t.Run("no request returns file URL", func(t *testing.T) {
		SetConfig(&Config{})
		if got := resolveIFSDownloadURL(context.Background(), ifsPath, localURL); got != localURL {
			t.Fatalf("resolveIFSDownloadURL = %q, want %q", got, localURL)
		}
	})
}

func TestIFSCleanJobTTL(t *testing.T) {
	oldCfg := GetConfig()
	defer SetConfig(oldCfg)

	SetConfig(&Config{Server: ServerConfig{IFS: IFSConfig{CleanJobTTLSeconds: "30s"}}})
	if got := ifsCleanJobTTL(); got != 30*time.Second {
		t.Fatalf("ifsCleanJobTTL = %v, want 30s", got)
	}

	SetConfig(&Config{Server: ServerConfig{IFS: IFSConfig{CleanJobTTLSeconds: "45"}}})
	if got := ifsCleanJobTTL(); got != 45*time.Second {
		t.Fatalf("ifsCleanJobTTL = %v, want 45s", got)
	}

	SetConfig(&Config{Server: ServerConfig{IFS: IFSConfig{CleanJobTTLSeconds: "not-a-duration"}}})
	if got := ifsCleanJobTTL(); got != defaultIFSCleanJobTTL {
		t.Fatalf("ifsCleanJobTTL = %v, want default %v", got, defaultIFSCleanJobTTL)
	}
}

func TestCleanIFSDirSkipsInProgressFiles(t *testing.T) {
	root := t.TempDir()
	oldFormal := filepath.Join(root, "old-formal")
	oldInProgress := filepath.Join(root, "old-formal"+ifsInProgressSuffix)
	youngFormal := filepath.Join(root, "young-formal")
	for _, path := range []string{oldFormal, oldInProgress, youngFormal} {
		if err := os.WriteFile(path, []byte("x"), 0644); err != nil {
			t.Fatalf("write %s: %v", path, err)
		}
	}
	oldTime := time.Now().Add(-10 * time.Minute)
	if err := os.Chtimes(oldFormal, oldTime, oldTime); err != nil {
		t.Fatalf("chtimes old formal: %v", err)
	}
	if err := os.Chtimes(oldInProgress, oldTime, oldTime); err != nil {
		t.Fatalf("chtimes old in-progress: %v", err)
	}

	cleanIFSDir(root, time.Now().Add(-5*time.Minute))

	if _, err := os.Stat(oldFormal); !os.IsNotExist(err) {
		t.Fatalf("old formal file should be removed, stat err=%v", err)
	}
	if _, err := os.Stat(oldInProgress); err != nil {
		t.Fatalf("old in-progress file should remain, stat err=%v", err)
	}
	if _, err := os.Stat(youngFormal); err != nil {
		t.Fatalf("young formal file should remain, stat err=%v", err)
	}
}

func TestForwardBinaryUploadRequest(t *testing.T) {
	t.Run("downloads file URI and sends raw binary", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if ct := r.Header.Get("Content-Type"); ct != "application/octet-stream" {
				t.Errorf("expected Content-Type application/octet-stream, got %s", ct)
			}
			body, _ := io.ReadAll(r.Body)
			if len(body) == 0 {
				t.Error("expected non-empty body")
			}
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		tmpDir := t.TempDir()
		oldCfg := GetConfig()
		t.Setenv("MCP__RUNTIME__DOWNLOAD_DIR", tmpDir)
		LoadConfig("sonarqube-mcp")
		defer SetConfig(oldCfg)

		// Write a test file and use file:// URI
		srcFile := filepath.Join(tmpDir, "test.bin")
		if err := os.WriteFile(srcFile, []byte("binary content"), 0644); err != nil {
			t.Fatalf("failed to write test file: %v", err)
		}
		fileRefs := map[string]string{"file": "file://" + srcFile}
		result, err := ForwardBinaryUploadRequest(context.Background(), ts.URL, "PUT", "/api/upload", map[string]interface{}{}, fileRefs, "application/octet-stream", "TestBinaryUpload")
		if err != nil {
			t.Fatalf("ForwardBinaryUploadRequest failed: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
	})

	t.Run("deletes IFS upload source after forwarding", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			body, _ := io.ReadAll(r.Body)
			if string(body) != "ifs upload content" {
				t.Fatalf("unexpected body: %q", string(body))
			}
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		oldCfg := GetConfig()
		t.Setenv("HOME", t.TempDir())
		LoadConfig("sonarqube-mcp")
		defer SetConfig(oldCfg)

		uploadDir, err := resolveUploadDir()
		if err != nil {
			t.Fatalf("resolveUploadDir: %v", err)
		}
		if err := os.MkdirAll(uploadDir, 0755); err != nil {
			t.Fatalf("mkdir upload dir: %v", err)
		}
		sourceFile := filepath.Join(uploadDir, "upload-source.bin")
		if err := os.WriteFile(sourceFile, []byte("ifs upload content"), 0644); err != nil {
			t.Fatalf("write upload source: %v", err)
		}

		fileRefs := map[string]string{"file": "file://" + sourceFile}
		if _, err := ForwardBinaryUploadRequest(context.Background(), ts.URL, "PUT", "/api/upload", map[string]interface{}{}, fileRefs, "application/octet-stream", "TestBinaryUpload"); err != nil {
			t.Fatalf("ForwardBinaryUploadRequest failed: %v", err)
		}
		if _, err := os.Stat(sourceFile); !os.IsNotExist(err) {
			t.Fatalf("IFS upload source should be removed after forwarding, stat err=%v", err)
		}
	})

	t.Run("keeps non-IFS file URI after forwarding", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		oldCfg := GetConfig()
		t.Setenv("HOME", t.TempDir())
		LoadConfig("sonarqube-mcp")
		defer SetConfig(oldCfg)

		sourceFile := filepath.Join(t.TempDir(), "regular-source.bin")
		if err := os.WriteFile(sourceFile, []byte("regular content"), 0644); err != nil {
			t.Fatalf("write regular source: %v", err)
		}

		fileRefs := map[string]string{"file": "file://" + sourceFile}
		if _, err := ForwardBinaryUploadRequest(context.Background(), ts.URL, "PUT", "/api/upload", map[string]interface{}{}, fileRefs, "application/octet-stream", "TestBinaryUpload"); err != nil {
			t.Fatalf("ForwardBinaryUploadRequest failed: %v", err)
		}
		if _, err := os.Stat(sourceFile); err != nil {
			t.Fatalf("non-IFS source should remain after forwarding, stat err=%v", err)
		}
	})

	t.Run("empty file ref sends empty body", func(t *testing.T) {
		ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			body, _ := io.ReadAll(r.Body)
			if len(body) != 0 {
				t.Errorf("expected empty body, got %d bytes", len(body))
			}
			w.WriteHeader(http.StatusOK)
			w.Write([]byte(`{"ok":true}`))
		}))
		defer ts.Close()

		fileRefs := map[string]string{"file": ""}
		result, err := ForwardBinaryUploadRequest(context.Background(), ts.URL, "POST", "/api/upload", map[string]interface{}{}, fileRefs, "image/png", "TestEmptyBinaryUpload")
		if err != nil {
			t.Fatalf("ForwardBinaryUploadRequest failed: %v", err)
		}
		if result == nil {
			t.Fatal("result is nil")
		}
	})
}

func TestForwardMultipartRequestDeletesIFSUploadSource(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data; boundary=") {
			t.Fatalf("expected multipart content type, got %q", r.Header.Get("Content-Type"))
		}
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			t.Fatalf("parse multipart: %v", err)
		}
		file, header, err := r.FormFile("file")
		if err != nil {
			t.Fatalf("missing file part: %v", err)
		}
		if got := header.Header.Get("Content-Type"); got != "application/zip" {
			t.Fatalf("file part Content-Type = %q, want application/zip", got)
		}
		defer file.Close()
		body, _ := io.ReadAll(file)
		if string(body) != "multipart upload content" {
			t.Fatalf("unexpected file body: %q", string(body))
		}
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"ok":true}`))
	}))
	defer ts.Close()

	oldCfg := GetConfig()
	t.Setenv("HOME", t.TempDir())
	LoadConfig("sonarqube-mcp")
	defer SetConfig(oldCfg)

	uploadDir, err := resolveUploadDir()
	if err != nil {
		t.Fatalf("resolveUploadDir: %v", err)
	}
	if err := os.MkdirAll(uploadDir, 0755); err != nil {
		t.Fatalf("mkdir upload dir: %v", err)
	}
	sourceFile := filepath.Join(uploadDir, "multipart-source.zip")
	if err := os.WriteFile(sourceFile, []byte("multipart upload content"), 0644); err != nil {
		t.Fatalf("write upload source: %v", err)
	}

	fileRefs := map[string]string{"file": "file://" + sourceFile}
	if _, err := ForwardMultipartRequest(context.Background(), ts.URL, "POST", "/api/upload", map[string]interface{}{}, fileRefs, nil, nil, nil, "TestMultipartUpload"); err != nil {
		t.Fatalf("ForwardMultipartRequest failed: %v", err)
	}
	if _, err := os.Stat(sourceFile); !os.IsNotExist(err) {
		t.Fatalf("IFS upload source should be removed after multipart forwarding, stat err=%v", err)
	}
}

func TestForwardMultipartRequestOmitsMissingOptionalFile(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data; boundary=") {
			t.Fatalf("expected multipart content type, got %q", r.Header.Get("Content-Type"))
		}
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			t.Fatalf("parse multipart: %v", err)
		}
		if got := r.FormValue("note"); got != "no-file" {
			t.Fatalf("note form field = %q, want no-file", got)
		}
		if r.MultipartForm != nil {
			if files := r.MultipartForm.File["file"]; len(files) != 0 {
				t.Fatalf("optional file part should be omitted, got %d file parts", len(files))
			}
		}
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"ok":true}`))
	}))
	defer ts.Close()

	args := map[string]interface{}{"note": "no-file"}
	fileRefs := map[string]string{"file": ""}
	if _, err := ForwardMultipartRequest(context.Background(), ts.URL, "POST", "/api/upload", args, fileRefs, nil, nil, nil, "TestMultipartUpload"); err != nil {
		t.Fatalf("ForwardMultipartRequest failed: %v", err)
	}
}

func TestForwardMultipartRequestStringFileArgBecomesFormField(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			t.Fatalf("parse multipart: %v", err)
		}
		if got := r.FormValue("file"); got != "already-uploaded.zip" {
			t.Fatalf("file form field = %q, want already-uploaded.zip", got)
		}
		if r.MultipartForm != nil {
			if files := r.MultipartForm.File["file"]; len(files) != 0 {
				t.Fatalf("string branch should not create file parts, got %d", len(files))
			}
		}
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"ok":true}`))
	}))
	defer ts.Close()

	args := map[string]interface{}{"file": "already-uploaded.zip"}
	fileRefs := map[string]string{"file": "already-uploaded.zip"}
	if _, err := ForwardMultipartRequest(context.Background(), ts.URL, "POST", "/api/upload", args, fileRefs, nil, nil, nil, "TestMultipartUpload"); err != nil {
		t.Fatalf("ForwardMultipartRequest failed: %v", err)
	}
}

func TestForwardMultipartRequestSeparatesQueryAndFormFields(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if got := r.URL.Query().Get("configId"); got != "cfg-123" {
			t.Fatalf("configId query = %q, want cfg-123", got)
		}
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			t.Fatalf("parse multipart: %v", err)
		}
		if got := r.FormValue("note"); got != "form-note" {
			t.Fatalf("note form field = %q, want form-note", got)
		}
		if r.MultipartForm != nil {
			if values := r.MultipartForm.Value["configId"]; len(values) != 0 {
				t.Fatalf("query parameter configId should not be duplicated into form body, got %v", values)
			}
			if values := r.MultipartForm.Value["id"]; len(values) != 0 {
				t.Fatalf("path parameter id should not be duplicated into form body, got %v", values)
			}
		}
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"ok":true}`))
	}))
	defer ts.Close()

	args := map[string]interface{}{"id": "42", "configId": "cfg-123", "note": "form-note"}
	if _, err := ForwardMultipartRequest(context.Background(), ts.URL, "POST", "/api/reports/{id}/upload", args, nil, []string{"id"}, []string{"configId"}, nil, "TestMultipartUpload"); err != nil {
		t.Fatalf("ForwardMultipartRequest failed: %v", err)
	}
}

func TestForwardMultipartRequestUsesPartContentTypes(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		reader, err := r.MultipartReader()
		if err != nil {
			t.Fatalf("multipart reader: %v", err)
		}
		seenJSON := false
		seenFile := false
		for {
			part, err := reader.NextPart()
			if err == io.EOF {
				break
			}
			if err != nil {
				t.Fatalf("next part: %v", err)
			}
			switch part.FormName() {
			case "metadata":
				seenJSON = true
				if got := part.Header.Get("Content-Type"); got != "application/json" {
					t.Fatalf("metadata Content-Type = %q, want application/json", got)
				}
				body, _ := io.ReadAll(part)
				var got map[string]interface{}
				if err := json.Unmarshal(body, &got); err != nil {
					t.Fatalf("metadata JSON body = %s: %v", body, err)
				}
				if got["name"] != "report" || got["enabled"] != true {
					t.Fatalf("metadata body = %#v", got)
				}
			case "file":
				seenFile = true
				if got := part.Header.Get("Content-Type"); got != "application/zip" {
					t.Fatalf("file Content-Type = %q, want application/zip", got)
				}
			}
		}
		if !seenJSON {
			t.Fatal("missing metadata part")
		}
		if !seenFile {
			t.Fatal("missing file part")
		}
		w.WriteHeader(http.StatusOK)
		w.Write([]byte(`{"ok":true}`))
	}))
	defer ts.Close()

	oldCfg := GetConfig()
	t.Setenv("HOME", t.TempDir())
	LoadConfig("sonarqube-mcp")
	defer SetConfig(oldCfg)

	uploadDir, err := resolveUploadDir()
	if err != nil {
		t.Fatalf("resolveUploadDir: %v", err)
	}
	if err := os.MkdirAll(uploadDir, 0755); err != nil {
		t.Fatalf("mkdir upload dir: %v", err)
	}
	sourceFile := filepath.Join(uploadDir, "encoded-source.zip")
	if err := os.WriteFile(sourceFile, []byte("zip bytes"), 0644); err != nil {
		t.Fatalf("write upload source: %v", err)
	}

	args := map[string]interface{}{
		"metadata": map[string]interface{}{"name": "report", "enabled": true},
	}
	fileRefs := map[string]string{"file": "file://" + sourceFile}
	partContentTypes := map[string]string{"metadata": "application/json", "file": "application/zip"}
	if _, err := ForwardMultipartRequest(context.Background(), ts.URL, "POST", "/api/upload", args, fileRefs, nil, nil, partContentTypes, "TestMultipartUpload"); err != nil {
		t.Fatalf("ForwardMultipartRequest failed: %v", err)
	}
}
